import Button from "@mui/material/Button";
import MenuItem from "@mui/material/MenuItem";
import Stack from "@mui/material/Stack";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";

import { DashboardPage, DashboardPanel, DashboardUnavailableState } from "@/app/dashboard-ui";
import { requireTraderLinkPlatformServerComponentPageIdentity } from "@/src/modules/platform/server/authentication/require-platform-request-scope";
import { withReadonlyPlatformDatabase } from "@/src/modules/platform/server/database/open-readonly-platform-database";
import { shareWatchlistWithCommunityAction } from "./community-watchlist-share-action";

export default async function ShareCommunityWatchlistPage(){const identity=await requireTraderLinkPlatformServerComponentPageIdentity();const data=withReadonlyPlatformDatabase({},database=>({watchlists:database.prepare(`SELECT watchlist_id id,title FROM community_watchlists WHERE owner_user_id=? AND status='published' ORDER BY updated_at_utc DESC`).all(identity.scope.userId) as {id:string;title:string}[],targets:database.prepare(`SELECT c.community_id communityId,c.slug,c.display_name communityName,a.audience_id audienceId,a.name audienceName FROM traderlink_community_memberships m JOIN traderlink_communities c ON c.community_id=m.community_id JOIN traderlink_community_audiences a ON a.community_id=c.community_id AND a.status='active' WHERE m.user_id=? AND m.status='active' AND c.status='active' ORDER BY c.display_name,a.name`).all(identity.scope.userId) as {communityId:string;slug:string;communityName:string;audienceId:string;audienceName:string}[]}));return <DashboardPage><Typography component="h1" variant="h1">Share a watchlist with your community</Typography>{data.watchlists.length&&data.targets.length?<DashboardPanel title="Choose where to share"><form action={shareWatchlistWithCommunityAction}><Stack spacing={2}><TextField label="Your published watchlist" name="watchlistId" select required>{data.watchlists.map(w=><MenuItem key={w.id} value={w.id}>{w.title}</MenuItem>)}</TextField><TextField helperText="The server owner controls which Discord roles belong to each audience." label="Community audience" name="target" select required>{data.targets.map(t=><MenuItem key={`${t.communityId}-${t.audienceId}`} value={`${t.communityId}|${t.audienceId}|${t.slug}`}>{t.communityName} · {t.audienceName}</MenuItem>)}</TextField><Button type="submit" variant="contained">Share TraderLink page</Button></Stack></form></DashboardPanel>:<DashboardUnavailableState actionHref={data.watchlists.length?"/communities":"/community/watchlists/new"} actionLabel={data.watchlists.length?"Open communities":"Create a watchlist"} description={data.watchlists.length?"Join an onboarded Discord community before sharing.":"Publish one of your own Community Watchlists first."} title="Nothing ready to share"/>}<DashboardPanel title="Your watchlist stays yours"><Typography variant="body2">Sharing creates a community placement and a link back to the original TraderLink page. It does not copy ownership or expose your Journal.</Typography></DashboardPanel></DashboardPage>}
