import assert from 'node:assert/strict';
import Database from '../app/node_modules/better-sqlite3/lib/index.js';
import {platformMigrationManifest as manifest} from '../app/src/modules/platform/server/database/platform-migration-manifest';
import {runPlatformMigrations,verifyCompletedPlatformDatabase} from '../app/src/modules/platform/server/database/run-platform-migrations';
const db=new Database(':memory:');db.pragma('foreign_keys=ON');assert.equal(manifest.length,129);assert.equal(manifest.at(-1)?.migrationId,'0147_watchlist_potential_gain_posts');
runPlatformMigrations(db,{manifest:manifest.slice(0,-1)});const before=db.prepare('SELECT * FROM platform_schema_migrations ORDER BY execution_order').all();
const tables=db.prepare("SELECT name FROM sqlite_schema WHERE type='table' AND name NOT LIKE 'sqlite_%' AND name<>'platform_schema_migrations'").all() as {name:string}[];
const counts=tables.map(t=>[t.name,db.prepare('SELECT COUNT(*) AS n FROM "'+t.name+'"').get()]);
assert.deepEqual(runPlatformMigrations(db).appliedMigrationIds,['0147_watchlist_potential_gain_posts']);assert.deepEqual(db.prepare('SELECT * FROM platform_schema_migrations ORDER BY execution_order LIMIT 128').all(),before);
for(const [name,count] of counts)assert.deepEqual(db.prepare('SELECT COUNT(*) AS n FROM "'+name+'"').get(),count);
verifyCompletedPlatformDatabase(db);assert.deepEqual(runPlatformMigrations(db).appliedMigrationIds,[]);db.close();console.log('PASS exact128-to129 synthetic rehearsal, predecessor preserved, old counts preserved and idempotency. Hosted backup remains required.');
