import {
  IBKR_SOURCE_ACCOUNT_CANONICALIZERS,
  IBKR_SOURCE_ACCOUNT_CANONICALIZATION_VERSION,
} from "./ibkr-source-account-canonicalizer";
import {
  JOURNAL_SOURCE_ACCOUNT_CANONICALIZERS,
} from "./mapped-statement-source-account-canonicalizer";

export const ALL_JOURNAL_SOURCE_ACCOUNT_CANONICALIZERS = Object.freeze({
  ...IBKR_SOURCE_ACCOUNT_CANONICALIZERS,
  ...JOURNAL_SOURCE_ACCOUNT_CANONICALIZERS,
});

export const DEFAULT_JOURNAL_SOURCE_ACCOUNT_CANONICALIZATION_VERSION =
  IBKR_SOURCE_ACCOUNT_CANONICALIZATION_VERSION;
