import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const repositoryRoot = process.cwd();
const categoryDirectory = path.join(
  repositoryRoot,
  "docs",
  "migration",
  "language-inventory",
  "categories",
);
const outputPath = path.join(
  repositoryRoot,
  "src",
  "modules",
  "coach",
  "server",
  "coach-ai-chat-language-inventory.generated.ts",
);

const runtimeTargets: Readonly<Record<string, string>> = Object.freeze({
  retrieve_records: "closed_trade_facts",
  summarize_performance: "closed_trade_facts",
  calculate_metric: "closed_trade_facts",
  compare_groups: "closed_trade_facts",
  group_and_aggregate: "closed_trade_facts",
  rank_results: "closed_trade_facts",
  explain_result: "closed_trade_facts",
  journal_writing_reflection: "daily_tracker_drafts",
  product_help: "product_help",
  prepare_manual_execution_draft: "manual_execution_drafts",
  prepare_user_setting_change: "review_delivery_draft",
  assist_daily_review: "daily_tracker_drafts",
  gross_profit: "closed_trade_facts",
  gross_loss: "closed_trade_facts",
  gross_pnl: "closed_trade_facts",
  net_pnl: "closed_trade_facts",
  average_net_pnl_per_trade: "closed_trade_facts",
  median_net_pnl_per_trade: "closed_trade_facts",
  largest_win: "closed_trade_facts",
  largest_loss: "closed_trade_facts",
  average_winning_trade: "closed_trade_facts",
  average_losing_trade: "closed_trade_facts",
  pnl_by_direction: "closed_trade_facts",
  pnl_before_fees: "closed_trade_facts",
  pnl_after_fees: "closed_trade_facts",
  trade_count: "closed_trade_facts",
  winning_trades: "closed_trade_facts",
  losing_trades: "closed_trade_facts",
  breakeven_trades: "closed_trade_facts",
  closed_trades: "closed_trade_facts",
  win_rate: "closed_trade_facts",
  loss_rate: "closed_trade_facts",
  breakeven_rate: "closed_trade_facts",
  expectancy: "closed_trade_facts",
  profit_factor: "closed_trade_facts",
  week: "closed_trade_facts",
  month: "closed_trade_facts",
  year: "closed_trade_facts",
});

type InventoryEntry = Readonly<{
  canonicalName: string;
  categoryFile: string;
  sourceCapabilityStatus: string;
  runtimeCapabilityId: string | null;
}>;

const categoryFiles = readdirSync(categoryDirectory)
  .filter((fileName) => /^\d{2}-.*\.md$/u.test(fileName))
  .sort((left, right) => left.localeCompare(right));
const sourceParts: string[] = [];
const entries: InventoryEntry[] = [];

for (const categoryFile of categoryFiles) {
  const source = readFileSync(path.join(categoryDirectory, categoryFile), "utf8")
    .replace(/\r\n?/gu, "\n");
  sourceParts.push(`${categoryFile}\n${source}\n`);
  const lines = source.split("\n");
  let canonicalName: string | null = null;
  for (const line of lines) {
    const canonicalMatch = /^\| Canonical name \| `?([^|`]+)`? \|$/u.exec(line);
    if (canonicalMatch) {
      canonicalName = canonicalMatch[1]?.trim() ?? null;
      continue;
    }
    const statusMatch = /^\| Capability status \| ([^|]+) \|$/u.exec(line);
    if (!statusMatch || canonicalName === null) continue;
    entries.push(Object.freeze({
      canonicalName,
      categoryFile,
      sourceCapabilityStatus: statusMatch[1]!.trim(),
      runtimeCapabilityId: runtimeTargets[canonicalName] ?? null,
    }));
    canonicalName = null;
  }
}

if (entries.length !== 417) {
  throw new Error(`Expected 417 locked language names, found ${entries.length}.`);
}

const sourceSha256 = createHash("sha256")
  .update(sourceParts.join(""), "utf8")
  .digest("hex");
const generated = `/* This file is generated by src/scripts/generate-coach-ai-chat-language-registry.ts. */
/* Do not edit it by hand or treat vocabulary coverage as calculation support. */

export const COACH_AI_CHAT_LANGUAGE_INVENTORY_SOURCE_SHA256 = ${JSON.stringify(sourceSha256)} as const;

export type CoachAiChatLanguageInventoryEntry = Readonly<{
  canonicalName: string;
  categoryFile: string;
  sourceCapabilityStatus: string;
  runtimeCapabilityId: string | null;
}>;

export const coachAiChatLanguageInventory = Object.freeze(${JSON.stringify(entries, null, 2)}) satisfies readonly CoachAiChatLanguageInventoryEntry[];
`;

writeFileSync(outputPath, generated, "utf8");
process.stdout.write(`Generated ${entries.length} AI Chat language entries.\n`);
