



import Database from "better-sqlite3";

import { platformIdentityMigration } from "../modules/platform/server/database/migrations/0001_platform_identity";
import { journalAccountBoundaryMigration } from "../modules/journal/server/database/migrations/0002_journal_account_boundary";
import { platformAuthenticationIdentitiesMigration } from "../modules/platform/server/database/migrations/0012_platform_authentication_identities";
import { platformDiscordMembershipsMigration } from "../modules/platform/server/database/migrations/0017_platform_discord_memberships";
import { communityWatchlistsMigration } from "../modules/community/server/database/migrations/0076_community_watchlists";
import { traderLinkCommunitiesIdentityPermissionsMigration } from "../modules/communities/server/database/migrations/0121_traderlink_communities_identity_permissions";
import { traderLinkCommunitiesPartnerPlatformMigration } from "../modules/communities/server/database/migrations/0122_traderlink_communities_partner_platform";
import { traderLinkCommunitiesDiscordFeatureAccessMigration } from "../modules/communities/server/database/migrations/0123_traderlink_communities_discord_feature_access";
import { traderLinkCommunitiesServerWatchlistsMigration } from "../modules/communities/server/database/migrations/0124_traderlink_communities_server_watchlists";
import { traderLinkCommunitiesPrivatePilotBootstrapMigration } from "../modules/communities/server/database/migrations/0125_traderlink_communities_private_pilot_bootstrap";
import { traderLinkCommunitiesWorkspaceToolsMigration } from "../modules/communities/server/database/migrations/0126_traderlink_communities_workspace_tools";
import { traderLinkCommunitiesCoachingWorkspaceMigration } from "../modules/communities/server/database/migrations/0127_traderlink_communities_coaching_workspace";
import { traderLinkCommunitiesCoachingProgramsMigration } from "../modules/communities/server/database/migrations/0128_traderlink_communities_coaching_programs";
import { traderLinkCommunitiesCoachingPlanBuilderMigration } from "../modules/communities/server/database/migrations/0129_traderlink_communities_coaching_plan_builder";
import { traderLinkCommunitiesCoachingServiceMeasurementMigration } from "../modules/communities/server/database/migrations/0130_traderlink_communities_coaching_service_measurement";
import { traderLinkCommunitiesReviewCoachingSectionsMigration } from "../modules/communities/server/database/migrations/0131_traderlink_communities_review_coaching_sections";
import { TraderLinkCommunityRepository } from "../modules/communities/server/traderlink-community-repository";
import { TraderLinkCommunityPlatformRepository } from "../modules/communities/server/traderlink-community-platform-repository";
import { TraderLinkCommunityCoachingProgramService } from "../modules/communities/server/traderlink-community-coaching-program-service";


import {strict as check} from "node:assert";
import {traderLinkCommunitiesReviewWorkflowMigration} from "../modules/communities/server/database/migrations/0143_traderlink_communities_review_workflow";
import {traderLinkCommunitiesReviewWorkspaceMetadataMigration} from "../modules/communities/server/database/migrations/0144_traderlink_communities_review_workspace_metadata";
import {traderLinkCommunitiesCoachingDeliveryWorkflowMigration} from "../modules/communities/server/database/migrations/0145_traderlink_communities_coaching_delivery_workflow";
import {CoachingAgreementService} from "../modules/communities/server/coaching-agreement-service";
import {coachingPeriod,coachingReviewCoverage} from "../modules/communities/contracts/coaching-agreements";
import {coachingEntitlement,reconcileCoachingAccess,archivePausedCoaching} from "../modules/communities/server/coaching-access-lifecycle";
import {questionAllowance} from "../modules/communities/server/coaching-service-limits";
import {CoachingDiscordRefreshService} from "../modules/communities/server/coaching-discord-refresh-service";
import {runCoachingMaintenance,nonOverlappingCoachingMaintenance} from "../modules/communities/server/coaching-maintenance-service";
import {TraderLinkCommunityCoachJournalReadService} from "../modules/communities/server/traderlink-community-coach-journal-read-service";
const NOW="2026-09-05T12:00:00.000Z";
const OWNER="10000000-0000-4000-8000-000000000001",MEMBER="10000000-0000-4000-8000-000000000002",OUTSIDER="10000000-0000-4000-8000-000000000003",WORKSPACE="10000000-0000-4000-8000-000000000004",ACCOUNT="10000000-0000-4000-8000-000000000005",OUTSIDER_WORKSPACE="10000000-0000-4000-8000-000000000007",OUTSIDER_ACCOUNT="10000000-0000-4000-8000-000000000008",PILOT_GUILD="1433570740430573642";
function assert(value:unknown,message:string):asserts value{check.ok(value,message);}
async function main(){
const database=new Database(":memory:");database.pragma("foreign_keys=ON");
try{
  for(const migration of [platformIdentityMigration,journalAccountBoundaryMigration,platformAuthenticationIdentitiesMigration,platformDiscordMembershipsMigration,communityWatchlistsMigration,traderLinkCommunitiesIdentityPermissionsMigration,traderLinkCommunitiesPartnerPlatformMigration,traderLinkCommunitiesDiscordFeatureAccessMigration,traderLinkCommunitiesServerWatchlistsMigration,traderLinkCommunitiesWorkspaceToolsMigration,traderLinkCommunitiesCoachingWorkspaceMigration,traderLinkCommunitiesCoachingProgramsMigration,traderLinkCommunitiesCoachingPlanBuilderMigration,traderLinkCommunitiesCoachingServiceMeasurementMigration,traderLinkCommunitiesReviewCoachingSectionsMigration,traderLinkCommunitiesReviewWorkflowMigration,traderLinkCommunitiesReviewWorkspaceMetadataMigration,traderLinkCommunitiesCoachingDeliveryWorkflowMigration]){
    for(const statement of migration.statements)database.exec(statement);
  }
  const insertUser=database.prepare(`INSERT INTO platform_users(user_id,auth_provider,auth_subject,display_name,status,created_at_utc,updated_at_utc) VALUES(?, 'discord', ?, ?, 'active', ?, ?)`);
  const insertIdentity=database.prepare(`INSERT INTO platform_auth_identities(user_id,auth_provider,auth_subject,status,linked_by_user_id,created_at_utc,updated_at_utc,last_authenticated_at_utc) VALUES(?,'discord',?,'active',?,?,?,?)`);
  const insertDiscord=database.prepare(`INSERT INTO platform_discord_memberships(user_id,guild_id,username,global_display_name,avatar_hash,role_ids_json,guild_owner,joined_at_utc,first_verified_at_utc,last_verified_at_utc) VALUES(?,?,?,?,NULL,?,?,?,?,?)`);
  for(const [id,subject,name] of [[OWNER,"123456789","Owner"],[MEMBER,"member-subject","Member"],[OUTSIDER,"outsider-subject","Outsider"]] as const){insertUser.run(id,subject,name,NOW,NOW);insertIdentity.run(id,subject,id,NOW,NOW,NOW);}
  insertDiscord.run(OWNER,PILOT_GUILD,"owner","Owner","[]",1,NOW,NOW,NOW);
  insertDiscord.run(MEMBER,PILOT_GUILD,"member","Member",JSON.stringify(["200001"]),0,NOW,NOW,NOW);
  insertDiscord.run(OUTSIDER,"900002","outsider","Outsider","[]",1,NOW,NOW,NOW);
  database.prepare(`INSERT INTO platform_workspaces(workspace_id,display_name,default_trading_timezone,status,created_at_utc,updated_at_utc) VALUES(?,?,'America/Toronto','active',?,?)`).run(WORKSPACE,"Member workspace",NOW,NOW);
  database.prepare(`INSERT INTO platform_workspaces(workspace_id,display_name,default_trading_timezone,status,created_at_utc,updated_at_utc) VALUES(?,?,'America/Toronto','active',?,?)`).run(OUTSIDER_WORKSPACE,"Outsider workspace",NOW,NOW);
  database.prepare(`INSERT INTO platform_workspace_memberships(workspace_id,user_id,role,status,created_by_user_id,created_at_utc,updated_at_utc) VALUES(?,?,'owner','active',?,?,?)`).run(WORKSPACE,OWNER,OWNER,NOW,NOW);
  database.prepare(`INSERT INTO platform_workspace_memberships(workspace_id,user_id,role,status,created_by_user_id,created_at_utc,updated_at_utc) VALUES(?,?,'owner','active',?,?,?)`).run(OUTSIDER_WORKSPACE,OUTSIDER,OUTSIDER,NOW,NOW);
  database.prepare(`INSERT INTO journal_accounts(account_id,workspace_id,display_name,base_currency,trading_timezone,status,created_by_user_id,created_at_utc,updated_at_utc) VALUES(?,?,?,'USD','America/Toronto','active',?,?,?)`).run(ACCOUNT,WORKSPACE,"Trading account",OWNER,NOW,NOW);
  database.prepare(`INSERT INTO journal_accounts(account_id,workspace_id,display_name,base_currency,trading_timezone,status,created_by_user_id,created_at_utc,updated_at_utc) VALUES(?,?,?,'USD','America/Toronto','active',?,?,?)`).run(OUTSIDER_ACCOUNT,OUTSIDER_WORKSPACE,"Outsider account",OUTSIDER,NOW,NOW);

  const permissions=new TraderLinkCommunityRepository(database);
  const platform=new TraderLinkCommunityPlatformRepository(database);
  const first=permissions.createFromVerifiedDiscordOwner({ownerUserId:OWNER,discordGuildId:PILOT_GUILD,slug:"first-room",displayName:"First Room",timestamp:NOW});
  for(const statement of traderLinkCommunitiesPrivatePilotBootstrapMigration.statements)database.exec(statement);
  assert((database.prepare(`SELECT count(*) count FROM traderlink_community_discord_role_mappings WHERE community_id=? AND status='active'`).get(first.communityId) as {count:number}).count===3,"Pilot bootstrap must install only the three server-feature Discord role mappings; test-community is superseded by the automatic all-member baseline.");
  assert((database.prepare(`SELECT count(*) count FROM traderlink_community_discord_destinations WHERE community_id=? AND status='active'`).get(first.communityId) as {count:number}).count===3,"Pilot bootstrap must install the three supplied Discord channel destinations.");
  const second=permissions.createFromVerifiedDiscordOwner({ownerUserId:OUTSIDER,discordGuildId:"900002",slug:"second-room",displayName:"Second Room",timestamp:NOW});
  permissions.setStatus({communityId:first.communityId,actorUserId:OWNER,status:"active",timestamp:NOW});
  permissions.setStatus({communityId:second.communityId,actorUserId:OUTSIDER,status:"active",timestamp:NOW});
  permissions.syncActiveMemberFromDiscord({communityId:first.communityId,userId:MEMBER,timestamp:NOW});

permissions.saveDiscordFeatureMapping({communityId:first.communityId,actorUserId:OWNER,discordRoleId:"200001",discordRoleName:"Coaching",responsibilities:["coach"],timestamp:NOW});
const everyone=platform.ensureDefaultAudience({communityId:first.communityId,actorUserId:OWNER,atUtc:NOW});
  const coach=platform.upsertCoach({communityId:first.communityId,actor:{userId:MEMBER,displayName:"Member",discordRoleIds:["200001"]},userId:MEMBER,displayName:"Member Coach",headline:"",biography:"",deliverySummary:"",capacity:1,active:true,atUtc:NOW});
  const plan=platform.createPlan({communityId:first.communityId,actor:{userId:MEMBER,displayName:"Member",discordRoleIds:["200001"]},coachProfileId:coach,name:"One review",description:"",cadence:"trade_reviews",tradeReviewLimit:1,studentCapacity:1,messagingIncluded:true,tradeReviewsIncluded:true,sessionsIncluded:true,teachingIncluded:true,priceLabel:"Handled in Discord",priceAmountMinor:5000,currency:"USD",billingCadence:"monthly",quoteRequired:false,paymentInstructions:"Contact the server owner.",audienceId:everyone,requiredDiscordRoleId:"200001",planStyle:"structured",items:[{itemType:"trade_review",frequency:"weekly",coveragePeriod:"previous_7_days",quantity:1,dueOffsetDays:2,selectionMode:"coach_or_student",followUpDays:0,measurementKind:"trades",plannedMinutes:null,timelineEnabled:true,reviewDepth:"standard"}],journalScopes:[{dataScope:"trades",required:true}],publish:true,atUtc:NOW});
  database.prepare(`UPDATE platform_discord_memberships SET role_ids_json=? WHERE user_id=? AND guild_id=?`).run(JSON.stringify(["200001"]),OWNER,PILOT_GUILD);
  const relationship=platform.requestCoaching({communityId:first.communityId,actor:{userId:OWNER,displayName:"Owner",discordRoleIds:[]},planId:plan,atUtc:NOW});
  assert(platform.requestCoaching({communityId:first.communityId,actor:{userId:OWNER,displayName:"Owner",discordRoleIds:[]},planId:plan,atUtc:NOW})===relationship,"Repeated coaching requests must remain idempotent while pending.");
  platform.setRelationshipStatus({communityId:first.communityId,actor:{userId:MEMBER,displayName:"Member",discordRoleIds:["200001"]},relationshipId:relationship,status:"active",atUtc:NOW});

const actor={userId:MEMBER,displayName:"Coach",discordRoleIds:["200001"]},student={userId:OWNER,displayName:"Student",discordRoleIds:["200001"]};
const service=new CoachingAgreementService(database);
const base={communityId:first.communityId,relationshipId:relationship,actor,atUtc:NOW};
const agreementId=service.propose({...base,startDate:"2026-09-01",dueTimeUtc:"17:00"});
check.equal(service.generate({...base,throughDate:"2026-09-30"}),0,"Unsigned agreement creates no work");
check.throws(()=>service.accept({...base,agreementId}),"Coach cannot accept for student");
service.accept({...base,actor:student,agreementId});
const generated=service.generate({...base,throughDate:"2026-09-30"});
check.equal(generated,5,"One weekly trade review per period");
check.equal(service.generate({...base,throughDate:"2026-09-30"}),0,"Repeated scheduling is idempotent");
const snapshot=platform.readSnapshot("first-room",actor);
check.equal(snapshot.coachingAgreements?.[0]?.status,"accepted");
const terms=snapshot.coachingAgreements![0].terms;
check.equal(coachingPeriod({...terms,startDate:"2026-01-31"},{...terms.items[0],frequency:"monthly"},1)?.start,"2026-02-28");
check.equal(coachingPeriod({...terms,startDate:"2026-01-31"},{...terms.items[0],frequency:"monthly"},2)?.start,"2026-03-31","Monthly cadence retains original anchor");
check.equal(coachingPeriod({...terms,startDate:null},terms.items[0],0),null);
const period={start:"2026-09-02",end:"2026-09-08"};
check.deepEqual(coachingReviewCoverage(terms,{...terms.items[0],coveragePeriod:"calendar_week"},period),{start:"2026-08-31",end:"2026-09-06"});
check.deepEqual(coachingReviewCoverage(terms,{...terms.items[0],coveragePeriod:"previous_month"},period),{start:"2026-08-01",end:"2026-08-31"});
check.deepEqual(coachingReviewCoverage(terms,{...terms.items[0],coveragePeriod:"since_last_review"},period,"2026-09-03"),{start:"2026-09-04",end:"2026-09-08"});
check.deepEqual(coachingReviewCoverage({...terms,coverageDays:{[terms.items[0].planItemId]:3}},{...terms.items[0],coveragePeriod:"custom"},period),{start:"2026-09-06",end:"2026-09-08"});
check.throws(()=>coachingReviewCoverage(terms,{...terms.items[0],coveragePeriod:"custom"},period),"Custom coverage must be agreed explicitly");
check.throws(()=>service.generate({...base,actor:{userId:OUTSIDER,displayName:"Outsider",discordRoleIds:[]},throughDate:"2026-09-30"}),"Unrelated coach cannot schedule this student");
const original=snapshot.plans.find(item=>item.planId===plan)!;
const edit={...original,communityId:first.communityId,actor,planId:plan,expectedRevision:original.revision,saveExisting:true,atUtc:NOW,publish:false,tradeReviewLimit:original.tradeReviewLimit??undefined,priceAmountMinor:original.priceAmountMinor??undefined,requiredDiscordRoleId:original.requiredDiscordRoleId??undefined,autoArchiveAfterDays:30,name:"Updated offer",description:"First line\nSecond line",builderConfig:{about:"Updated offer",offers:{trade_review:{details:"Review each trade",resources:["Analytics reports"]}}}};
platform.createPlan(edit);
check.throws(()=>platform.createPlan(edit),"Stale editor cannot overwrite newer plan");
const edited=platform.readSnapshot("first-room",actor).plans.find(item=>item.planId===plan)!;
check.equal(edited.status,"active","Editing a published plan retains publication");
check.equal(edited.builderConfig?.offers.trade_review?.resources[0],"Analytics reports");
check.equal(service.generate({...base,throughDate:"2026-09-30"}),0,"Editing does not recreate scheduled work");
check.equal(platform.readSnapshot("first-room",actor).coachingAgreements?.find(item=>item.agreementId===agreementId)?.terms.planName,"One review","Accepted agreement stays frozen");
const included=edited.items[0];
platform.createPlan({...edit,expectedRevision:edited.revision,items:[included,{...included,itemType:"questions",measurementKind:"questions",quantity:2,selectionMode:"not_applicable"},{...included,itemType:"review_follow_up",measurementKind:"reviews",followUpDays:3,selectionMode:"not_applicable"}],messagingIncluded:true});
const revisedId=service.propose({...base,startDate:"2026-09-01",dueTimeUtc:"17:00"});
service.accept({...base,actor:student,agreementId:revisedId});
service.accept({...base,actor:student,agreementId:revisedId});
check.equal(service.generate({...base,throughDate:"2026-09-30"}),0,"Agreement revisions preserve existing periods");
platform.sendCoachingMessage({...base,actor:student,body:"First question"});
platform.sendCoachingMessage({...base,actor:student,body:"Second question"});
check.throws(()=>platform.sendCoachingMessage({...base,actor:student,body:"Third question"}),"Question limit enforced");
check.equal(questionAllowance(database,relationship,OWNER,NOW)?.remaining,0);
platform.sendCoachingMessage({...base,actor:student,body:"Next week",atUtc:"2026-09-08T12:00:00.000Z"});
check.equal(questionAllowance(database,relationship,OWNER,"2026-09-08T12:00:00.000Z")?.remaining,1);
const programs=new TraderLinkCommunityCoachingProgramService(database);
const chart=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jf6kAAAAASUVORK5CYII=","base64");
const conversationImage=programs.addImage({...base,actor:student,targetType:"message",targetId:relationship,filename:"conversation-chart.png",mediaType:"image/png",content:chart});
check.ok(programs.readImage({communityId:first.communityId,actor,attachmentId:conversationImage}).content.equals(chart),"Conversation-root images reach the coach");
check.throws(()=>programs.addImage({...base,actor:student,targetType:"message",targetId:OUTSIDER,filename:"wrong-thread.png",mediaType:"image/png",content:chart}),"Images cannot target another conversation");
const journal=new TraderLinkCommunityCoachJournalReadService(database);
check.throws(()=>journal.readAnalysisScope({coachUserId:MEMBER,relationshipId:relationship}),"No account data without a grant");
const analyticsGrant=platform.grantJournal({...base,actor:student,journalAccountId:ACCOUNT,dataScope:"analytics"});
check.equal(journal.readAnalysisScope({coachUserId:MEMBER,relationshipId:relationship}).canReadTrades,false,"Analytics-only sharing excludes trade details");
check.throws(()=>journal.readAnalysisScope({coachUserId:OUTSIDER,relationshipId:relationship}),"Different coach cannot use student's analysis scope");
check.throws(()=>platform.grantJournal({...base,actor:student,journalAccountId:OUTSIDER_ACCOUNT,dataScope:"complete"}),"Student cannot share another account");
const fullGrant=platform.grantJournal({...base,actor:student,journalAccountId:ACCOUNT,dataScope:"complete"});
const analysisAccess=journal.readAnalysisScope({coachUserId:MEMBER,relationshipId:relationship});
check.equal(analysisAccess.canReadTrades,true);check.deepEqual(analysisAccess.scope.allowedAccountIds,[ACCOUNT]);
platform.revokeJournal({actorUserId:OWNER,grantId:fullGrant,atUtc:NOW});
platform.revokeJournal({actorUserId:OWNER,grantId:analyticsGrant,atUtc:NOW});
check.throws(()=>journal.readAnalysisScope({coachUserId:MEMBER,relationshipId:relationship}),"Revoked analysis grants stop access");
const reviewId=programs.createReview({...base,title:"Delivery QA",context:"",reviewType:"custom",roundTripIds:[]});
const imageId=programs.addImage({...base,targetType:"review",targetId:reviewId,reviewId,filename:"chart.png",mediaType:"image/png",content:Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jf6kAAAAASUVORK5CYII=","base64")});
check.throws(()=>programs.readImage({communityId:first.communityId,actor:student,attachmentId:imageId}),"Unsent review images hidden from students");
programs.saveFocusFeedback({...base,reviewId,feedback:{}});
check.throws(()=>programs.deliverReview({...base,reviewId}),"Empty reviews cannot be sent");
platform.updateTradeReview({...base,reviewId,coachFeedback:"Shared review",wentWell:"",needsWork:"",nextFocus:"Practice entries",coachPrivateNotes:"Private QA note",previousFocusStatus:null,previousFocusAssessment:"",status:"in_review"});
check.equal(platform.readSnapshot("first-room",student).tradeReviews.find(item=>item.reviewId===reviewId)?.coachFeedback,"");
programs.deliverReview({...base,reviewId});
check.ok(programs.readImage({communityId:first.communityId,actor:student,attachmentId:imageId}).content.length>0,"Delivered chart available to intended student");
check.throws(()=>programs.readImage({communityId:first.communityId,actor:{userId:OUTSIDER,displayName:"Outsider",discordRoleIds:[]},attachmentId:imageId}),"Images isolated from unrelated users");
check.throws(()=>programs.replyToReview({...base,actor:student,reviewId,body:"Before read"}),"Follow-up starts after read confirmation");
programs.markReviewViewed({...base,actor:student,reviewId});
programs.replyToReview({...base,actor:student,reviewId,body:"Follow-up"});
check.throws(()=>programs.replyToReview({...base,actor:student,reviewId,body:"Late follow-up",atUtc:"2026-09-09T12:00:00.000Z"}),"Follow-up expiry enforced");
check.equal(platform.readSnapshot("first-room",student).tradeReviews.find(item=>item.reviewId===reviewId)?.coachPrivateNotes,"");
const sessionId=programs.createSession({...base,title:"Session",agenda:"Agenda"});
programs.updateSession({...base,sessionId,title:"Session",agenda:"Shared agenda",notes:"Shared notes",privateNotes:"Private notes",meetingUrl:"https://example.com/meeting",durationMinutes:45,scheduledAtUtc:"2026-09-10T14:00:00.000Z",attendance:"attended",status:"completed"});
const studentSession=platform.readSnapshot("first-room",student).coachingSessions.find(item=>item.sessionId===sessionId)!;
check.equal(studentSession.coachPrivateNotes,"");check.equal(studentSession.durationMinutes,45);check.equal(studentSession.meetingUrl,"https://example.com/meeting");
const teachingId=programs.createTeaching({...base,title:"Lesson",teachingType:"lesson",body:"Lesson content",deliveryUrl:"https://example.com/lesson",audienceMode:"all_students",relationshipIds:[],publish:false});
check.ok(!platform.readSnapshot("first-room",student).teachingItems.some(item=>item.teachingId===teachingId),"Draft lesson hidden from students");
programs.updateTeachingDetails({...base,teachingId,title:"Lesson",body:"Lesson content",deliveryUrl:"https://example.com/lesson",recordingUrl:"https://example.com/recording",deliveryKind:"recorded",status:"published"});
check.equal(platform.readSnapshot("first-room",student).teachingItems.find(item=>item.teachingId===teachingId)?.recordingUrl,"https://example.com/recording");
programs.updateTeachingStudent({...base,teachingId,status:"completed"});
check.equal(platform.readSnapshot("first-room",actor).teachingItems.find(item=>item.teachingId===teachingId)?.students[0]?.status,"completed","Coach can record lesson progress");
check.throws(()=>programs.updateTeachingDetails({...base,teachingId,title:"Lesson",body:"",deliveryUrl:"javascript:alert(1)",recordingUrl:"",deliveryKind:"live",status:"published"}),"Only web links accepted");
const reused=programs.createTeaching({...base,sourceTeachingId:teachingId,title:"Reused lesson",teachingType:"lesson",body:"Lesson content",deliveryUrl:"https://example.com/lesson",audienceMode:"all_students",relationshipIds:[],publish:false});
check.notEqual(reused,teachingId);
check.equal(platform.readSnapshot("first-room",actor).teachingItems.find(item=>item.teachingId===reused)?.recordingUrl,"https://example.com/recording");
const roleTime="2026-09-10T12:00:00.000Z";
database.prepare(`UPDATE platform_discord_memberships SET role_ids_json='[]',last_verified_at_utc=? WHERE user_id=? AND guild_id=?`).run(roleTime,OWNER,PILOT_GUILD);
reconcileCoachingAccess(database,first.communityId,OWNER,roleTime);
reconcileCoachingAccess(database,first.communityId,OWNER,roleTime);
check.equal(coachingEntitlement(database,relationship)?.present,false);
check.throws(()=>programs.createReview({...base,title:"Blocked",context:"",reviewType:"custom",roundTripIds:[]}),"Role removal blocks new work");
check.equal((database.prepare(`SELECT count(*) count FROM traderlink_community_coaching_notices WHERE kind='access_paused'`).get() as {count:number}).count,2,"One pause notice for each party");
check.equal(archivePausedCoaching(database,"2026-09-20T12:00:00.000Z"),0);
check.equal(archivePausedCoaching(database,"2026-10-11T12:00:00.000Z"),1);
check.ok(platform.readSnapshot("first-room",actor).tradeReviews.some(item=>item.reviewId===reviewId),"Archived records preserved");
const restoredAt="2026-10-12T12:00:00.000Z";
database.prepare(`UPDATE platform_discord_memberships SET role_ids_json='["200001"]',last_verified_at_utc=? WHERE user_id=? AND guild_id=?`).run(restoredAt,OWNER,PILOT_GUILD);
reconcileCoachingAccess(database,first.communityId,OWNER,restoredAt);
check.equal(coachingEntitlement(database,relationship)?.present,true);
check.equal((database.prepare(`SELECT count(*) count FROM traderlink_community_coaching_notices WHERE kind='access_restored'`).get() as {count:number}).count,2);
database.prepare(`UPDATE traderlink_community_coaching_relationships SET archived_at_utc=NULL WHERE relationship_id=?`).run(relationship);
const latestPlan=platform.readSnapshot("first-room",actor).plans.find(item=>item.planId===plan)!;
platform.createPlan({...edit,expectedRevision:latestPlan.revision,items:[{...included,itemType:"private_session",measurementKind:"sessions",frequency:"once",quantity:150,selectionMode:"not_applicable"}],sessionsIncluded:true});
const batchAgreement=service.propose({...base,atUtc:restoredAt,startDate:"2026-10-12",dueTimeUtc:"17:00"});
service.accept({...base,atUtc:restoredAt,actor:student,agreementId:batchAgreement});
check.equal(service.generate({...base,atUtc:restoredAt,throughDate:"2026-10-12"}),120,"Large batches save bounded progress");
check.equal(service.generate({...base,atUtc:restoredAt,throughDate:"2026-10-12"}),30,"Next batch resumes remaining slots");
check.equal(service.generate({...base,atUtc:restoredAt,throughDate:"2026-10-12"}),0,"Finished batch stays idempotent");
const fakeRequest=(status:number,body:unknown)=>(async()=>new Response(JSON.stringify(body),{status})) as typeof fetch;
await new CoachingDiscordRefreshService(database,"fixture-token",fakeRequest(403,{message:"Missing access"})).runAvailable(25,"2026-10-13T12:00:00.000Z");
check.equal(coachingEntitlement(database,relationship)?.present,true,"Provider failures do not remove roles");
await new CoachingDiscordRefreshService(database,"fixture-token",fakeRequest(404,{code:10007})).runAvailable(25,"2026-10-13T12:10:00.000Z");
check.equal(coachingEntitlement(database,relationship)?.present,false,"Confirmed departed member pauses coaching");
await new CoachingDiscordRefreshService(database,"fixture-token",fakeRequest(200,{roles:["200001"]})).runAvailable(25,"2026-10-13T12:20:00.000Z");
check.equal(coachingEntitlement(database,relationship)?.present,true,"Verified role restore resumes access");
const maintenance=await runCoachingMaintenance(database,{atUtc:"2026-10-13T12:30:00.000Z",limit:1});
check.equal(maintenance.checked,1,"Maintenance processes the eligible agreement");
check.equal(maintenance.created,0,"Maintenance cannot duplicate already generated work");
check.equal(maintenance.roleRefreshConfigured,false,"No token means no fabricated provider verification");
check.equal((await runCoachingMaintenance(database,{atUtc:"2026-10-13T12:31:00.000Z",limit:1})).checked,0,"Hourly watermark prevents repeated agreement work");
const scheduledPlan=platform.readSnapshot("first-room",actor).plans.find(item=>item.planId===plan)!;
platform.createPlan({...edit,expectedRevision:scheduledPlan.revision,items:[{...included,frequency:"weekly",quantity:3}]});
const scheduledAgreement=service.propose({...base,atUtc:"2026-10-14T12:00:00.000Z",startDate:"2026-10-14",dueTimeUtc:"17:00"});
service.accept({...base,atUtc:"2026-10-14T12:00:00.000Z",actor:student,agreementId:scheduledAgreement});
check.equal((await runCoachingMaintenance(database,{atUtc:"2026-10-14T12:01:00.000Z",limit:1})).created,5,"Maintenance creates upcoming weekly work without manual scheduling");
check.equal((await runCoachingMaintenance(database,{atUtc:"2026-10-14T14:01:00.000Z",limit:1})).created,0,"Next eligible maintenance pass is idempotent");
let releasePass!:()=>void;
let passes=0;
const deferred=new Promise<void>(resolve=>{releasePass=resolve;});
const guarded=nonOverlappingCoachingMaintenance(async()=>{passes++;await deferred;return passes;});
const activePass=guarded();
check.equal(await guarded(),null,"Concurrent maintenance tick is skipped");
releasePass();check.equal(await activePass,1);check.equal(await guarded(),2,"Later pass resumes after completion");
let failures=0;
const retryable=nonOverlappingCoachingMaintenance(async()=>{if(failures++===0)throw new Error("Fixture failure");return true;});
await check.rejects(retryable());check.equal(await retryable(),true,"Failure releases overlap guard");
check.equal((database.pragma("foreign_key_check") as unknown[]).length,0);
console.log(JSON.stringify({result:"passed",generated,checks:["unsigned","student acceptance","weekly generation","idempotence","month end","unscheduled","plan edits","revision conflicts","frozen terms","question renewal","follow-up expiry","draft privacy","session privacy","lesson edit/reuse","role pause/restore","archive preservation","foreign keys"]}));
}finally{database.close();}
}
void main().catch(error=>{console.error(error);process.exitCode=1;});
