import "server-only";

import type Database from "better-sqlite3";
import type { WorkspaceAccessScope } from "../../platform/contracts/workspace-access-scope";
import { assertCanonicalUtcTimestamp, createCanonicalUuidV4, platformFailure } from "../../platform/server/database/platform-migration-contract";
import type { MarketHalt } from "./market-halt-feed";

function assertActive(database: Database.Database, scope: WorkspaceAccessScope): void { const found = database.prepare<[string, string], { found: number }>(`SELECT 1 AS found FROM platform_workspace_memberships m JOIN platform_users u ON u.user_id=m.user_id JOIN platform_workspaces w ON w.workspace_id=m.workspace_id WHERE m.user_id=? AND m.workspace_id=? AND m.status='active' AND u.status='active' AND w.status='active'`).get(scope.userId, scope.workspaceId); if (!found) platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED"); }
function normalizeTicker(value: string): string { const ticker = value.trim().toUpperCase(); if (!/^[A-Z0-9.-]{1,24}$/u.test(ticker)) platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED"); return ticker; }

export class MarketHaltAlertRepository {
  constructor(private readonly database: Database.Database) {}
  read(scope: WorkspaceAccessScope): Readonly<{ enabled: boolean; mutedTickers: readonly string[] }> { assertActive(this.database, scope); const enabled = this.database.prepare<[string], { enabled: number }>(`SELECT enabled FROM news_market_halt_preferences WHERE user_id=?`).get(scope.userId)?.enabled === 1; const mutedTickers = this.database.prepare<[string], { ticker: string }>(`SELECT ticker FROM news_market_halt_muted_tickers WHERE user_id=? ORDER BY ticker`).all(scope.userId).map((row) => row.ticker); return Object.freeze({ enabled, mutedTickers: Object.freeze(mutedTickers) }); }
  setEnabled(input: Readonly<{ enabled: boolean; scope: WorkspaceAccessScope; updatedAtUtc: string }>): boolean { assertActive(this.database, input.scope); assertCanonicalUtcTimestamp(input.updatedAtUtc, "marketHaltPreferenceUpdatedAt"); this.database.prepare(`INSERT INTO news_market_halt_preferences (user_id,enabled,updated_at_utc) VALUES (?,?,?) ON CONFLICT(user_id) DO UPDATE SET enabled=excluded.enabled,updated_at_utc=excluded.updated_at_utc`).run(input.scope.userId, input.enabled ? 1 : 0, input.updatedAtUtc); return input.enabled; }
  mute(input: Readonly<{ scope: WorkspaceAccessScope; ticker: string; updatedAtUtc: string }>): readonly string[] { assertActive(this.database, input.scope); assertCanonicalUtcTimestamp(input.updatedAtUtc, "marketHaltMuteUpdatedAt"); this.database.prepare(`INSERT OR IGNORE INTO news_market_halt_muted_tickers (user_id,ticker,muted_at_utc) VALUES (?,?,?)`).run(input.scope.userId, normalizeTicker(input.ticker), input.updatedAtUtc); return this.read(input.scope).mutedTickers; }
  unmute(input: Readonly<{ scope: WorkspaceAccessScope; ticker: string }>): readonly string[] { assertActive(this.database, input.scope); this.database.prepare(`DELETE FROM news_market_halt_muted_tickers WHERE user_id=? AND ticker=?`).run(input.scope.userId, normalizeTicker(input.ticker)); return this.read(input.scope).mutedTickers; }
  upsert(input: Readonly<{ halt: MarketHalt; observedAtUtc: string; sourceUrl: string }>): Readonly<{ haltId: string; inserted: boolean }> { assertCanonicalUtcTimestamp(input.observedAtUtc, "marketHaltObservedAt"); const existing = this.database.prepare<[string,string,string],{halt_id:string}>(`SELECT halt_id FROM news_market_halt_events WHERE halt_date_et=? AND halt_time_et=? AND ticker=?`).get(input.halt.haltDateEt,input.halt.haltTimeEt,input.halt.ticker); if (existing) { this.database.prepare(`UPDATE news_market_halt_events SET reason_code=?,reason_description=?,resumption_quote_time_et=?,resumption_trade_time_et=?,updated_at_utc=? WHERE halt_id=?`).run(input.halt.reasonCode,input.halt.reasonDescription,input.halt.resumptionQuoteTimeEt,input.halt.resumptionTradeTimeEt,input.observedAtUtc,existing.halt_id); return Object.freeze({haltId:existing.halt_id,inserted:false}); } const haltId=createCanonicalUuidV4(); this.database.prepare(`INSERT INTO news_market_halt_events (halt_id,source,halt_date_et,halt_time_et,ticker,issue_name,market,reason_code,reason_description,resumption_quote_time_et,resumption_trade_time_et,source_url,first_seen_at_utc,updated_at_utc) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(haltId,input.halt.source,input.halt.haltDateEt,input.halt.haltTimeEt,input.halt.ticker,input.halt.issueName,input.halt.market,input.halt.reasonCode,input.halt.reasonDescription,input.halt.resumptionQuoteTimeEt,input.halt.resumptionTradeTimeEt,input.sourceUrl,input.observedAtUtc,input.observedAtUtc); return Object.freeze({haltId,inserted:true}); }
  enqueue(input: Readonly<{ halt: MarketHalt; haltId: string; occurredAtUtc: string }>): number { const title=`${input.halt.ticker} halted — ${input.halt.haltTimeEt} ET`; const exchange=input.halt.source === "nyse" ? "NYSE" : "Nasdaq"; const timing=input.halt.resumptionQuoteTimeEt||input.halt.resumptionTradeTimeEt ? `${exchange} expects quotes at ${input.halt.resumptionQuoteTimeEt ?? "an unposted time"} ET; trading at ${input.halt.resumptionTradeTimeEt ?? "an unposted time"} ET.` : "The exchange has not posted quote or trading resumption times yet."; const body=`${input.halt.reasonDescription} (${input.halt.reasonCode}). ${timing}`; const subscriptions=this.database.prepare<[string],{subscription_id:string}>(`SELECT s.subscription_id FROM platform_web_push_subscriptions s JOIN news_market_halt_preferences p ON p.user_id=s.user_id AND p.enabled=1 WHERE s.state='active' AND NOT EXISTS (SELECT 1 FROM news_market_halt_muted_tickers m WHERE m.user_id=s.user_id AND m.ticker=?)`).all(input.halt.ticker); const insert=this.database.prepare(`INSERT OR IGNORE INTO news_market_halt_push_deliveries (delivery_id,halt_id,subscription_id,notification_title,notification_body,state,attempt_count,available_at_utc,last_attempt_at_utc,delivered_at_utc,failure_code,created_at_utc,updated_at_utc) VALUES (?,?,?, ?,?,'pending',0,?,NULL,NULL,NULL,?,?)`); let count=0; this.database.transaction(()=>subscriptions.forEach((subscription)=>{count+=insert.run(createCanonicalUuidV4(),input.haltId,subscription.subscription_id,title,body,input.occurredAtUtc,input.occurredAtUtc,input.occurredAtUtc).changes;})).immediate(); return count; }
}
