import type Database from "better-sqlite3";

/* eslint-disable @typescript-eslint/no-explicit-any -- SQLite projection rows are mapped immediately into strict exported contracts. */

import type {
  TraderLinkCommunityAlert,
  TraderLinkCommunityAlertTemplate,
  TraderLinkCommunityAudience,
  TraderLinkCommunityChannel,
  TraderLinkCommunityCoach,
  TraderLinkCommunityCoachingPlan,
  TraderLinkCommunityCoachingMessage,
  TraderLinkCommunityCoachingRecord,
  TraderLinkCommunityCoachingTask,
  TraderLinkCommunityDashboardSnapshot,
  TraderLinkCommunityJournalGrant,
  TraderLinkCommunityMemberSummary,
  TraderLinkCommunityRelationship,
  TraderLinkCommunityTradeReview,
  TraderLinkCommunityWatchlistPlacement,
} from "../contracts/traderlink-community-platform-contracts";
import type { TraderLinkCommunityCapability } from "../contracts/traderlink-community-contracts";
import {
  assertCanonicalUtcTimestamp,
  assertCanonicalUuidV4,
  createCanonicalUuidV4,
  platformFailure,
} from "../../platform/server/database/platform-migration-contract";
import { TraderLinkCommunityRepository } from "./traderlink-community-repository";

const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/u;
const SYMBOL = /^[A-Z0-9][A-Z0-9.-]{0,14}$/u;
const SNOWFLAKE = /^[0-9]{1,32}$/u;

function text(value: string, maximum: number, field: string, required = true): string {
  const normalized = value.normalize("NFKC").trim();
  if ((required && !normalized) || normalized.length > maximum || /[\u0000-\u001f\u007f]/u.test(normalized)) {
    platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED", { field });
  }
  return normalized;
}

function slug(value: string, field: string): string {
  const normalized = text(value, 100, field).toLowerCase().replace(/[^a-z0-9]+/gu, "-").replace(/^-|-$/gu, "");
  if (!SLUG.test(normalized)) platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED", { field });
  return normalized;
}

function parseJsonStrings(value: string): readonly string[] {
  try {
    const parsed: unknown = JSON.parse(value);
    return Array.isArray(parsed) && parsed.every((item) => typeof item === "string") ? Object.freeze(parsed) : Object.freeze([]);
  } catch { return Object.freeze([]); }
}

type BaseViewer = Readonly<{ userId: string; displayName: string; discordRoleIds: readonly string[] }>;

export class TraderLinkCommunityPlatformRepository {
  private readonly permissions: TraderLinkCommunityRepository;
  constructor(private readonly database: Database.Database) {
    this.permissions = new TraderLinkCommunityRepository(database);
  }

  private write<T>(operation: () => T): T {
    return this.database.transaction(operation).immediate();
  }

  private requireCapability(communityId: string, viewer: BaseViewer, capability: TraderLinkCommunityCapability) {
    return this.permissions.requireCapability(communityId, viewer.userId, capability);
  }

  ensureDefaultAudience(input: Readonly<{ communityId: string; actorUserId: string; atUtc: string }>): string {
    assertCanonicalUuidV4(input.communityId, "communityId"); assertCanonicalUuidV4(input.actorUserId, "actorUserId"); assertCanonicalUtcTimestamp(input.atUtc, "atUtc");
    const existing = this.database.prepare(`SELECT audience_id FROM traderlink_community_audiences WHERE community_id=? AND mode='everyone' AND status='active' ORDER BY created_at_utc LIMIT 1`).get(input.communityId) as {audience_id:string}|undefined;
    if (existing) return existing.audience_id;
    const id = createCanonicalUuidV4();
    this.database.prepare(`INSERT INTO traderlink_community_audiences(audience_id,community_id,name,mode,status,created_by_user_id,created_at_utc,updated_at_utc) VALUES(?,?,'Everyone','everyone','active',?,?,?)`).run(id,input.communityId,input.actorUserId,input.atUtc,input.atUtc);
    return id;
  }

  createAudience(input: Readonly<{ communityId: string; actor: BaseViewer; name: string; discordRoleIds: readonly string[]; atUtc: string }>): string {
    this.requireCapability(input.communityId,input.actor,"community.roles.manage"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    if (!Array.isArray(input.discordRoleIds) || input.discordRoleIds.length<1 || input.discordRoleIds.some((id)=>!SNOWFLAKE.test(id))) platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"discordRoleIds"});
    return this.write(()=>{ const id=createCanonicalUuidV4(); this.database.prepare(`INSERT INTO traderlink_community_audiences(audience_id,community_id,name,mode,status,created_by_user_id,created_at_utc,updated_at_utc) VALUES(?,?,?,'discord_roles','active',?,?,?)`).run(id,input.communityId,text(input.name,80,"name"),input.actor.userId,input.atUtc,input.atUtc); const statement=this.database.prepare(`INSERT INTO traderlink_community_audience_discord_roles(audience_id,community_id,discord_role_id) VALUES(?,?,?)`); for(const roleId of [...new Set(input.discordRoleIds)]) statement.run(id,input.communityId,roleId); return id; });
  }

  createAlert(input: Readonly<{ communityId:string; actor:BaseViewer; title:string; symbol?:string; body:string; audienceId:string; publish:boolean; publishingMode?:"tracked_page"|"discord_post"; atUtc:string }>): string {
    this.requireCapability(input.communityId,input.actor,"community.alerts.create"); assertCanonicalUuidV4(input.audienceId,"audienceId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    if(input.publishingMode&&!['tracked_page','discord_post'].includes(input.publishingMode))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"publishingMode"});
    const normalizedSymbol=input.symbol?.trim().toUpperCase()||null; if(normalizedSymbol&&!SYMBOL.test(normalizedSymbol)) platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"symbol"});
    return this.write(()=>{ const id=createCanonicalUuidV4(); const base=slug(input.title,"title"); let candidate=base; let suffix=2; while(this.database.prepare(`SELECT 1 FROM traderlink_community_alerts WHERE community_id=? AND slug=?`).get(input.communityId,candidate)) candidate=`${base}-${suffix++}`; this.database.prepare(`INSERT INTO traderlink_community_alerts(alert_id,community_id,slug,author_user_id,title,symbol,body,status,audience_id,published_at_utc,created_at_utc,updated_at_utc,publishing_mode) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,input.communityId,candidate,input.actor.userId,text(input.title,140,"title"),normalizedSymbol,text(input.body,8000,"body"),input.publish?"published":"draft",input.audienceId,input.publish?input.atUtc:null,input.atUtc,input.atUtc,input.publishingMode??"tracked_page"); if(input.publish)this.queueDestinations(input.communityId,"alert",id,"alerts",input.atUtc); return id; });
  }

  updateAlert(input:Readonly<{communityId:string;actor:BaseViewer;alertId:string;title:string;symbol?:string;body:string;audienceId?:string;publishingMode?:"tracked_page"|"discord_post";status:"published"|"archived";atUtc:string}>):void{
    this.requireCapability(input.communityId,input.actor,"community.alerts.create");
    assertCanonicalUuidV4(input.alertId,"alertId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    const current=this.database.prepare(`SELECT author_user_id FROM traderlink_community_alerts WHERE community_id=? AND alert_id=?`).get(input.communityId,input.alertId) as {author_user_id:string}|undefined;
    const access=this.permissions.resolveAccess(input.communityId,input.actor.userId);
    if(!current||(current.author_user_id!==input.actor.userId&&!access.capabilities.includes("community.alerts.manage_all")))platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"update_alert"});
    const symbol=input.symbol?.trim().toUpperCase()||null;if(symbol&&!SYMBOL.test(symbol))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"symbol"});
    const mode=input.publishingMode;if(mode&&!['tracked_page','discord_post'].includes(mode))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"publishingMode"});if(input.audienceId)assertCanonicalUuidV4(input.audienceId,"audienceId");
    this.database.prepare(`UPDATE traderlink_community_alerts SET title=?,symbol=?,body=?,audience_id=coalesce(?,audience_id),publishing_mode=coalesce(?,publishing_mode),status=?,published_at_utc=CASE WHEN ?='published' THEN coalesce(published_at_utc,?) ELSE published_at_utc END,updated_at_utc=? WHERE community_id=? AND alert_id=?`).run(text(input.title,140,"title"),symbol,text(input.body,8000,"body"),input.audienceId??null,mode??null,input.status,input.status,input.atUtc,input.atUtc,input.communityId,input.alertId);
  }

  shareWatchlist(input: Readonly<{ communityId:string; actor:BaseViewer; watchlistId:string; audienceId:string; atUtc:string }>): string {
    this.requireCapability(input.communityId,input.actor,"community.watchlists.share_own"); assertCanonicalUuidV4(input.watchlistId,"watchlistId"); assertCanonicalUuidV4(input.audienceId,"audienceId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    const owner=this.database.prepare(`SELECT owner_user_id,status FROM community_watchlists WHERE watchlist_id=?`).get(input.watchlistId) as {owner_user_id:string;status:string}|undefined;
    const access=this.permissions.resolveAccess(input.communityId,input.actor.userId);
    if(!owner||owner.status!=="published"||(owner.owner_user_id!==input.actor.userId&&!access.capabilities.includes("community.watchlists.manage_all"))) platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"share_community_watchlist"});
    const audience=this.database.prepare(`SELECT mode,status FROM traderlink_community_audiences WHERE audience_id=? AND community_id=?`).get(input.audienceId,input.communityId) as {mode:"everyone"|"discord_roles";status:"active"|"archived"}|undefined;
    if(!audience||audience.status!=="active"||(owner.owner_user_id===input.actor.userId&&audience.mode!=="everyone")) platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"share_community_watchlist_audience"});
    const id=createCanonicalUuidV4(); this.write(()=>{this.database.prepare(`INSERT INTO traderlink_community_watchlist_placements(placement_id,community_id,watchlist_id,author_user_id,audience_id,status,shared_at_utc) VALUES(?,?,?,?,?,'published',?) ON CONFLICT(community_id,watchlist_id) DO UPDATE SET audience_id=excluded.audience_id,status='published',shared_at_utc=excluded.shared_at_utc,removed_at_utc=NULL`).run(id,input.communityId,input.watchlistId,owner.owner_user_id,input.audienceId,input.atUtc);this.queueDestinations(input.communityId,"watchlist",input.watchlistId,"watchlists",input.atUtc);}); return id;
  }

  createServerWatchlist(input: Readonly<{
    communityId:string;
    actor:BaseViewer;
    title:string;
    description:string;
    symbols:readonly string[];
    publish:boolean;
    publishingMode?:"tracked_page"|"discord_post";
    atUtc:string;
  }>): string {
    this.requireCapability(input.communityId,input.actor,"community.watchlists.publish_staff");
    assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    if(input.publishingMode&&!['tracked_page','discord_post'].includes(input.publishingMode))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"publishingMode"});
    const symbols=[...new Set(input.symbols.map(value=>value.normalize("NFKC").trim().toUpperCase()).filter(Boolean))];
    if(symbols.length<1||symbols.length>100||symbols.some(value=>!SYMBOL.test(value))) platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"symbols"});
    const id=createCanonicalUuidV4();
    this.write(()=>{
      this.database.prepare(`INSERT INTO traderlink_community_server_watchlists(
  watchlist_id,community_id,author_user_id,title,description,status,network_visibility,
  published_at_utc,created_at_utc,updated_at_utc,publishing_mode
) VALUES(?,?,?,?,?,?,'private',?,?,?,?)`).run(
        id,input.communityId,input.actor.userId,text(input.title,120,"title"),
        text(input.description,1200,"description",false),input.publish?"published":"draft",
        input.publish?input.atUtc:null,input.atUtc,input.atUtc,input.publishingMode??"tracked_page",
      );
      const insert=this.database.prepare(`INSERT INTO traderlink_community_server_watchlist_symbols(
  watchlist_id,community_id,symbol,ordinal,note
) VALUES(?,?,?,?, '')`);
      symbols.forEach((symbol,index)=>insert.run(id,input.communityId,symbol,index));
      if(input.publish)this.queueDestinations(input.communityId,"watchlist",id,"watchlists",input.atUtc);
    });
    return id;
  }

  updateServerWatchlist(input:Readonly<{communityId:string;actor:BaseViewer;watchlistId:string;title:string;description:string;symbols:readonly string[];publishingMode:"tracked_page"|"discord_post";status:"published"|"archived";atUtc:string}>):void {
    this.requireCapability(input.communityId,input.actor,"community.watchlists.publish_staff");assertCanonicalUuidV4(input.watchlistId,"watchlistId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    const current=this.database.prepare(`SELECT author_user_id FROM traderlink_community_server_watchlists WHERE community_id=? AND watchlist_id=?`).get(input.communityId,input.watchlistId) as {author_user_id:string}|undefined;const access=this.permissions.resolveAccess(input.communityId,input.actor.userId);if(!current||(current.author_user_id!==input.actor.userId&&!access.capabilities.includes("community.watchlists.manage_all")))platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"update_server_watchlist"});
    const symbols=[...new Set(input.symbols.map(value=>value.normalize("NFKC").trim().toUpperCase()).filter(Boolean))];if(symbols.length<1||symbols.length>100||symbols.some(value=>!SYMBOL.test(value)))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"symbols"});if(!['tracked_page','discord_post'].includes(input.publishingMode))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"publishingMode"});
    this.write(()=>{this.database.prepare(`UPDATE traderlink_community_server_watchlists SET title=?,description=?,publishing_mode=?,status=?,published_at_utc=CASE WHEN ?='published' THEN coalesce(published_at_utc,?) ELSE published_at_utc END,updated_at_utc=? WHERE community_id=? AND watchlist_id=?`).run(text(input.title,120,"title"),text(input.description,1200,"description",false),input.publishingMode,input.status,input.status,input.atUtc,input.atUtc,input.communityId,input.watchlistId);this.database.prepare(`DELETE FROM traderlink_community_server_watchlist_symbols WHERE watchlist_id=?`).run(input.watchlistId);const insert=this.database.prepare(`INSERT INTO traderlink_community_server_watchlist_symbols(watchlist_id,community_id,symbol,ordinal,note) VALUES(?,?,?,?,'')`);symbols.forEach((symbol,index)=>insert.run(input.watchlistId,input.communityId,symbol,index));});
  }

  private queueDestinations(communityId:string,objectType:"alert"|"watchlist"|"coach"|"plan",objectId:string,contentType:"alerts"|"watchlists"|"coaching",atUtc:string):void {
    const destinations=this.database.prepare(`SELECT destination_id FROM traderlink_community_discord_destinations WHERE community_id=? AND content_type=? AND status='active'`).all(communityId,contentType) as {destination_id:string}[];
    const insert=this.database.prepare(`INSERT INTO traderlink_community_content_deliveries(delivery_id,community_id,object_type,object_id,destination_id,status,attempt_count,last_error,requested_at_utc,delivered_at_utc,updated_at_utc) VALUES(?,?,?,?,?,'pending',0,NULL,?,NULL,?) ON CONFLICT(community_id,object_type,object_id,destination_id) DO NOTHING`);
    for(const destination of destinations)insert.run(createCanonicalUuidV4(),communityId,objectType,objectId,destination.destination_id,atUtc,atUtc);
  }

  saveDiscordDestination(input:Readonly<{communityId:string;actor:BaseViewer;name:string;discordChannelId:string;contentType:"alerts"|"watchlists"|"coaching"|"general";atUtc:string}>):string {
    this.requireCapability(input.communityId,input.actor,"community.discord.manage"); if(!SNOWFLAKE.test(input.discordChannelId))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"discordChannelId"});assertCanonicalUtcTimestamp(input.atUtc,"atUtc");const existing=this.database.prepare(`SELECT destination_id FROM traderlink_community_discord_destinations WHERE community_id=? AND discord_channel_id=? AND content_type=?`).get(input.communityId,input.discordChannelId,input.contentType) as {destination_id:string}|undefined;const id=existing?.destination_id??createCanonicalUuidV4();this.database.prepare(`INSERT INTO traderlink_community_discord_destinations(destination_id,community_id,name,discord_channel_id,content_type,status,updated_by_user_id,created_at_utc,updated_at_utc) VALUES(?,?,?,?,?,'active',?,?,?) ON CONFLICT(community_id,discord_channel_id,content_type) DO UPDATE SET name=excluded.name,status='active',updated_by_user_id=excluded.updated_by_user_id,updated_at_utc=excluded.updated_at_utc`).run(id,input.communityId,text(input.name,80,"name"),input.discordChannelId,input.contentType,input.actor.userId,input.atUtc,input.atUtc);return id;
  }

  updateSettings(input:Readonly<{communityId:string;actor:BaseViewer;displayName:string;description:string;retentionDays:number;visibilityStatus:"not_configured"|"active"|"declined";visibilityCopy:string;atUtc:string}>):void {
    this.requireCapability(input.communityId,input.actor,"community.manage");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");if(!Number.isInteger(input.retentionDays)||input.retentionDays<7||input.retentionDays>730)platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"retentionDays"});this.write(()=>{this.database.prepare(`UPDATE traderlink_communities SET display_name=?,updated_at_utc=? WHERE community_id=?`).run(text(input.displayName,120,"displayName"),input.atUtc,input.communityId);this.database.prepare(`INSERT INTO traderlink_community_settings(community_id,description,named_activity_retention_days,visibility_status,visibility_copy,updated_at_utc) VALUES(?,?,?,?,?,?) ON CONFLICT(community_id) DO UPDATE SET description=excluded.description,named_activity_retention_days=excluded.named_activity_retention_days,visibility_status=excluded.visibility_status,visibility_copy=excluded.visibility_copy,updated_at_utc=excluded.updated_at_utc`).run(input.communityId,text(input.description,1000,"description",false),input.retentionDays,input.visibilityStatus,text(input.visibilityCopy,1000,"visibilityCopy",false),input.atUtc);});
  }

  upsertCoach(input: Readonly<{ communityId:string; actor:BaseViewer; userId:string; displayName:string; headline:string; biography:string; deliverySummary:string; capacity:number; active:boolean; atUtc:string }>): string {
    const access=this.requireCapability(input.communityId,input.actor,"community.coaching.offer"); assertCanonicalUuidV4(input.userId,"userId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    if(input.userId!==input.actor.userId&&!access.capabilities.includes("community.coaching.manage_all")) platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"manage_other_coach"});
    if(!Number.isInteger(input.capacity)||input.capacity<1||input.capacity>10000) platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"capacity"});
    const existing=this.database.prepare(`SELECT coach_profile_id FROM traderlink_community_coach_profiles WHERE community_id=? AND user_id=?`).get(input.communityId,input.userId) as {coach_profile_id:string}|undefined; const id=existing?.coach_profile_id??createCanonicalUuidV4();
    const coachSlug=slug(input.displayName,"displayName"); this.database.prepare(`INSERT INTO traderlink_community_coach_profiles(coach_profile_id,community_id,user_id,coach_slug,display_name,headline,biography,delivery_summary,capacity,status,created_at_utc,updated_at_utc) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(community_id,user_id) DO UPDATE SET display_name=excluded.display_name,headline=excluded.headline,biography=excluded.biography,delivery_summary=excluded.delivery_summary,capacity=excluded.capacity,status=excluded.status,updated_at_utc=excluded.updated_at_utc`).run(id,input.communityId,input.userId,coachSlug,text(input.displayName,100,"displayName"),text(input.headline,180,"headline",false),text(input.biography,4000,"biography",false),text(input.deliverySummary,1000,"deliverySummary",false),input.capacity,input.active?"active":"draft",input.atUtc,input.atUtc); return id;
  }

  createPlan(input: Readonly<{communityId:string;actor:BaseViewer;coachProfileId:string;name:string;description:string;cadence:"weekly"|"monthly"|"trade_reviews"|"custom";tradeReviewLimit?:number;priceLabel:string;paymentInstructions:string;audienceId:string;publish:boolean;atUtc:string}>): string {
    this.requireCapability(input.communityId,input.actor,"community.coaching.offer"); assertCanonicalUuidV4(input.coachProfileId,"coachProfileId"); assertCanonicalUuidV4(input.audienceId,"audienceId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    const coach=this.database.prepare(`SELECT user_id FROM traderlink_community_coach_profiles WHERE coach_profile_id=? AND community_id=?`).get(input.coachProfileId,input.communityId) as {user_id:string}|undefined; const access=this.permissions.resolveAccess(input.communityId,input.actor.userId); if(!coach||(coach.user_id!==input.actor.userId&&!access.capabilities.includes("community.coaching.manage_all"))) platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"create_coaching_plan"});
    const id=createCanonicalUuidV4(); this.write(()=>{this.database.prepare(`INSERT INTO traderlink_community_coaching_plans(plan_id,coach_profile_id,community_id,name,description,cadence,trade_review_limit,price_label,payment_instructions,audience_id,status,created_at_utc,updated_at_utc) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,input.coachProfileId,input.communityId,text(input.name,100,"name"),text(input.description,4000,"description",false),input.cadence,input.tradeReviewLimit??null,text(input.priceLabel,80,"priceLabel",false),text(input.paymentInstructions,1000,"paymentInstructions",false),input.audienceId,input.publish?"active":"draft",input.atUtc,input.atUtc);if(input.publish)this.queueDestinations(input.communityId,"plan",id,"coaching",input.atUtc);}); return id;
  }

  updatePlanStatus(input:Readonly<{communityId:string;actor:BaseViewer;planId:string;status:"active"|"paused"|"archived";atUtc:string}>):void {
    this.requireCapability(input.communityId,input.actor,"community.coaching.offer");assertCanonicalUuidV4(input.planId,"planId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    const plan=this.database.prepare(`SELECT coach.user_id FROM traderlink_community_coaching_plans plan JOIN traderlink_community_coach_profiles coach ON coach.coach_profile_id=plan.coach_profile_id WHERE plan.community_id=? AND plan.plan_id=?`).get(input.communityId,input.planId) as {user_id:string}|undefined;const access=this.permissions.resolveAccess(input.communityId,input.actor.userId);if(!plan||(plan.user_id!==input.actor.userId&&!access.capabilities.includes("community.coaching.manage_all")))platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"update_coaching_plan"});
    this.database.prepare(`UPDATE traderlink_community_coaching_plans SET status=?,updated_at_utc=? WHERE community_id=? AND plan_id=?`).run(input.status,input.atUtc,input.communityId,input.planId);
  }

  requestCoaching(input:Readonly<{communityId:string;actor:BaseViewer;planId:string;atUtc:string}>):string { this.requireCapability(input.communityId,input.actor,"community.coaching.view"); assertCanonicalUuidV4(input.planId,"planId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc"); const plan=this.database.prepare(`SELECT p.coach_profile_id,c.user_id,c.capacity,(SELECT count(*) FROM traderlink_community_coaching_relationships r WHERE r.coach_profile_id=c.coach_profile_id AND r.status='active') active_count FROM traderlink_community_coaching_plans p JOIN traderlink_community_coach_profiles c ON c.coach_profile_id=p.coach_profile_id WHERE p.plan_id=? AND p.community_id=? AND p.status='active' AND c.status='active'`).get(input.planId,input.communityId) as {coach_profile_id:string;user_id:string;capacity:number;active_count:number}|undefined; if(!plan||plan.user_id===input.actor.userId||plan.active_count>=plan.capacity) platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"request_coaching"}); const existing=this.database.prepare(`SELECT relationship_id,status FROM traderlink_community_coaching_relationships WHERE community_id=? AND coach_user_id=? AND student_user_id=? AND plan_id=?`).get(input.communityId,plan.user_id,input.actor.userId,input.planId) as {relationship_id:string;status:string}|undefined; if(existing?.status==="pending"||existing?.status==="active")return existing.relationship_id; const id=existing?.relationship_id??createCanonicalUuidV4(); if(existing)this.database.prepare(`UPDATE traderlink_community_coaching_relationships SET status='pending',requested_at_utc=?,started_at_utc=NULL,ended_at_utc=NULL WHERE relationship_id=?`).run(input.atUtc,id); else this.database.prepare(`INSERT INTO traderlink_community_coaching_relationships(relationship_id,community_id,coach_profile_id,coach_user_id,student_user_id,plan_id,status,requested_at_utc,started_at_utc,ended_at_utc) VALUES(?,?,?,?,?,?,'pending',?,NULL,NULL)`).run(id,input.communityId,plan.coach_profile_id,plan.user_id,input.actor.userId,input.planId,input.atUtc); return id; }

  setRelationshipStatus(input:Readonly<{communityId:string;actor:BaseViewer;relationshipId:string;status:"active"|"declined"|"ended";atUtc:string}>):void { this.requireCapability(input.communityId,input.actor,"community.coaching.students"); assertCanonicalUuidV4(input.relationshipId,"relationshipId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc"); const row=this.database.prepare(`SELECT r.coach_user_id,r.coach_profile_id,r.status,c.capacity,(SELECT count(*) FROM traderlink_community_coaching_relationships active_relationship WHERE active_relationship.coach_profile_id=r.coach_profile_id AND active_relationship.status='active' AND active_relationship.relationship_id<>r.relationship_id) active_count FROM traderlink_community_coaching_relationships r JOIN traderlink_community_coach_profiles c ON c.coach_profile_id=r.coach_profile_id WHERE r.relationship_id=? AND r.community_id=?`).get(input.relationshipId,input.communityId) as {coach_user_id:string;coach_profile_id:string;status:string;capacity:number;active_count:number}|undefined; const access=this.permissions.resolveAccess(input.communityId,input.actor.userId); if(!row||(row.coach_user_id!==input.actor.userId&&!access.capabilities.includes("community.coaching.manage_all"))) platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"manage_coaching_relationship"}); if(input.status==="active"&&row.status!=="active"&&row.active_count>=row.capacity)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"coach_capacity_reached"}); this.database.prepare(`UPDATE traderlink_community_coaching_relationships SET status=?,started_at_utc=CASE WHEN ?='active' THEN coalesce(started_at_utc,?) ELSE started_at_utc END,ended_at_utc=CASE WHEN ? IN ('declined','ended') THEN ? ELSE NULL END WHERE relationship_id=?`).run(input.status,input.status,input.atUtc,input.status,input.atUtc,input.relationshipId); }

  grantJournal(input:Readonly<{communityId:string;actor:BaseViewer;relationshipId:string;journalAccountId:string;dataScope:"summary"|"trades"|"journal"|"analytics"|"complete";atUtc:string}>):string { assertCanonicalUuidV4(input.relationshipId,"relationshipId"); assertCanonicalUuidV4(input.journalAccountId,"journalAccountId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc"); const row=this.database.prepare(`SELECT coach_user_id,student_user_id,status FROM traderlink_community_coaching_relationships WHERE relationship_id=? AND community_id=?`).get(input.relationshipId,input.communityId) as {coach_user_id:string;student_user_id:string;status:string}|undefined; if(!row||row.student_user_id!==input.actor.userId||row.status!=="active") platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"grant_coach_journal_access"}); const ownedAccount=this.database.prepare(`SELECT 1 FROM journal_accounts account JOIN platform_workspace_memberships membership ON membership.workspace_id=account.workspace_id WHERE account.account_id=? AND account.status='active' AND membership.user_id=? AND membership.status='active'`).get(input.journalAccountId,input.actor.userId); if(!ownedAccount)platformFailure("TRADERLINK_ACCOUNT_ACCESS_DENIED",{operation:"grant_coach_journal_access"}); const id=createCanonicalUuidV4(); this.database.prepare(`INSERT INTO traderlink_community_journal_grants(grant_id,relationship_id,community_id,coach_user_id,student_user_id,journal_account_id,data_scope,status,granted_at_utc,revoked_at_utc) VALUES(?,?,?,?,?,?,?,'active',?,NULL) ON CONFLICT(relationship_id,journal_account_id,data_scope) DO UPDATE SET status='active',granted_at_utc=excluded.granted_at_utc,revoked_at_utc=NULL`).run(id,input.relationshipId,input.communityId,row.coach_user_id,row.student_user_id,input.journalAccountId,input.dataScope,input.atUtc); return id; }

  revokeJournal(input:Readonly<{actorUserId:string;grantId:string;atUtc:string}>):void { assertCanonicalUuidV4(input.grantId,"grantId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc"); const result=this.database.prepare(`UPDATE traderlink_community_journal_grants SET status='revoked',revoked_at_utc=? WHERE grant_id=? AND student_user_id=? AND status='active'`).run(input.atUtc,input.grantId,input.actorUserId); if(result.changes!==1) platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"revoke_coach_journal_access"}); }

  createAlertTemplate(input:Readonly<{communityId:string;actor:BaseViewer;title:string;scope:"personal"|"community";fields:readonly Readonly<{label:string;type:"text"|"number"|"price"|"ticker"|"date"|"time"|"choice"|"notes";required:boolean;placeholder:string}>[];atUtc:string}>):string {
    const access=this.requireCapability(input.communityId,input.actor,"community.alerts.create");
    assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    if(input.scope==="community"&&!access.capabilities.includes("community.alerts.manage_all"))platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"create_community_alert_template"});
    const settings=this.database.prepare(`SELECT personal_alert_templates_enabled enabled FROM traderlink_community_settings WHERE community_id=?`).get(input.communityId) as {enabled:number}|undefined;
    if(input.scope==="personal"&&settings?.enabled===0&&!access.isOwner)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"create_personal_alert_template"});
    if(!input.fields.length||input.fields.length>20)platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"templateFields"});
    return this.write(()=>{const templateId=createCanonicalUuidV4();this.database.prepare(`INSERT INTO traderlink_community_alert_templates(template_id,community_id,owner_user_id,title,scope,status,created_at_utc,updated_at_utc) VALUES(?,?,?,?,?,'active',?,?)`).run(templateId,input.communityId,input.actor.userId,text(input.title,100,"templateTitle"),input.scope,input.atUtc,input.atUtc);const insert=this.database.prepare(`INSERT INTO traderlink_community_alert_template_fields(template_id,community_id,field_key,label,field_type,required,placeholder,ordinal) VALUES(?,?,?,?,?,?,?,?)`);input.fields.forEach((field,index)=>{const key=slug(field.label,"fieldLabel").replace(/-/gu,"_");insert.run(templateId,input.communityId,key,text(field.label,80,"fieldLabel"),field.type,field.required?1:0,text(field.placeholder,120,"placeholder",false),index);});return templateId;});
  }

  archiveAlertTemplate(input:Readonly<{communityId:string;actor:BaseViewer;templateId:string;atUtc:string}>):void {
    this.requireCapability(input.communityId,input.actor,"community.alerts.create");assertCanonicalUuidV4(input.templateId,"templateId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");const template=this.database.prepare(`SELECT owner_user_id,scope FROM traderlink_community_alert_templates WHERE community_id=? AND template_id=?`).get(input.communityId,input.templateId) as {owner_user_id:string;scope:"personal"|"community"}|undefined;const access=this.permissions.resolveAccess(input.communityId,input.actor.userId);if(!template||(template.owner_user_id!==input.actor.userId&&!(template.scope==="community"&&access.capabilities.includes("community.alerts.manage_all"))))platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"archive_alert_template"});this.database.prepare(`UPDATE traderlink_community_alert_templates SET status='archived',updated_at_utc=? WHERE community_id=? AND template_id=?`).run(input.atUtc,input.communityId,input.templateId);
  }

  setMemberStatus(input:Readonly<{communityId:string;actor:BaseViewer;userId:string;status:"active"|"suspended";atUtc:string}>):void {
    this.requireCapability(input.communityId,input.actor,"community.manage");assertCanonicalUuidV4(input.userId,"userId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");if(input.userId===input.actor.userId)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"change_own_community_membership"});const changed=this.database.prepare(`UPDATE traderlink_community_memberships SET status=?,updated_at_utc=? WHERE community_id=? AND user_id=?`).run(input.status,input.atUtc,input.communityId,input.userId);if(changed.changes!==1)platformFailure("TRADERLINK_WORKSPACE_NOT_FOUND",{resource:"community_member"});
  }

  setPersonalAlertTemplatesEnabled(input:Readonly<{communityId:string;actor:BaseViewer;enabled:boolean;atUtc:string}>):void {
    this.requireCapability(input.communityId,input.actor,"community.manage");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    this.database.prepare(`INSERT INTO traderlink_community_settings(community_id,description,named_activity_retention_days,visibility_status,visibility_copy,personal_alert_templates_enabled,updated_at_utc) VALUES(?,'',90,'not_configured','',?,?) ON CONFLICT(community_id) DO UPDATE SET personal_alert_templates_enabled=excluded.personal_alert_templates_enabled,updated_at_utc=excluded.updated_at_utc`).run(input.communityId,input.enabled?1:0,input.atUtc);
  }

  sendCoachingMessage(input:Readonly<{communityId:string;actor:BaseViewer;relationshipId:string;body:string;atUtc:string}>):string {
    assertCanonicalUuidV4(input.relationshipId,"relationshipId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    const relationship=this.database.prepare(`SELECT coach_user_id,student_user_id,status,student_messaging_enabled FROM traderlink_community_coaching_relationships WHERE community_id=? AND relationship_id=?`).get(input.communityId,input.relationshipId) as {coach_user_id:string;student_user_id:string;status:string;student_messaging_enabled:number}|undefined;
    const isCoach=relationship?.coach_user_id===input.actor.userId;const isStudent=relationship?.student_user_id===input.actor.userId;
    if(!relationship||relationship.status!=="active"||(!isCoach&&!isStudent)||(isStudent&&relationship.student_messaging_enabled!==1))platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"send_coaching_message"});
    const id=createCanonicalUuidV4();this.database.prepare(`INSERT INTO traderlink_community_coaching_messages(message_id,relationship_id,community_id,author_user_id,body,created_at_utc,edited_at_utc) VALUES(?,?,?,?,?,?,NULL)`).run(id,input.relationshipId,input.communityId,input.actor.userId,text(input.body,8000,"message"),input.atUtc);return id;
  }

  requestTradeReview(input:Readonly<{communityId:string;actor:BaseViewer;relationshipId:string;title:string;studentContext:string;atUtc:string}>):string {
    assertCanonicalUuidV4(input.relationshipId,"relationshipId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    const relationship=this.database.prepare(`SELECT student_user_id,status,student_trade_reviews_enabled FROM traderlink_community_coaching_relationships WHERE community_id=? AND relationship_id=?`).get(input.communityId,input.relationshipId) as {student_user_id:string;status:string;student_trade_reviews_enabled:number}|undefined;
    if(!relationship||relationship.status!=="active"||relationship.student_user_id!==input.actor.userId||relationship.student_trade_reviews_enabled!==1)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"request_trade_review"});
    const id=createCanonicalUuidV4();this.database.prepare(`INSERT INTO traderlink_community_coaching_trade_reviews(review_id,relationship_id,community_id,requested_by_user_id,round_trip_id,title,student_context,coach_feedback,status,requested_at_utc,completed_at_utc,updated_at_utc) VALUES(?,?,?,?,NULL,?,?,?,'requested',?,NULL,?)`).run(id,input.relationshipId,input.communityId,input.actor.userId,text(input.title,140,"reviewTitle"),text(input.studentContext,4000,"studentContext",false),"",input.atUtc,input.atUtc);return id;
  }

  updateTradeReview(input:Readonly<{communityId:string;actor:BaseViewer;reviewId:string;coachFeedback:string;status:"in_review"|"completed"|"cancelled";atUtc:string}>):void {
    assertCanonicalUuidV4(input.reviewId,"reviewId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    const review=this.database.prepare(`SELECT relationship.coach_user_id FROM traderlink_community_coaching_trade_reviews review JOIN traderlink_community_coaching_relationships relationship ON relationship.relationship_id=review.relationship_id WHERE review.community_id=? AND review.review_id=?`).get(input.communityId,input.reviewId) as {coach_user_id:string}|undefined;
    if(!review||review.coach_user_id!==input.actor.userId)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"update_trade_review"});
    this.database.prepare(`UPDATE traderlink_community_coaching_trade_reviews SET coach_feedback=?,status=?,completed_at_utc=CASE WHEN ?='completed' THEN ? ELSE NULL END,updated_at_utc=? WHERE review_id=? AND community_id=?`).run(text(input.coachFeedback,8000,"coachFeedback",false),input.status,input.status,input.atUtc,input.atUtc,input.reviewId,input.communityId);
  }

  setStudentServices(input:Readonly<{communityId:string;actor:BaseViewer;relationshipId:string;messagingEnabled:boolean;tradeReviewsEnabled:boolean;atUtc:string}>):void {
    assertCanonicalUuidV4(input.relationshipId,"relationshipId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    const relationship=this.database.prepare(`SELECT coach_user_id FROM traderlink_community_coaching_relationships WHERE community_id=? AND relationship_id=?`).get(input.communityId,input.relationshipId) as {coach_user_id:string}|undefined;
    if(!relationship||relationship.coach_user_id!==input.actor.userId)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"set_student_coaching_services"});
    this.database.prepare(`UPDATE traderlink_community_coaching_relationships SET student_messaging_enabled=?,student_trade_reviews_enabled=? WHERE community_id=? AND relationship_id=?`).run(input.messagingEnabled?1:0,input.tradeReviewsEnabled?1:0,input.communityId,input.relationshipId);
  }

  createCoachingTask(input:Readonly<{communityId:string;actor:BaseViewer;relationshipId:string;title:string;dueAtUtc?:string;priority:"normal"|"high";atUtc:string}>):string {
    assertCanonicalUuidV4(input.relationshipId,"relationshipId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");if(input.dueAtUtc)assertCanonicalUtcTimestamp(input.dueAtUtc,"dueAtUtc");
    const relationship=this.database.prepare(`SELECT coach_user_id,status FROM traderlink_community_coaching_relationships WHERE community_id=? AND relationship_id=?`).get(input.communityId,input.relationshipId) as {coach_user_id:string;status:string}|undefined;
    if(!relationship||relationship.coach_user_id!==input.actor.userId||relationship.status!=="active")platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"create_coaching_task"});
    const id=createCanonicalUuidV4();this.database.prepare(`INSERT INTO traderlink_community_coaching_tasks(task_id,relationship_id,community_id,created_by_user_id,title,due_at_utc,priority,status,created_at_utc,completed_at_utc,updated_at_utc) VALUES(?,?,?,?,?,?,?,'open',?,NULL,?)`).run(id,input.relationshipId,input.communityId,input.actor.userId,text(input.title,160,"taskTitle"),input.dueAtUtc??null,input.priority,input.atUtc,input.atUtc);return id;
  }

  updateCoachingTaskStatus(input:Readonly<{communityId:string;actor:BaseViewer;taskId:string;status:"open"|"completed"|"cancelled";atUtc:string}>):void {
    assertCanonicalUuidV4(input.taskId,"taskId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");const task=this.database.prepare(`SELECT relationship.coach_user_id FROM traderlink_community_coaching_tasks task JOIN traderlink_community_coaching_relationships relationship ON relationship.relationship_id=task.relationship_id WHERE task.community_id=? AND task.task_id=?`).get(input.communityId,input.taskId) as {coach_user_id:string}|undefined;if(!task||task.coach_user_id!==input.actor.userId)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"update_coaching_task"});this.database.prepare(`UPDATE traderlink_community_coaching_tasks SET status=?,completed_at_utc=CASE WHEN ?='completed' THEN ? ELSE NULL END,updated_at_utc=? WHERE community_id=? AND task_id=?`).run(input.status,input.status,input.atUtc,input.atUtc,input.communityId,input.taskId);
  }

  createCoachingRecord(input:Readonly<{communityId:string;actor:BaseViewer;relationshipId:string;recordType:"session"|"note";visibility:"shared"|"coach_private";title:string;body:string;occurredAtUtc:string;atUtc:string}>):string {
    assertCanonicalUuidV4(input.relationshipId,"relationshipId");assertCanonicalUtcTimestamp(input.occurredAtUtc,"occurredAtUtc");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");const relationship=this.database.prepare(`SELECT coach_user_id FROM traderlink_community_coaching_relationships WHERE community_id=? AND relationship_id=?`).get(input.communityId,input.relationshipId) as {coach_user_id:string}|undefined;if(!relationship||relationship.coach_user_id!==input.actor.userId)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"create_coaching_record"});const id=createCanonicalUuidV4();this.database.prepare(`INSERT INTO traderlink_community_coaching_records(record_id,relationship_id,community_id,author_user_id,record_type,visibility,title,body,occurred_at_utc,created_at_utc) VALUES(?,?,?,?,?,?,?,?,?,?)`).run(id,input.relationshipId,input.communityId,input.actor.userId,input.recordType,input.visibility,text(input.title,160,"recordTitle"),text(input.body,8000,"recordBody",false),input.occurredAtUtc,input.atUtc);return id;
  }

  recordView(input:Readonly<{communityId:string;userId:string;path:string;objectType:string;objectId?:string;atUtc:string}>):void { assertCanonicalUuidV4(input.communityId,"communityId"); assertCanonicalUuidV4(input.userId,"userId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc"); const path=text(input.path,500,"path");this.write(()=>{this.database.prepare(`INSERT INTO traderlink_community_activity_events(event_id,community_id,user_id,event_type,object_type,object_id,path,occurred_at_utc) VALUES(?,?,?,'page.view',?,?,?,?)`).run(createCanonicalUuidV4(),input.communityId,input.userId,text(input.objectType,40,"objectType"),input.objectId??null,path,input.atUtc);this.database.prepare(`INSERT INTO traderlink_community_activity_daily_members(community_id,activity_day,path,user_id,views,first_viewed_at_utc,last_viewed_at_utc) VALUES(?,?,?,?,1,?,?) ON CONFLICT(community_id,activity_day,path,user_id) DO UPDATE SET views=views+1,last_viewed_at_utc=excluded.last_viewed_at_utc`).run(input.communityId,input.atUtc.slice(0,10),path,input.userId,input.atUtc,input.atUtc);const retention=(this.database.prepare(`SELECT named_activity_retention_days days FROM traderlink_community_settings WHERE community_id=?`).get(input.communityId) as {days:number}|undefined)?.days??90;const cutoff=new Date(new Date(input.atUtc).getTime()-retention*86400000).toISOString();this.database.prepare(`DELETE FROM traderlink_community_activity_events WHERE community_id=? AND occurred_at_utc<?`).run(input.communityId,cutoff);}); }

  readSnapshot(communitySlug:string,viewer:BaseViewer):TraderLinkCommunityDashboardSnapshot {
    const community=this.database.prepare(`SELECT community_id,discord_guild_id,slug,display_name,status,owner_user_id FROM traderlink_communities WHERE slug=?`).get(communitySlug) as {community_id:string;discord_guild_id:string;slug:string;display_name:string;status:"setup"|"active"|"paused"|"suspended";owner_user_id:string}|undefined;
    if(!community) platformFailure("TRADERLINK_WORKSPACE_NOT_FOUND",{resource:"community"}); const access=this.requireCapability(community.community_id,viewer,"community.view");
    const audienceRows=this.database.prepare(`SELECT a.audience_id,a.community_id,a.name,a.mode,a.status,coalesce(json_group_array(r.discord_role_id) FILTER(WHERE r.discord_role_id IS NOT NULL),'[]') role_ids FROM traderlink_community_audiences a LEFT JOIN traderlink_community_audience_discord_roles r ON r.audience_id=a.audience_id WHERE a.community_id=? GROUP BY a.audience_id ORDER BY a.name`).all(community.community_id) as any[];
    const audiences:TraderLinkCommunityAudience[]=audienceRows.map(r=>({audienceId:r.audience_id,communityId:r.community_id,name:r.name,mode:r.mode,discordRoleIds:parseJsonStrings(r.role_ids),status:r.status}));
    const allowed=new Set(audiences.filter(a=>a.status==="active"&&(a.mode==="everyone"||a.discordRoleIds.some(id=>viewer.discordRoleIds.includes(id)))).map(a=>a.audienceId)); if(access.isOwner) audiences.forEach(a=>allowed.add(a.audienceId));
    const canViewAlerts=access.isOwner||access.capabilities.includes("community.alerts.view")||access.capabilities.includes("community.alerts.create");
    const canViewWatchlists=access.isOwner||access.capabilities.includes("community.watchlists.view")||access.capabilities.includes("community.watchlists.publish_staff");
    const canViewCoaching=access.isOwner||access.capabilities.includes("community.coaching.view")||access.capabilities.includes("community.coaching.offer")||access.capabilities.includes("community.coaching.manage_all");
    const alerts=canViewAlerts?(this.database.prepare(`SELECT a.*,u.display_name author_name FROM traderlink_community_alerts a JOIN platform_users u ON u.user_id=a.author_user_id WHERE a.community_id=? AND a.status='published' ORDER BY a.published_at_utc DESC LIMIT 100`).all(community.community_id) as any[]).filter(r=>allowed.has(r.audience_id)).map((r):TraderLinkCommunityAlert=>({alertId:r.alert_id,communityId:r.community_id,slug:r.slug,authorUserId:r.author_user_id,authorName:r.author_name,title:r.title,symbol:r.symbol,body:r.body,status:r.status,audienceId:r.audience_id,publishedAtUtc:r.published_at_utc,createdAtUtc:r.created_at_utc,updatedAtUtc:r.updated_at_utc,publishingMode:r.publishing_mode})):[];
    const memberWatchlists=canViewWatchlists?(this.database.prepare(`SELECT p.*,w.title,u.display_name author_name FROM traderlink_community_watchlist_placements p JOIN community_watchlists w ON w.watchlist_id=p.watchlist_id JOIN platform_users u ON u.user_id=p.author_user_id WHERE p.community_id=? AND p.status='published' ORDER BY p.shared_at_utc DESC LIMIT 100`).all(community.community_id) as any[]).filter(r=>allowed.has(r.audience_id)).map((r):TraderLinkCommunityWatchlistPlacement=>({placementId:r.placement_id,communityId:r.community_id,watchlistId:r.watchlist_id,authorUserId:r.author_user_id,authorName:r.author_name,title:r.title,audienceId:r.audience_id,status:r.status,sharedAtUtc:r.shared_at_utc,sourceKind:"member"})):[];
    const serverWatchlists=canViewWatchlists?(this.database.prepare(`SELECT w.*,u.display_name author_name,coalesce(group_concat(s.symbol,','),'') symbols FROM traderlink_community_server_watchlists w JOIN platform_users u ON u.user_id=w.author_user_id LEFT JOIN traderlink_community_server_watchlist_symbols s ON s.watchlist_id=w.watchlist_id WHERE w.community_id=? AND w.status='published' GROUP BY w.watchlist_id ORDER BY w.published_at_utc DESC LIMIT 100`).all(community.community_id) as any[]).map((r):TraderLinkCommunityWatchlistPlacement=>({placementId:r.watchlist_id,communityId:r.community_id,watchlistId:r.watchlist_id,authorUserId:r.author_user_id,authorName:r.author_name,title:r.title,audienceId:"server-role-access",status:"published",sharedAtUtc:r.published_at_utc,sourceKind:"server",description:r.description,symbols:Object.freeze(String(r.symbols).split(",").filter(Boolean)),networkVisibility:r.network_visibility,publishingMode:r.publishing_mode})):[];
    const watchlists=[...serverWatchlists,...memberWatchlists].sort((left,right)=>right.sharedAtUtc.localeCompare(left.sharedAtUtc)).slice(0,100);
    const coaches=canViewCoaching?(this.database.prepare(`SELECT c.*,(SELECT count(*) FROM traderlink_community_coaching_relationships r WHERE r.coach_profile_id=c.coach_profile_id AND r.status='active') active_students FROM traderlink_community_coach_profiles c WHERE c.community_id=? AND c.status IN ('active','paused') ORDER BY c.display_name`).all(community.community_id) as any[]).map((r):TraderLinkCommunityCoach=>({coachProfileId:r.coach_profile_id,slug:r.coach_slug,communityId:r.community_id,userId:r.user_id,displayName:r.display_name,headline:r.headline,biography:r.biography,deliverySummary:r.delivery_summary,capacity:r.capacity,activeStudents:r.active_students,status:r.status})):[];
    const plans=canViewCoaching?(this.database.prepare(`SELECT plan.*,coach.user_id coach_user_id FROM traderlink_community_coaching_plans plan JOIN traderlink_community_coach_profiles coach ON coach.coach_profile_id=plan.coach_profile_id WHERE plan.community_id=? AND plan.status IN ('active','paused') ORDER BY plan.name`).all(community.community_id) as any[]).filter(r=>(r.status==="active"&&allowed.has(r.audience_id))||r.coach_user_id===viewer.userId||access.capabilities.includes("community.coaching.manage_all")).map((r):TraderLinkCommunityCoachingPlan=>({planId:r.plan_id,coachProfileId:r.coach_profile_id,communityId:r.community_id,name:r.name,description:r.description,cadence:r.cadence,tradeReviewLimit:r.trade_review_limit,priceLabel:r.price_label,paymentInstructions:r.payment_instructions,audienceId:r.audience_id,status:r.status})):[];
    const relationships=(this.database.prepare(`SELECT r.*,coach.display_name coach_display_name,student.display_name student_display_name,plan.name plan_name FROM traderlink_community_coaching_relationships r JOIN platform_users coach ON coach.user_id=r.coach_user_id JOIN platform_users student ON student.user_id=r.student_user_id JOIN traderlink_community_coaching_plans plan ON plan.plan_id=r.plan_id WHERE r.community_id=? AND (r.coach_user_id=? OR r.student_user_id=?) ORDER BY r.requested_at_utc DESC`).all(community.community_id,viewer.userId,viewer.userId) as any[]).map((r):TraderLinkCommunityRelationship=>({relationshipId:r.relationship_id,communityId:r.community_id,coachProfileId:r.coach_profile_id,coachUserId:r.coach_user_id,coachDisplayName:r.coach_display_name,studentUserId:r.student_user_id,studentDisplayName:r.student_display_name,planId:r.plan_id,planName:r.plan_name,status:r.status,requestedAtUtc:r.requested_at_utc,startedAtUtc:r.started_at_utc,endedAtUtc:r.ended_at_utc,studentMessagingEnabled:r.student_messaging_enabled===1,studentTradeReviewsEnabled:r.student_trade_reviews_enabled===1}));
    const relationshipIds=new Set(relationships.map(r=>r.relationshipId)); const grants=(this.database.prepare(`SELECT * FROM traderlink_community_journal_grants WHERE community_id=? AND (coach_user_id=? OR student_user_id=?) ORDER BY granted_at_utc DESC`).all(community.community_id,viewer.userId,viewer.userId) as any[]).filter(r=>relationshipIds.has(r.relationship_id)).map((r):TraderLinkCommunityJournalGrant=>({grantId:r.grant_id,relationshipId:r.relationship_id,communityId:r.community_id,coachUserId:r.coach_user_id,studentUserId:r.student_user_id,journalAccountId:r.journal_account_id,dataScope:r.data_scope,status:r.status,grantedAtUtc:r.granted_at_utc,revokedAtUtc:r.revoked_at_utc}));
    const alertTemplates=(this.database.prepare(`SELECT template.*,owner.display_name owner_name,coalesce(json_group_array(json_object('key',field.field_key,'label',field.label,'type',field.field_type,'required',field.required,'placeholder',field.placeholder,'ordinal',field.ordinal)) FILTER(WHERE field.field_key IS NOT NULL),'[]') fields FROM traderlink_community_alert_templates template JOIN platform_users owner ON owner.user_id=template.owner_user_id LEFT JOIN traderlink_community_alert_template_fields field ON field.template_id=template.template_id WHERE template.community_id=? AND template.status='active' AND (template.scope='community' OR template.owner_user_id=?) GROUP BY template.template_id ORDER BY template.scope DESC,template.title`).all(community.community_id,viewer.userId) as any[]).map((r):TraderLinkCommunityAlertTemplate=>({templateId:r.template_id,communityId:r.community_id,ownerUserId:r.owner_user_id,ownerName:r.owner_name,title:r.title,scope:r.scope,status:r.status,fields:Object.freeze((JSON.parse(r.fields) as any[]).sort((a,b)=>a.ordinal-b.ordinal).map(field=>({key:field.key,label:field.label,type:field.type,required:field.required===1,placeholder:field.placeholder,ordinal:field.ordinal})))}));
    const coachingMessages=(this.database.prepare(`SELECT message.*,author.display_name author_name FROM traderlink_community_coaching_messages message JOIN platform_users author ON author.user_id=message.author_user_id WHERE message.community_id=? ORDER BY message.created_at_utc`).all(community.community_id) as any[]).filter(row=>relationshipIds.has(row.relationship_id)).map((r):TraderLinkCommunityCoachingMessage=>({messageId:r.message_id,relationshipId:r.relationship_id,authorUserId:r.author_user_id,authorName:r.author_name,body:r.body,createdAtUtc:r.created_at_utc,editedAtUtc:r.edited_at_utc}));
    const tradeReviews=(this.database.prepare(`SELECT * FROM traderlink_community_coaching_trade_reviews WHERE community_id=? ORDER BY updated_at_utc DESC`).all(community.community_id) as any[]).filter(row=>relationshipIds.has(row.relationship_id)).map((r):TraderLinkCommunityTradeReview=>({reviewId:r.review_id,relationshipId:r.relationship_id,requestedByUserId:r.requested_by_user_id,title:r.title,studentContext:r.student_context,coachFeedback:r.coach_feedback,status:r.status,requestedAtUtc:r.requested_at_utc,completedAtUtc:r.completed_at_utc,updatedAtUtc:r.updated_at_utc}));
    const coachingTasks=(this.database.prepare(`SELECT * FROM traderlink_community_coaching_tasks WHERE community_id=? ORDER BY CASE status WHEN 'open' THEN 0 ELSE 1 END,due_at_utc,created_at_utc DESC`).all(community.community_id) as any[]).filter(row=>relationshipIds.has(row.relationship_id)).map((r):TraderLinkCommunityCoachingTask=>({taskId:r.task_id,relationshipId:r.relationship_id,title:r.title,dueAtUtc:r.due_at_utc,priority:r.priority,status:r.status,createdAtUtc:r.created_at_utc,completedAtUtc:r.completed_at_utc}));
    const coachingRecords=(this.database.prepare(`SELECT record.*,author.display_name author_name,relationship.coach_user_id FROM traderlink_community_coaching_records record JOIN platform_users author ON author.user_id=record.author_user_id JOIN traderlink_community_coaching_relationships relationship ON relationship.relationship_id=record.relationship_id WHERE record.community_id=? ORDER BY record.occurred_at_utc DESC`).all(community.community_id) as any[]).filter(row=>relationshipIds.has(row.relationship_id)&&(row.visibility==='shared'||row.coach_user_id===viewer.userId)).map((r):TraderLinkCommunityCoachingRecord=>({recordId:r.record_id,relationshipId:r.relationship_id,authorUserId:r.author_user_id,authorName:r.author_name,recordType:r.record_type,visibility:r.visibility,title:r.title,body:r.body,occurredAtUtc:r.occurred_at_utc}));
    const settingsRow=this.database.prepare(`SELECT description,personal_alert_templates_enabled FROM traderlink_community_settings WHERE community_id=?`).get(community.community_id) as {description:string;personal_alert_templates_enabled:number}|undefined;
    const canMembers=access.capabilities.includes("community.members.view"); const memberRows=canMembers?this.database.prepare(`SELECT m.user_id,u.display_name,m.status,m.discord_verified_at_utc,(SELECT max(e.occurred_at_utc) FROM traderlink_community_activity_events e WHERE e.community_id=m.community_id AND e.user_id=m.user_id) last_active,coalesce((SELECT json_group_array(r.name) FROM traderlink_community_member_role_assignments x JOIN traderlink_community_roles r ON r.role_id=x.role_id WHERE x.community_id=m.community_id AND x.user_id=m.user_id AND x.status='active'),'[]') roles FROM traderlink_community_memberships m JOIN platform_users u ON u.user_id=m.user_id WHERE m.community_id=? ORDER BY u.display_name`).all(community.community_id) as any[]:[];
    const members:TraderLinkCommunityMemberSummary[]=memberRows.map(r=>({userId:r.user_id,displayName:r.display_name,membershipStatus:r.status,lastVerifiedAtUtc:r.discord_verified_at_utc,lastActiveAtUtc:r.last_active,roles:parseJsonStrings(r.roles),capabilities:this.permissions.resolveAccess(community.community_id,r.user_id).capabilities}));
    const staffRoles=access.capabilities.includes("community.roles.manage")?(this.database.prepare(`SELECT r.role_id,r.name,coalesce((SELECT json_group_array(c.capability_key) FROM traderlink_community_role_capabilities c WHERE c.role_id=r.role_id),'[]') capabilities,coalesce((SELECT json_group_array(m.discord_role_id) FROM traderlink_community_discord_role_mappings m WHERE m.role_id=r.role_id AND m.status='active'),'[]') discord_roles FROM traderlink_community_roles r WHERE r.community_id=? AND r.status='active' ORDER BY r.name`).all(community.community_id) as any[]).map(r=>({roleId:r.role_id,name:r.name,capabilities:parseJsonStrings(r.capabilities) as readonly TraderLinkCommunityCapability[],discordRoleIds:parseJsonStrings(r.discord_roles)})):[];
    const channels=(access.capabilities.includes("community.discord.manage")?(this.database.prepare(`SELECT * FROM traderlink_community_discord_destinations WHERE community_id=? ORDER BY content_type,name`).all(community.community_id) as any[]):[]).map((r):TraderLinkCommunityChannel=>({destinationId:r.destination_id,communityId:r.community_id,name:r.name,discordChannelId:r.discord_channel_id,contentType:r.content_type,status:r.status}));
    const cutoff=new Date(Date.now()-30*86400000).toISOString().slice(0,10); const analyticsRow=access.capabilities.includes("community.analytics.view")?this.database.prepare(`SELECT coalesce(sum(views),0) views,count(DISTINCT user_id) users,coalesce(sum(CASE WHEN path LIKE '%/alerts%' THEN views ELSE 0 END),0) alert_views,coalesce(sum(CASE WHEN path LIKE '%/watchlists%' THEN views ELSE 0 END),0) watchlist_views,coalesce(sum(CASE WHEN path LIKE '%/coach%' THEN views ELSE 0 END),0) coaching_views FROM traderlink_community_activity_daily_members WHERE community_id=? AND activity_day>=?`).get(community.community_id,cutoff) as any:null; const topPages=access.capabilities.includes("community.analytics.view")?(this.database.prepare(`SELECT path,sum(views) views,count(DISTINCT user_id) users FROM traderlink_community_activity_daily_members WHERE community_id=? AND activity_day>=? GROUP BY path ORDER BY views DESC LIMIT 10`).all(community.community_id,cutoff) as any[]).map(r=>({path:r.path,views:r.views,uniqueMembers:r.users})):[];
    const namedMemberPages=access.capabilities.includes("community.member_activity.view")?(this.database.prepare(`SELECT activity.user_id userId,user.display_name displayName,activity.path,sum(activity.views) views,max(activity.last_viewed_at_utc) lastViewedAtUtc FROM traderlink_community_activity_daily_members activity JOIN platform_users user ON user.user_id=activity.user_id WHERE activity.community_id=? AND activity.activity_day>=? GROUP BY activity.user_id,activity.path ORDER BY lastViewedAtUtc DESC LIMIT 200`).all(community.community_id,cutoff) as any[]):[];
    const referral=access.capabilities.includes("community.referrals.view")?this.database.prepare(`SELECT count(DISTINCT a.attribution_id) attributed,sum(CASE WHEN a.status='converted' THEN 1 ELSE 0 END) converted,coalesce(sum(e.commission_minor),0) earnings,max(p.currency) currency,max(p.commission_basis_points) bps,max(p.status) program_status FROM traderlink_community_partner_programs p LEFT JOIN traderlink_community_partner_attributions a ON a.community_id=p.community_id LEFT JOIN traderlink_community_partner_earnings e ON e.attribution_id=a.attribution_id AND e.status IN ('estimated','approved','paid') WHERE p.community_id=?`).get(community.community_id) as any:null;
    const count=(this.database.prepare(`SELECT count(*) count FROM traderlink_community_memberships WHERE community_id=? AND status='active'`).get(community.community_id) as {count:number}).count;
    return Object.freeze({community:{communityId:community.community_id,discordGuildId:community.discord_guild_id,slug:community.slug,displayName:community.display_name,status:community.status,isOwner:access.isOwner,memberCount:count},viewer:{...viewer,capabilities:access.capabilities},alerts:Object.freeze(alerts),alertTemplates:Object.freeze(alertTemplates),watchlists:Object.freeze(watchlists),coaches:Object.freeze(coaches),plans:Object.freeze(plans),relationships:Object.freeze(relationships),journalGrants:Object.freeze(grants),coachingMessages:Object.freeze(coachingMessages),tradeReviews:Object.freeze(tradeReviews),coachingTasks:Object.freeze(coachingTasks),coachingRecords:Object.freeze(coachingRecords),settings:{description:settingsRow?.description??"",personalAlertTemplatesEnabled:settingsRow?.personal_alert_templates_enabled!==0},audiences:Object.freeze(audiences),channels:Object.freeze(channels),members:Object.freeze(members),staffRoles:Object.freeze(staffRoles),analytics:{views30Days:analyticsRow?.views??0,uniqueMembers30Days:analyticsRow?.users??0,alertViews30Days:analyticsRow?.alert_views??0,watchlistViews30Days:analyticsRow?.watchlist_views??0,coachingViews30Days:analyticsRow?.coaching_views??0,topPages:Object.freeze(topPages),namedMemberPages:Object.freeze(namedMemberPages)},referrals:{attributedMembers:referral?.attributed??0,tier2Members:referral?.converted??0,estimatedEarningsMinor:referral?.earnings??0,currency:referral?.currency??"USD",commissionLabel:referral?.program_status==="active"&&referral?.bps!=null?`${referral.bps/100}%`:"Not configured"}});
  }
}
