import {createHash} from "node:crypto";
import type Database from "better-sqlite3";
import {assertCanonicalUtcTimestamp,assertCanonicalUuidV4,createCanonicalUuidV4,platformFailure} from "../../platform/server/database/platform-migration-contract";
import {TraderLinkCommunityRepository} from "./traderlink-community-repository";

/* eslint-disable @typescript-eslint/no-explicit-any -- SQLite rows are narrowed immediately after lookup. */

type Actor=Readonly<{userId:string;displayName:string;discordRoleIds:readonly string[]}>;
type ReviewType="single_trade"|"multiple_trades"|"weekly"|"monthly"|"general"|"session"|"custom";
const clean=(value:string,max:number,required=true)=>{const result=value.normalize("NFKC").trim();if((required&&!result)||result.length>max||/[\u0000-\u001f\u007f]/u.test(result))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"text"});return result;};

export class TraderLinkCommunityCoachingProgramService{
 constructor(private readonly database:Database.Database){}
 private relation(communityId:string,relationshipId:string,actor:Actor){assertCanonicalUuidV4(relationshipId,"relationshipId");const row=this.database.prepare(`SELECT relationship.*,plan.required_discord_role_id,CASE WHEN plan.required_discord_role_id IS NULL THEN 1 ELSE EXISTS(SELECT 1 FROM traderlink_communities community JOIN platform_discord_memberships membership ON membership.guild_id=community.discord_guild_id JOIN json_each(membership.role_ids_json) role ON role.value=plan.required_discord_role_id WHERE community.community_id=relationship.community_id AND membership.user_id=relationship.student_user_id) END required_role_present FROM traderlink_community_coaching_relationships relationship JOIN traderlink_community_coaching_plans plan ON plan.plan_id=relationship.plan_id WHERE relationship.community_id=? AND relationship.relationship_id=? AND relationship.status='active'`).get(communityId,relationshipId) as any;if(!row||(row.coach_user_id!==actor.userId&&row.student_user_id!==actor.userId)||row.required_role_present!==1)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"coaching_access_paused"});return row;}
 private coach(communityId:string,relationshipId:string,actor:Actor){const row=this.relation(communityId,relationshipId,actor);if(row.coach_user_id!==actor.userId)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"coach_only"});new TraderLinkCommunityRepository(this.database).requireCapability(communityId,actor.userId,"community.coaching.students");return row;}
 createReview(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;reviewType:ReviewType;title:string;context:string;periodStart?:string;periodEnd?:string;roundTripIds:readonly string[];atUtc:string}>){assertCanonicalUtcTimestamp(input.atUtc,"atUtc");const relation=this.relation(input.communityId,input.relationshipId,input.actor);const isCoach=relation.coach_user_id===input.actor.userId;if(!isCoach&&relation.student_trade_reviews_enabled!==1)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"request_trade_review"});if(!isCoach&&!["single_trade","multiple_trades"].includes(input.reviewType))platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"student_review_type"});if(input.roundTripIds.length>500)platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"roundTripIds"});input.roundTripIds.forEach(id=>assertCanonicalUuidV4(id,"roundTripId"));const id=createCanonicalUuidV4();this.database.transaction(()=>{this.database.prepare(`INSERT INTO traderlink_community_coaching_trade_reviews(review_id,relationship_id,community_id,requested_by_user_id,round_trip_id,title,student_context,coach_feedback,status,requested_at_utc,completed_at_utc,updated_at_utc,review_type,period_start,period_end) VALUES(?,?,?,?,NULL,?,?,?,'requested',?,NULL,?,?,?,?)`).run(id,input.relationshipId,input.communityId,input.actor.userId,clean(input.title,140),clean(input.context,4000,false),"",input.atUtc,input.atUtc,input.reviewType,input.periodStart??null,input.periodEnd??null);const add=this.database.prepare(`INSERT INTO traderlink_community_coaching_review_trades(review_id,community_id,round_trip_id,ordinal) VALUES(?,?,?,?)`);input.roundTripIds.forEach((trade,index)=>add.run(id,input.communityId,trade,index));})();return id;}
 replyToReview(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;reviewId:string;body:string;atUtc:string}>){this.relation(input.communityId,input.relationshipId,input.actor);assertCanonicalUuidV4(input.reviewId,"reviewId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");const review=this.database.prepare(`SELECT 1 FROM traderlink_community_coaching_trade_reviews WHERE community_id=? AND relationship_id=? AND review_id=?`).get(input.communityId,input.relationshipId,input.reviewId);if(!review)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"review_reply"});const id=createCanonicalUuidV4();this.database.prepare(`INSERT INTO traderlink_community_coaching_review_replies(reply_id,review_id,community_id,author_user_id,body,created_at_utc) VALUES(?,?,?,?,?,?)`).run(id,input.reviewId,input.communityId,input.actor.userId,clean(input.body,8000),input.atUtc);return id;}
 createSession(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;title:string;agenda:string;scheduledAtUtc?:string;atUtc:string}>){this.coach(input.communityId,input.relationshipId,input.actor);assertCanonicalUtcTimestamp(input.atUtc,"atUtc");if(input.scheduledAtUtc)assertCanonicalUtcTimestamp(input.scheduledAtUtc,"scheduledAtUtc");const id=createCanonicalUuidV4();this.database.prepare(`INSERT INTO traderlink_community_coaching_sessions(session_id,relationship_id,community_id,coach_user_id,title,agenda,notes,scheduled_at_utc,completed_at_utc,status,created_at_utc,updated_at_utc) VALUES(?,?,?,?,?,?,'',?,NULL,'scheduled',?,?)`).run(id,input.relationshipId,input.communityId,input.actor.userId,clean(input.title,160),clean(input.agenda,8000,false),input.scheduledAtUtc??null,input.atUtc,input.atUtc);return id;}
 completeSession(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;sessionId:string;notes:string;atUtc:string}>){this.coach(input.communityId,input.relationshipId,input.actor);assertCanonicalUuidV4(input.sessionId,"sessionId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");const changed=this.database.prepare(`UPDATE traderlink_community_coaching_sessions SET notes=?,status='completed',completed_at_utc=?,updated_at_utc=? WHERE community_id=? AND relationship_id=? AND session_id=?`).run(clean(input.notes,12000,false),input.atUtc,input.atUtc,input.communityId,input.relationshipId,input.sessionId);if(changed.changes!==1)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"complete_session"});}
 createTeaching(input:Readonly<{communityId:string;actor:Actor;title:string;teachingType:"lesson"|"class"|"assignment";body:string;deliveryUrl:string;scheduledAtUtc?:string;audienceMode:"all_students"|"plan"|"selected_students";planId?:string;relationshipIds:readonly string[];publish:boolean;atUtc:string}>){new TraderLinkCommunityRepository(this.database).requireCapability(input.communityId,input.actor.userId,"community.coaching.students");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");if(input.scheduledAtUtc)assertCanonicalUtcTimestamp(input.scheduledAtUtc,"scheduledAtUtc");const eligible=this.database.prepare(`SELECT relationship_id FROM traderlink_community_coaching_relationships WHERE community_id=? AND coach_user_id=? AND status='active' AND (?='all_students' OR (?='plan' AND plan_id=?) OR (?='selected_students' AND relationship_id IN (SELECT value FROM json_each(?))))`).all(input.communityId,input.actor.userId,input.audienceMode,input.audienceMode,input.planId??null,input.audienceMode,JSON.stringify(input.relationshipIds)) as {relationship_id:string}[];if(!eligible.length)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"teaching_audience"});const id=createCanonicalUuidV4();this.database.transaction(()=>{this.database.prepare(`INSERT INTO traderlink_community_coaching_teaching_items(teaching_id,community_id,coach_user_id,title,teaching_type,body,delivery_url,scheduled_at_utc,status,audience_mode,plan_id,created_at_utc,updated_at_utc) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,input.communityId,input.actor.userId,clean(input.title,160),input.teachingType,clean(input.body,20000,false),clean(input.deliveryUrl,1000,false),input.scheduledAtUtc??null,input.publish?"published":"draft",input.audienceMode,input.planId??null,input.atUtc,input.atUtc);const add=this.database.prepare(`INSERT INTO traderlink_community_coaching_teaching_students(teaching_id,community_id,relationship_id,status,completed_at_utc,updated_at_utc) VALUES(?,?,?,'assigned',NULL,?)`);eligible.forEach(row=>add.run(id,input.communityId,row.relationship_id,input.atUtc));})();return id;}
 updateTeachingStudent(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;teachingId:string;status:"attending"|"completed"|"excused";atUtc:string}>){const relation=this.relation(input.communityId,input.relationshipId,input.actor);assertCanonicalUuidV4(input.teachingId,"teachingId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");if(relation.student_user_id!==input.actor.userId&&relation.coach_user_id!==input.actor.userId)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"teaching_status"});this.database.prepare(`UPDATE traderlink_community_coaching_teaching_students SET status=?,completed_at_utc=CASE WHEN ?='completed' THEN ? ELSE NULL END,updated_at_utc=? WHERE community_id=? AND relationship_id=? AND teaching_id=?`).run(input.status,input.status,input.atUtc,input.atUtc,input.communityId,input.relationshipId,input.teachingId);}
 addImage(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;targetType:"message"|"review"|"session"|"teaching"|"submission";targetId:string;filename:string;mediaType:"image/png"|"image/jpeg"|"image/webp";content:Buffer;atUtc:string}>){const relation=this.relation(input.communityId,input.relationshipId,input.actor);assertCanonicalUuidV4(input.targetId,"targetId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");if(relation.student_user_id===input.actor.userId&&relation.student_messaging_enabled!==1)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"student_attachment"});if(input.content.length<1||input.content.length>8388608)platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"imageSize"});const signatures={"image/png":input.content.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),"image/jpeg":input.content[0]===255&&input.content[1]===216,"image/webp":input.content.subarray(0,4).toString()==="RIFF"&&input.content.subarray(8,12).toString()==="WEBP"};if(!signatures[input.mediaType])platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"imageType"});const id=createCanonicalUuidV4();this.database.prepare(`INSERT INTO traderlink_community_coaching_attachments(attachment_id,relationship_id,community_id,uploaded_by_user_id,target_type,target_id,filename,media_type,byte_length,sha256,content,created_at_utc) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,input.relationshipId,input.communityId,input.actor.userId,input.targetType,input.targetId,clean(input.filename,180),input.mediaType,input.content.length,createHash("sha256").update(input.content).digest("hex"),input.content,input.atUtc);return id;}
 readImage(input:Readonly<{communityId:string;actor:Actor;attachmentId:string}>){assertCanonicalUuidV4(input.attachmentId,"attachmentId");const row=this.database.prepare(`SELECT attachment.*,relationship.coach_user_id,relationship.student_user_id,relationship.status FROM traderlink_community_coaching_attachments attachment JOIN traderlink_community_coaching_relationships relationship ON relationship.relationship_id=attachment.relationship_id WHERE attachment.community_id=? AND attachment.attachment_id=?`).get(input.communityId,input.attachmentId) as any;if(!row||row.status!=="active"||(row.coach_user_id!==input.actor.userId&&row.student_user_id!==input.actor.userId))platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"read_coaching_attachment"});return {content:row.content as Buffer,mediaType:row.media_type as string,filename:row.filename as string};}
}
