import {createHash} from "node:crypto";
import type Database from "better-sqlite3";
import {assertCanonicalUtcTimestamp,assertCanonicalUuidV4,createCanonicalUuidV4,platformFailure} from "../../platform/server/database/platform-migration-contract";
import {TraderLinkCommunityRepository} from "./traderlink-community-repository";
import {TraderLinkCommunityCoachJournalReadService} from "./traderlink-community-coach-journal-read-service";

/* eslint-disable @typescript-eslint/no-explicit-any -- SQLite rows are narrowed immediately after lookup. */

type Actor=Readonly<{userId:string;displayName:string;discordRoleIds:readonly string[]}>;
type ReviewType="single_trade"|"multiple_trades"|"weekly"|"monthly"|"general"|"session"|"custom";
const clean=(value:string,max:number,required=true)=>{const result=value.normalize("NFKC").trim();if((required&&!result)||result.length>max||/[\u0000-\u0008\u000b\u000c\u000e-\u001f\u007f]/u.test(result))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"text"});return result;};

export class TraderLinkCommunityCoachingProgramService{
 constructor(private readonly database:Database.Database){}
 private relation(communityId:string,relationshipId:string,actor:Actor){assertCanonicalUuidV4(relationshipId,"relationshipId");const row=this.database.prepare(`SELECT relationship.*,plan.required_discord_role_id,CASE WHEN plan.required_discord_role_id IS NULL THEN 1 ELSE EXISTS(SELECT 1 FROM traderlink_communities community JOIN platform_discord_memberships membership ON membership.guild_id=community.discord_guild_id JOIN json_each(membership.role_ids_json) role ON role.value=plan.required_discord_role_id WHERE community.community_id=relationship.community_id AND membership.user_id=relationship.student_user_id) END required_role_present FROM traderlink_community_coaching_relationships relationship JOIN traderlink_community_coaching_plans plan ON plan.plan_id=relationship.plan_id WHERE relationship.community_id=? AND relationship.relationship_id=? AND relationship.status='active'`).get(communityId,relationshipId) as any;if(!row||(row.coach_user_id!==actor.userId&&row.student_user_id!==actor.userId)||row.required_role_present!==1)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"coaching_access_paused"});if(row.coach_user_id===actor.userId)new TraderLinkCommunityRepository(this.database).requireCapability(communityId,actor.userId,"community.coaching.students");return row;}
 private coach(communityId:string,relationshipId:string,actor:Actor){const row=this.relation(communityId,relationshipId,actor);if(row.coach_user_id!==actor.userId)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"coach_only"});new TraderLinkCommunityRepository(this.database).requireCapability(communityId,actor.userId,"community.coaching.students");return row;}
 private review(communityId:string,relationshipId:string,reviewId:string,actor:Actor){assertCanonicalUuidV4(reviewId,"reviewId");const relation=this.relation(communityId,relationshipId,actor);const review=this.database.prepare(`SELECT * FROM traderlink_community_coaching_trade_reviews WHERE community_id=? AND relationship_id=? AND review_id=?`).get(communityId,relationshipId,reviewId) as any;if(!review)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"coaching_review"});return {relation,review};}
 updateReviewAction(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;reviewId:string;actionId:string;state:"open"|"completed"|"removed";atUtc:string}>){
  assertCanonicalUuidV4(input.actionId,"actionId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
  const {relation,review}=this.review(input.communityId,input.relationshipId,input.reviewId,input.actor);
  const isCoach=relation.coach_user_id===input.actor.userId;
  if(!["open","completed","removed"].includes(input.state)||(!isCoach&&(!review.delivered_at_utc||input.state==="removed"))||(input.state==="removed"&&review.delivery_state!=="draft"))platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"review_action"});
  if(input.state==="removed")this.database.prepare(`UPDATE traderlink_community_coaching_review_actions SET status='cancelled' WHERE action_id=? AND review_id=? AND community_id=?`).run(input.actionId,input.reviewId,input.communityId);
  else this.database.prepare(`UPDATE traderlink_community_coaching_review_actions SET status=?,completed_at_utc=?,updated_at_utc=? WHERE action_id=? AND review_id=? AND community_id=?`).run(input.state,input.state==="completed"?input.atUtc:null,input.atUtc,input.actionId,input.reviewId,input.communityId);
 }
 private event(input:Readonly<{communityId:string;relationshipId:string;reviewId:string;actorUserId:string;eventType:"started"|"trade_added"|"trade_removed"|"trade_saved"|"delivered"|"viewed"|"follow_up_required"|"completed"|"cancelled";atUtc:string;details?:unknown}>){this.database.prepare(`INSERT INTO traderlink_community_coaching_review_events(event_id,review_id,relationship_id,community_id,actor_user_id,event_type,occurred_at_utc,details_json) VALUES(?,?,?,?,?,?,?,?)`).run(createCanonicalUuidV4(),input.reviewId,input.relationshipId,input.communityId,input.actorUserId,input.eventType,input.atUtc,JSON.stringify(input.details??{}));}
 createReview(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;reviewType:ReviewType;title:string;context:string;periodStart?:string;periodEnd?:string;dueAtUtc?:string;roundTripIds:readonly string[];atUtc:string}>){
  assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
  const relation=this.relation(input.communityId,input.relationshipId,input.actor);
  const isCoach=relation.coach_user_id===input.actor.userId;
  if(isCoach)this.coach(input.communityId,input.relationshipId,input.actor);
  if(!isCoach&&relation.student_trade_reviews_enabled!==1)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"request_trade_review"});
  if(!["single_trade","multiple_trades","weekly","monthly","general","session","custom"].includes(input.reviewType)||(!isCoach&&!["single_trade","multiple_trades"].includes(input.reviewType)))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"reviewType"});
  if(input.dueAtUtc)assertCanonicalUtcTimestamp(input.dueAtUtc,"dueAtUtc");
  for(const date of [input.periodStart,input.periodEnd])if(date&&(!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"reviewPeriod"});
  if(input.periodStart&&input.periodEnd&&input.periodStart>input.periodEnd)platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"reviewPeriod"});
  const ids=[...new Set(input.roundTripIds)];
  if(ids.length>500)platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"roundTripIds"});
  ids.forEach(id=>assertCanonicalUuidV4(id,"roundTripId"));
  const available=new Map((ids.length?new TraderLinkCommunityCoachJournalReadService(this.database).read({coachUserId:relation.coach_user_id,relationshipId:input.relationshipId}).trades:[]).map(trade=>[trade.roundTripId,trade] as const));
  if(ids.some(id=>!available.has(id)))platformFailure("TRADERLINK_ACCOUNT_ACCESS_DENIED",{operation:"request_review_trade"});
  const id=createCanonicalUuidV4();
  this.database.transaction(()=>{
   this.database.prepare(`INSERT INTO traderlink_community_coaching_trade_reviews(review_id,relationship_id,community_id,requested_by_user_id,round_trip_id,title,student_context,coach_feedback,status,requested_at_utc,completed_at_utc,updated_at_utc,review_type,period_start,period_end,due_at_utc) VALUES(?,?,?,?,NULL,?,?,?,'requested',?,NULL,?,?,?,?,?)`).run(id,input.relationshipId,input.communityId,input.actor.userId,clean(input.title,140),clean(input.context,4000,false),"",input.atUtc,input.atUtc,input.reviewType,isCoach?input.periodStart??null:null,isCoach?input.periodEnd??null:null,isCoach?input.dueAtUtc??null:null);
   const add=this.database.prepare(`INSERT INTO traderlink_community_coaching_review_trades(review_id,community_id,round_trip_id,ordinal,selected_by_user_id,selection_source,workflow_state,updated_at_utc,trade_label) VALUES(?,?,?,?,?,?,'queued',?,?)`);
   ids.forEach((tradeId,index)=>{const trade=available.get(tradeId)!;add.run(id,input.communityId,tradeId,index,input.actor.userId,isCoach?"coach":"student",input.atUtc,`${trade.symbol} · ${trade.openedAtUtc.slice(0,10)} · ${trade.direction}`);});
  })();
  return id;
 }
 startReview(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;reviewId:string;atUtc:string}>){this.coach(input.communityId,input.relationshipId,input.actor);assertCanonicalUtcTimestamp(input.atUtc,"atUtc");const {review}=this.review(input.communityId,input.relationshipId,input.reviewId,input.actor);if(review.delivery_state!=="draft"||review.status==="cancelled")platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"reviewState"});if(review.status==="requested"){this.database.transaction(()=>{this.database.prepare(`UPDATE traderlink_community_coaching_trade_reviews SET status='in_review',updated_at_utc=? WHERE review_id=? AND community_id=?`).run(input.atUtc,input.reviewId,input.communityId);this.event({...input,actorUserId:input.actor.userId,eventType:"started"});})();}}
 selectTrades(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;reviewId:string;roundTripIds:readonly string[];atUtc:string}>){
  this.coach(input.communityId,input.relationshipId,input.actor);
  assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
  const {review}=this.review(input.communityId,input.relationshipId,input.reviewId,input.actor);
  if(review.delivery_state!=="draft")platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"reviewState"});
  const available=new Map(new TraderLinkCommunityCoachJournalReadService(this.database).read({coachUserId:input.actor.userId,relationshipId:input.relationshipId}).trades.map(trade=>[trade.roundTripId,trade] as const));
  const ids=[...new Set(input.roundTripIds)];
  if(ids.length>500||ids.some(id=>!available.has(id)))platformFailure("TRADERLINK_ACCOUNT_ACCESS_DENIED",{operation:"select_review_trade"});
  this.database.transaction(()=>{
   const existing=this.database.prepare(`SELECT round_trip_id,workflow_state,ordinal FROM traderlink_community_coaching_review_trades WHERE review_id=?`).all(input.reviewId) as {round_trip_id:string;workflow_state:string;ordinal:number}[];
   const byId=new Map(existing.map(row=>[row.round_trip_id,row]));
   let ordinal=existing.reduce((maximum,row)=>Math.max(maximum,row.ordinal),-1)+1;
   if(ordinal+ids.filter(id=>!byId.has(id)).length>500)platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"reviewTradeLimit"});
   for(const id of ids){
    const current=byId.get(id);if(current&&current.workflow_state!=="removed")continue;
    const trade=available.get(id)!;
    const label=`${trade.symbol} · ${trade.openedAtUtc.slice(0,10)} · ${trade.direction}`;
    if(current)this.database.prepare(`UPDATE traderlink_community_coaching_review_trades SET selection_source='coach',selected_by_user_id=?,workflow_state='queued',removed_at_utc=NULL,trade_label=?,updated_at_utc=? WHERE review_id=? AND round_trip_id=?`).run(input.actor.userId,label,input.atUtc,input.reviewId,id);
    else this.database.prepare(`INSERT INTO traderlink_community_coaching_review_trades(review_id,community_id,round_trip_id,ordinal,selected_by_user_id,selection_source,workflow_state,trade_label,updated_at_utc) VALUES(?,?,?,?,?,'coach','queued',?,?)`).run(input.reviewId,input.communityId,id,ordinal++,input.actor.userId,label,input.atUtc);
    this.event({...input,actorUserId:input.actor.userId,eventType:"trade_added",details:{roundTripId:id}});
   }
   if(ids.length)this.database.prepare(`UPDATE traderlink_community_coaching_trade_reviews SET status='in_review',updated_at_utc=? WHERE review_id=? AND community_id=?`).run(input.atUtc,input.reviewId,input.communityId);
  })();
 }
 removeTrades(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;reviewId:string;roundTripIds:readonly string[];atUtc:string}>){this.coach(input.communityId,input.relationshipId,input.actor);assertCanonicalUtcTimestamp(input.atUtc,"atUtc");const {review}=this.review(input.communityId,input.relationshipId,input.reviewId,input.actor);if(review.delivery_state!=="draft")platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"reviewState"});this.database.transaction(()=>{const statement=this.database.prepare(`UPDATE traderlink_community_coaching_review_trades SET workflow_state='removed',removed_at_utc=?,updated_at_utc=? WHERE review_id=? AND community_id=? AND round_trip_id=?`);for(const id of [...new Set(input.roundTripIds)]){assertCanonicalUuidV4(id,"roundTripId");statement.run(input.atUtc,input.atUtc,input.reviewId,input.communityId,id);this.event({...input,actorUserId:input.actor.userId,eventType:"trade_removed",details:{roundTripId:id}});}this.database.prepare(`UPDATE traderlink_community_coaching_trade_reviews SET updated_at_utc=? WHERE review_id=? AND community_id=?`).run(input.atUtc,input.reviewId,input.communityId);})();}
 saveTradeReview(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;reviewId:string;roundTripId:string;feedback:string;atUtc:string}>){this.coach(input.communityId,input.relationshipId,input.actor);assertCanonicalUtcTimestamp(input.atUtc,"atUtc");assertCanonicalUuidV4(input.roundTripId,"roundTripId");const {review}=this.review(input.communityId,input.relationshipId,input.reviewId,input.actor);if(review.delivery_state!=="draft")platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"reviewState"});const {trade}=new TraderLinkCommunityCoachJournalReadService(this.database).readTrade({coachUserId:input.actor.userId,relationshipId:input.relationshipId,roundTripId:input.roundTripId});const feedback=clean(input.feedback,12000);this.database.transaction(()=>{const changed=this.database.prepare(`UPDATE traderlink_community_coaching_review_trades SET coach_feedback=?,trade_label=?,workflow_state='saved',saved_at_utc=?,removed_at_utc=NULL,updated_at_utc=? WHERE review_id=? AND community_id=? AND round_trip_id=? AND workflow_state!='removed'`).run(feedback,`${trade.symbol} · ${trade.openedAtUtc.slice(0,10)} · ${trade.direction}`,input.atUtc,input.atUtc,input.reviewId,input.communityId,input.roundTripId);if(changed.changes!==1)platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"reviewTrade"});this.database.prepare(`UPDATE traderlink_community_coaching_trade_reviews SET status='in_review',updated_at_utc=? WHERE review_id=? AND community_id=?`).run(input.atUtc,input.reviewId,input.communityId);this.event({...input,actorUserId:input.actor.userId,eventType:"trade_saved",details:{roundTripId:input.roundTripId}});})();}
 addReviewAction(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;reviewId:string;title:string;details:string;dueAtUtc?:string;atUtc:string}>){this.coach(input.communityId,input.relationshipId,input.actor);assertCanonicalUtcTimestamp(input.atUtc,"atUtc");if(input.dueAtUtc)assertCanonicalUtcTimestamp(input.dueAtUtc,"dueAtUtc");const {review}=this.review(input.communityId,input.relationshipId,input.reviewId,input.actor);if(review.delivery_state!=="draft")platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"reviewState"});const id=createCanonicalUuidV4();this.database.prepare(`INSERT INTO traderlink_community_coaching_review_actions(action_id,review_id,relationship_id,community_id,created_by_user_id,title,details,due_at_utc,status,completed_at_utc,created_at_utc,updated_at_utc) VALUES(?,?,?,?,?,?,?,?, 'open',NULL,?,?)`).run(id,input.reviewId,input.relationshipId,input.communityId,input.actor.userId,clean(input.title,240),clean(input.details,4000,false),input.dueAtUtc??null,input.atUtc,input.atUtc);this.database.prepare(`UPDATE traderlink_community_coaching_trade_reviews SET status='in_review',updated_at_utc=? WHERE review_id=? AND community_id=?`).run(input.atUtc,input.reviewId,input.communityId);return id;}
 deliverReview(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;reviewId:string;atUtc:string}>){this.coach(input.communityId,input.relationshipId,input.actor);assertCanonicalUtcTimestamp(input.atUtc,"atUtc");const {review}=this.review(input.communityId,input.relationshipId,input.reviewId,input.actor);if(review.delivery_state!=="draft")platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"reviewState"});const counts=this.database.prepare(`SELECT count(*) total,sum(CASE WHEN workflow_state='saved' THEN 1 ELSE 0 END) saved FROM traderlink_community_coaching_review_trades WHERE review_id=? AND workflow_state!='removed'`).get(input.reviewId) as {total:number;saved:number|null};if(counts.total>0&&counts.saved!==counts.total)platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"unfinishedTradeReviews"});if(counts.total===0&&!review.coach_feedback&&!review.went_well&&!review.needs_work&&!review.next_focus&&!review.previous_focus_assessment&&!this.database.prepare(`SELECT 1 FROM traderlink_community_coaching_review_actions WHERE review_id=? AND status!='cancelled' LIMIT 1`).get(input.reviewId))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"emptyReview"});this.database.transaction(()=>{this.database.prepare(`UPDATE traderlink_community_coaching_trade_reviews SET delivery_state='delivered',delivered_at_utc=?,status='in_review',updated_at_utc=? WHERE review_id=? AND community_id=?`).run(input.atUtc,input.atUtc,input.reviewId,input.communityId);this.event({...input,actorUserId:input.actor.userId,eventType:"delivered"});})();}
 markReviewViewed(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;reviewId:string;atUtc:string}>){assertCanonicalUtcTimestamp(input.atUtc,"atUtc");const {relation,review}=this.review(input.communityId,input.relationshipId,input.reviewId,input.actor);if(relation.student_user_id!==input.actor.userId)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"review_view"});if(!["delivered","viewed"].includes(review.delivery_state))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"reviewState"});if(review.delivery_state==="delivered")this.database.transaction(()=>{this.database.prepare(`UPDATE traderlink_community_coaching_trade_reviews SET delivery_state='viewed',viewed_at_utc=?,updated_at_utc=? WHERE review_id=? AND community_id=?`).run(input.atUtc,input.atUtc,input.reviewId,input.communityId);this.event({...input,actorUserId:input.actor.userId,eventType:"viewed"});})();}
 setReviewLifecycle(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;reviewId:string;state:"follow_up"|"completed"|"cancelled";followUpDueAtUtc?:string;atUtc:string}>){this.coach(input.communityId,input.relationshipId,input.actor);assertCanonicalUtcTimestamp(input.atUtc,"atUtc");if(input.followUpDueAtUtc)assertCanonicalUtcTimestamp(input.followUpDueAtUtc,"followUpDueAtUtc");const {review}=this.review(input.communityId,input.relationshipId,input.reviewId,input.actor);if(!["follow_up","completed","cancelled"].includes(input.state)||["completed","cancelled"].includes(review.delivery_state)||(input.state==="completed"&&!review.delivered_at_utc))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"reviewState"});if(input.state==="follow_up"&&!["viewed","follow_up"].includes(review.delivery_state))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"reviewState"});if(input.state==="follow_up"&&!input.followUpDueAtUtc)platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"followUpDueAtUtc"});const eventType=input.state==="follow_up"?"follow_up_required":input.state;this.database.transaction(()=>{this.database.prepare(`UPDATE traderlink_community_coaching_trade_reviews SET delivery_state=?,status=CASE WHEN ?='completed' THEN 'completed' WHEN ?='cancelled' THEN 'cancelled' ELSE 'in_review' END,follow_up_due_at_utc=CASE WHEN ?='follow_up' THEN ? ELSE follow_up_due_at_utc END,completed_at_utc=CASE WHEN ?='completed' THEN ? ELSE completed_at_utc END,cancelled_at_utc=CASE WHEN ?='cancelled' THEN ? ELSE cancelled_at_utc END,updated_at_utc=? WHERE review_id=? AND community_id=?`).run(input.state,input.state,input.state,input.state,input.followUpDueAtUtc??null,input.state,input.atUtc,input.state,input.atUtc,input.atUtc,input.reviewId,input.communityId);this.event({...input,actorUserId:input.actor.userId,eventType});})();}
 replyToReview(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;reviewId:string;body:string;atUtc:string}>){this.relation(input.communityId,input.relationshipId,input.actor);assertCanonicalUuidV4(input.reviewId,"reviewId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");const review=this.database.prepare(`SELECT delivered_at_utc,delivery_state FROM traderlink_community_coaching_trade_reviews WHERE community_id=? AND relationship_id=? AND review_id=?`).get(input.communityId,input.relationshipId,input.reviewId) as {delivered_at_utc:string|null;delivery_state:string}|undefined;if(!review?.delivered_at_utc||["completed","cancelled"].includes(review.delivery_state))platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"review_reply"});const relation=this.relation(input.communityId,input.relationshipId,input.actor);if(relation.student_user_id===input.actor.userId&&relation.student_messaging_enabled!==1)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"student_review_reply"});const id=createCanonicalUuidV4();this.database.prepare(`INSERT INTO traderlink_community_coaching_review_replies(reply_id,review_id,community_id,author_user_id,body,created_at_utc) VALUES(?,?,?,?,?,?)`).run(id,input.reviewId,input.communityId,input.actor.userId,clean(input.body,8000),input.atUtc);return id;}
 createSession(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;title:string;agenda:string;scheduledAtUtc?:string;atUtc:string}>){this.coach(input.communityId,input.relationshipId,input.actor);assertCanonicalUtcTimestamp(input.atUtc,"atUtc");if(input.scheduledAtUtc)assertCanonicalUtcTimestamp(input.scheduledAtUtc,"scheduledAtUtc");const id=createCanonicalUuidV4();this.database.prepare(`INSERT INTO traderlink_community_coaching_sessions(session_id,relationship_id,community_id,coach_user_id,title,agenda,notes,scheduled_at_utc,completed_at_utc,status,created_at_utc,updated_at_utc) VALUES(?,?,?,?,?,?,'',?,NULL,'scheduled',?,?)`).run(id,input.relationshipId,input.communityId,input.actor.userId,clean(input.title,160),clean(input.agenda,8000,false),input.scheduledAtUtc??null,input.atUtc,input.atUtc);return id;}
 completeSession(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;sessionId:string;notes:string;atUtc:string}>){this.coach(input.communityId,input.relationshipId,input.actor);assertCanonicalUuidV4(input.sessionId,"sessionId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");const changed=this.database.prepare(`UPDATE traderlink_community_coaching_sessions SET notes=?,status='completed',completed_at_utc=?,updated_at_utc=? WHERE community_id=? AND relationship_id=? AND session_id=?`).run(clean(input.notes,12000,false),input.atUtc,input.atUtc,input.communityId,input.relationshipId,input.sessionId);if(changed.changes!==1)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"complete_session"});}
 createTeaching(input:Readonly<{communityId:string;actor:Actor;title:string;teachingType:"lesson"|"class"|"assignment";body:string;deliveryUrl:string;scheduledAtUtc?:string;audienceMode:"all_students"|"plan"|"selected_students";planId?:string;relationshipIds:readonly string[];publish:boolean;atUtc:string}>){new TraderLinkCommunityRepository(this.database).requireCapability(input.communityId,input.actor.userId,"community.coaching.students");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");if(input.scheduledAtUtc)assertCanonicalUtcTimestamp(input.scheduledAtUtc,"scheduledAtUtc");const eligible=this.database.prepare(`SELECT relationship_id FROM traderlink_community_coaching_relationships WHERE community_id=? AND coach_user_id=? AND status='active' AND (?='all_students' OR (?='plan' AND plan_id=?) OR (?='selected_students' AND relationship_id IN (SELECT value FROM json_each(?))))`).all(input.communityId,input.actor.userId,input.audienceMode,input.audienceMode,input.planId??null,input.audienceMode,JSON.stringify(input.relationshipIds)) as {relationship_id:string}[];if(!eligible.length)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"teaching_audience"});const id=createCanonicalUuidV4();this.database.transaction(()=>{this.database.prepare(`INSERT INTO traderlink_community_coaching_teaching_items(teaching_id,community_id,coach_user_id,title,teaching_type,body,delivery_url,scheduled_at_utc,status,audience_mode,plan_id,created_at_utc,updated_at_utc) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,input.communityId,input.actor.userId,clean(input.title,160),input.teachingType,clean(input.body,20000,false),clean(input.deliveryUrl,1000,false),input.scheduledAtUtc??null,input.publish?"published":"draft",input.audienceMode,input.planId??null,input.atUtc,input.atUtc);const add=this.database.prepare(`INSERT INTO traderlink_community_coaching_teaching_students(teaching_id,community_id,relationship_id,status,completed_at_utc,updated_at_utc) VALUES(?,?,?,'assigned',NULL,?)`);eligible.forEach(row=>add.run(id,input.communityId,row.relationship_id,input.atUtc));})();return id;}
 updateTeachingStudent(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;teachingId:string;status:"attending"|"completed"|"excused";atUtc:string}>){const relation=this.relation(input.communityId,input.relationshipId,input.actor);assertCanonicalUuidV4(input.teachingId,"teachingId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");if(relation.student_user_id!==input.actor.userId&&relation.coach_user_id!==input.actor.userId)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"teaching_status"});this.database.prepare(`UPDATE traderlink_community_coaching_teaching_students SET status=?,completed_at_utc=CASE WHEN ?='completed' THEN ? ELSE NULL END,updated_at_utc=? WHERE community_id=? AND relationship_id=? AND teaching_id=?`).run(input.status,input.status,input.atUtc,input.atUtc,input.communityId,input.relationshipId,input.teachingId);}
 addImage(input:Readonly<{communityId:string;actor:Actor;relationshipId:string;targetType:"message"|"review"|"session"|"teaching"|"submission";targetId:string;reviewId?:string;roundTripId?:string;filename:string;mediaType:"image/png"|"image/jpeg"|"image/webp";content:Buffer;atUtc:string}>){const relation=this.relation(input.communityId,input.relationshipId,input.actor);assertCanonicalUuidV4(input.targetId,"targetId");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");if(input.reviewId){const {review}=this.review(input.communityId,input.relationshipId,input.reviewId,input.actor);if(input.targetId!==input.reviewId||input.targetType!=="review"||review.delivery_state!=="draft"||relation.coach_user_id!==input.actor.userId)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"review_attachment"});if(input.roundTripId&&!this.database.prepare(`SELECT 1 FROM traderlink_community_coaching_review_trades WHERE review_id=? AND round_trip_id=? AND workflow_state!='removed'`).get(input.reviewId,input.roundTripId))platformFailure("TRADERLINK_ACCOUNT_ACCESS_DENIED",{operation:"review_attachment_trade"});}if(input.roundTripId)assertCanonicalUuidV4(input.roundTripId,"roundTripId");if(["review","submission"].includes(input.targetType))this.review(input.communityId,input.relationshipId,input.targetId,input.actor);if(relation.student_user_id===input.actor.userId&&relation.student_messaging_enabled!==1)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"student_attachment"});if(input.content.length<1||input.content.length>8388608)platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"imageSize"});const signatures={"image/png":input.content.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])),"image/jpeg":input.content[0]===255&&input.content[1]===216,"image/webp":input.content.subarray(0,4).toString()==="RIFF"&&input.content.subarray(8,12).toString()==="WEBP"};if(!signatures[input.mediaType])platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"imageType"});const id=createCanonicalUuidV4();this.database.transaction(()=>{this.database.prepare(`INSERT INTO traderlink_community_coaching_attachments(attachment_id,relationship_id,community_id,uploaded_by_user_id,target_type,target_id,filename,media_type,byte_length,sha256,content,created_at_utc) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,input.relationshipId,input.communityId,input.actor.userId,input.targetType,input.targetId,clean(input.filename,180).replace(/[\r\n\t]/g," "),input.mediaType,input.content.length,createHash("sha256").update(input.content).digest("hex"),input.content,input.atUtc);if(input.reviewId)this.database.prepare(`INSERT INTO traderlink_community_coaching_review_attachment_links(attachment_id,review_id,round_trip_id,community_id) VALUES(?,?,?,?)`).run(id,input.reviewId,input.roundTripId??null,input.communityId);})();return id;}
 readImage(input:Readonly<{communityId:string;actor:Actor;attachmentId:string}>){
  assertCanonicalUuidV4(input.attachmentId,"attachmentId");
  const row=this.database.prepare(`SELECT attachment.*,relationship.coach_user_id,relationship.student_user_id,relationship.status FROM traderlink_community_coaching_attachments attachment JOIN traderlink_community_coaching_relationships relationship ON relationship.relationship_id=attachment.relationship_id WHERE attachment.community_id=? AND attachment.attachment_id=?`).get(input.communityId,input.attachmentId) as any;
  if(!row)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"read_coaching_attachment"});
  this.relation(input.communityId,row.relationship_id,input.actor);
  if(row.student_user_id===input.actor.userId&&row.uploaded_by_user_id!==input.actor.userId&&["review","submission"].includes(row.target_type)){
   const review=this.database.prepare(`SELECT delivered_at_utc FROM traderlink_community_coaching_trade_reviews WHERE review_id=? AND relationship_id=? AND community_id=?`).get(row.target_id,row.relationship_id,input.communityId) as {delivered_at_utc:string|null}|undefined;
   if(!review?.delivered_at_utc)platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"unpublished_review_attachment"});
   const linked=this.database.prepare(`SELECT link.round_trip_id,selected.workflow_state FROM traderlink_community_coaching_review_attachment_links link LEFT JOIN traderlink_community_coaching_review_trades selected ON selected.review_id=link.review_id AND selected.round_trip_id=link.round_trip_id WHERE link.attachment_id=?`).get(input.attachmentId) as {round_trip_id:string|null;workflow_state:string|null}|undefined;
   if(linked?.round_trip_id&&linked.workflow_state!=="saved")platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"removed_review_attachment"});
  }
  return {content:row.content as Buffer,mediaType:row.media_type as string,filename:row.filename as string};
 }
}
