import type Database from "better-sqlite3";

/* eslint-disable @typescript-eslint/no-explicit-any -- SQLite projection rows are mapped immediately into strict exported contracts. */

import type {
  TraderLinkCommunityAlert,
  TraderLinkCommunityAudience,
  TraderLinkCommunityChannel,
  TraderLinkCommunityCoach,
  TraderLinkCommunityCoachingPlan,
  TraderLinkCommunityDashboardSnapshot,
  TraderLinkCommunityJournalGrant,
  TraderLinkCommunityMemberSummary,
  TraderLinkCommunityRelationship,
  TraderLinkCommunityWatchlistPlacement,
} from "../contracts/traderlink-community-platform-contracts";
import type { TraderLinkCommunityCapability } from "../contracts/traderlink-community-contracts";
import {
  assertCanonicalUtcTimestamp,
  assertCanonicalUuidV4,
  createCanonicalUuidV4,
  platformFailure,
} from "../../platform/server/database/platform-migration-contract";
import { TraderLinkCommunityRepository } from "./traderlink-community-repository";

const SLUG = /^[a-z0-9]+(?:-[a-z0-9]+)*$/u;
const SYMBOL = /^[A-Z0-9][A-Z0-9.-]{0,14}$/u;
const SNOWFLAKE = /^[0-9]{1,32}$/u;

function text(value: string, maximum: number, field: string, required = true): string {
  const normalized = value.normalize("NFKC").trim();
  if ((required && !normalized) || normalized.length > maximum || /[\u0000-\u001f\u007f]/u.test(normalized)) {
    platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED", { field });
  }
  return normalized;
}

function slug(value: string, field: string): string {
  const normalized = text(value, 100, field).toLowerCase().replace(/[^a-z0-9]+/gu, "-").replace(/^-|-$/gu, "");
  if (!SLUG.test(normalized)) platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED", { field });
  return normalized;
}

function parseJsonStrings(value: string): readonly string[] {
  try {
    const parsed: unknown = JSON.parse(value);
    return Array.isArray(parsed) && parsed.every((item) => typeof item === "string") ? Object.freeze(parsed) : Object.freeze([]);
  } catch { return Object.freeze([]); }
}

type BaseViewer = Readonly<{ userId: string; displayName: string; discordRoleIds: readonly string[] }>;

export class TraderLinkCommunityPlatformRepository {
  private readonly permissions: TraderLinkCommunityRepository;
  constructor(private readonly database: Database.Database) {
    this.permissions = new TraderLinkCommunityRepository(database);
  }

  private write<T>(operation: () => T): T {
    return this.database.transaction(operation).immediate();
  }

  private requireCapability(communityId: string, viewer: BaseViewer, capability: TraderLinkCommunityCapability) {
    return this.permissions.requireCapability(communityId, viewer.userId, capability);
  }

  ensureDefaultAudience(input: Readonly<{ communityId: string; actorUserId: string; atUtc: string }>): string {
    assertCanonicalUuidV4(input.communityId, "communityId"); assertCanonicalUuidV4(input.actorUserId, "actorUserId"); assertCanonicalUtcTimestamp(input.atUtc, "atUtc");
    const existing = this.database.prepare(`SELECT audience_id FROM traderlink_community_audiences WHERE community_id=? AND mode='everyone' AND status='active' ORDER BY created_at_utc LIMIT 1`).get(input.communityId) as {audience_id:string}|undefined;
    if (existing) return existing.audience_id;
    const id = createCanonicalUuidV4();
    this.database.prepare(`INSERT INTO traderlink_community_audiences(audience_id,community_id,name,mode,status,created_by_user_id,created_at_utc,updated_at_utc) VALUES(?,?,'Everyone','everyone','active',?,?,?)`).run(id,input.communityId,input.actorUserId,input.atUtc,input.atUtc);
    return id;
  }

  createAudience(input: Readonly<{ communityId: string; actor: BaseViewer; name: string; discordRoleIds: readonly string[]; atUtc: string }>): string {
    this.requireCapability(input.communityId,input.actor,"community.roles.manage"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    if (!Array.isArray(input.discordRoleIds) || input.discordRoleIds.length<1 || input.discordRoleIds.some((id)=>!SNOWFLAKE.test(id))) platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"discordRoleIds"});
    return this.write(()=>{ const id=createCanonicalUuidV4(); this.database.prepare(`INSERT INTO traderlink_community_audiences(audience_id,community_id,name,mode,status,created_by_user_id,created_at_utc,updated_at_utc) VALUES(?,?,?,'discord_roles','active',?,?,?)`).run(id,input.communityId,text(input.name,80,"name"),input.actor.userId,input.atUtc,input.atUtc); const statement=this.database.prepare(`INSERT INTO traderlink_community_audience_discord_roles(audience_id,community_id,discord_role_id) VALUES(?,?,?)`); for(const roleId of [...new Set(input.discordRoleIds)]) statement.run(id,input.communityId,roleId); return id; });
  }

  createAlert(input: Readonly<{ communityId:string; actor:BaseViewer; title:string; symbol?:string; body:string; audienceId:string; publish:boolean; atUtc:string }>): string {
    this.requireCapability(input.communityId,input.actor,"community.alerts.create"); assertCanonicalUuidV4(input.audienceId,"audienceId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    const normalizedSymbol=input.symbol?.trim().toUpperCase()||null; if(normalizedSymbol&&!SYMBOL.test(normalizedSymbol)) platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"symbol"});
    return this.write(()=>{ const id=createCanonicalUuidV4(); const base=slug(input.title,"title"); let candidate=base; let suffix=2; while(this.database.prepare(`SELECT 1 FROM traderlink_community_alerts WHERE community_id=? AND slug=?`).get(input.communityId,candidate)) candidate=`${base}-${suffix++}`; this.database.prepare(`INSERT INTO traderlink_community_alerts(alert_id,community_id,slug,author_user_id,title,symbol,body,status,audience_id,published_at_utc,created_at_utc,updated_at_utc) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,input.communityId,candidate,input.actor.userId,text(input.title,140,"title"),normalizedSymbol,text(input.body,8000,"body"),input.publish?"published":"draft",input.audienceId,input.publish?input.atUtc:null,input.atUtc,input.atUtc); if(input.publish)this.queueDestinations(input.communityId,"alert",id,"alerts",input.atUtc); return id; });
  }

  shareWatchlist(input: Readonly<{ communityId:string; actor:BaseViewer; watchlistId:string; audienceId:string; atUtc:string }>): string {
    this.requireCapability(input.communityId,input.actor,"community.watchlists.share_own"); assertCanonicalUuidV4(input.watchlistId,"watchlistId"); assertCanonicalUuidV4(input.audienceId,"audienceId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    const owner=this.database.prepare(`SELECT owner_user_id,status FROM community_watchlists WHERE watchlist_id=?`).get(input.watchlistId) as {owner_user_id:string;status:string}|undefined;
    const access=this.permissions.resolveAccess(input.communityId,input.actor.userId);
    if(!owner||owner.status!=="published"||(owner.owner_user_id!==input.actor.userId&&!access.capabilities.includes("community.watchlists.manage_all"))) platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"share_community_watchlist"});
    const id=createCanonicalUuidV4(); this.write(()=>{this.database.prepare(`INSERT INTO traderlink_community_watchlist_placements(placement_id,community_id,watchlist_id,author_user_id,audience_id,status,shared_at_utc) VALUES(?,?,?,?,?,'published',?) ON CONFLICT(community_id,watchlist_id) DO UPDATE SET audience_id=excluded.audience_id,status='published',shared_at_utc=excluded.shared_at_utc,removed_at_utc=NULL`).run(id,input.communityId,input.watchlistId,owner.owner_user_id,input.audienceId,input.atUtc);this.queueDestinations(input.communityId,"watchlist",input.watchlistId,"watchlists",input.atUtc);}); return id;
  }

  private queueDestinations(communityId:string,objectType:"alert"|"watchlist"|"coach"|"plan",objectId:string,contentType:"alerts"|"watchlists"|"coaching",atUtc:string):void {
    const destinations=this.database.prepare(`SELECT destination_id FROM traderlink_community_discord_destinations WHERE community_id=? AND content_type=? AND status='active'`).all(communityId,contentType) as {destination_id:string}[];
    const insert=this.database.prepare(`INSERT INTO traderlink_community_content_deliveries(delivery_id,community_id,object_type,object_id,destination_id,status,attempt_count,last_error,requested_at_utc,delivered_at_utc,updated_at_utc) VALUES(?,?,?,?,?,'pending',0,NULL,?,NULL,?)`);
    for(const destination of destinations)insert.run(createCanonicalUuidV4(),communityId,objectType,objectId,destination.destination_id,atUtc,atUtc);
  }

  saveDiscordDestination(input:Readonly<{communityId:string;actor:BaseViewer;name:string;discordChannelId:string;contentType:"alerts"|"watchlists"|"coaching"|"general";atUtc:string}>):string {
    this.requireCapability(input.communityId,input.actor,"community.discord.manage"); if(!SNOWFLAKE.test(input.discordChannelId))platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"discordChannelId"});assertCanonicalUtcTimestamp(input.atUtc,"atUtc");const existing=this.database.prepare(`SELECT destination_id FROM traderlink_community_discord_destinations WHERE community_id=? AND discord_channel_id=? AND content_type=?`).get(input.communityId,input.discordChannelId,input.contentType) as {destination_id:string}|undefined;const id=existing?.destination_id??createCanonicalUuidV4();this.database.prepare(`INSERT INTO traderlink_community_discord_destinations(destination_id,community_id,name,discord_channel_id,content_type,status,updated_by_user_id,created_at_utc,updated_at_utc) VALUES(?,?,?,?,?,'active',?,?,?) ON CONFLICT(community_id,discord_channel_id,content_type) DO UPDATE SET name=excluded.name,status='active',updated_by_user_id=excluded.updated_by_user_id,updated_at_utc=excluded.updated_at_utc`).run(id,input.communityId,text(input.name,80,"name"),input.discordChannelId,input.contentType,input.actor.userId,input.atUtc,input.atUtc);return id;
  }

  updateSettings(input:Readonly<{communityId:string;actor:BaseViewer;displayName:string;description:string;retentionDays:number;visibilityStatus:"not_configured"|"active"|"declined";visibilityCopy:string;atUtc:string}>):void {
    this.requireCapability(input.communityId,input.actor,"community.manage");assertCanonicalUtcTimestamp(input.atUtc,"atUtc");if(!Number.isInteger(input.retentionDays)||input.retentionDays<7||input.retentionDays>730)platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"retentionDays"});this.write(()=>{this.database.prepare(`UPDATE traderlink_communities SET display_name=?,updated_at_utc=? WHERE community_id=?`).run(text(input.displayName,120,"displayName"),input.atUtc,input.communityId);this.database.prepare(`INSERT INTO traderlink_community_settings(community_id,description,named_activity_retention_days,visibility_status,visibility_copy,updated_at_utc) VALUES(?,?,?,?,?,?) ON CONFLICT(community_id) DO UPDATE SET description=excluded.description,named_activity_retention_days=excluded.named_activity_retention_days,visibility_status=excluded.visibility_status,visibility_copy=excluded.visibility_copy,updated_at_utc=excluded.updated_at_utc`).run(input.communityId,text(input.description,1000,"description",false),input.retentionDays,input.visibilityStatus,text(input.visibilityCopy,1000,"visibilityCopy",false),input.atUtc);});
  }

  upsertCoach(input: Readonly<{ communityId:string; actor:BaseViewer; userId:string; displayName:string; headline:string; biography:string; deliverySummary:string; capacity:number; active:boolean; atUtc:string }>): string {
    const access=this.requireCapability(input.communityId,input.actor,"community.coaching.offer"); assertCanonicalUuidV4(input.userId,"userId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    if(input.userId!==input.actor.userId&&!access.capabilities.includes("community.coaching.manage_all")) platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"manage_other_coach"});
    if(!Number.isInteger(input.capacity)||input.capacity<1||input.capacity>10000) platformFailure("TRADERLINK_PLATFORM_STORAGE_VALIDATION_FAILED",{field:"capacity"});
    const existing=this.database.prepare(`SELECT coach_profile_id FROM traderlink_community_coach_profiles WHERE community_id=? AND user_id=?`).get(input.communityId,input.userId) as {coach_profile_id:string}|undefined; const id=existing?.coach_profile_id??createCanonicalUuidV4();
    const coachSlug=slug(input.displayName,"displayName"); this.database.prepare(`INSERT INTO traderlink_community_coach_profiles(coach_profile_id,community_id,user_id,coach_slug,display_name,headline,biography,delivery_summary,capacity,status,created_at_utc,updated_at_utc) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(community_id,user_id) DO UPDATE SET display_name=excluded.display_name,headline=excluded.headline,biography=excluded.biography,delivery_summary=excluded.delivery_summary,capacity=excluded.capacity,status=excluded.status,updated_at_utc=excluded.updated_at_utc`).run(id,input.communityId,input.userId,coachSlug,text(input.displayName,100,"displayName"),text(input.headline,180,"headline",false),text(input.biography,4000,"biography",false),text(input.deliverySummary,1000,"deliverySummary",false),input.capacity,input.active?"active":"draft",input.atUtc,input.atUtc); return id;
  }

  createPlan(input: Readonly<{communityId:string;actor:BaseViewer;coachProfileId:string;name:string;description:string;cadence:"weekly"|"monthly"|"trade_reviews"|"custom";tradeReviewLimit?:number;priceLabel:string;paymentInstructions:string;audienceId:string;publish:boolean;atUtc:string}>): string {
    this.requireCapability(input.communityId,input.actor,"community.coaching.offer"); assertCanonicalUuidV4(input.coachProfileId,"coachProfileId"); assertCanonicalUuidV4(input.audienceId,"audienceId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc");
    const coach=this.database.prepare(`SELECT user_id FROM traderlink_community_coach_profiles WHERE coach_profile_id=? AND community_id=?`).get(input.coachProfileId,input.communityId) as {user_id:string}|undefined; const access=this.permissions.resolveAccess(input.communityId,input.actor.userId); if(!coach||(coach.user_id!==input.actor.userId&&!access.capabilities.includes("community.coaching.manage_all"))) platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"create_coaching_plan"});
    const id=createCanonicalUuidV4(); this.write(()=>{this.database.prepare(`INSERT INTO traderlink_community_coaching_plans(plan_id,coach_profile_id,community_id,name,description,cadence,trade_review_limit,price_label,payment_instructions,audience_id,status,created_at_utc,updated_at_utc) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,input.coachProfileId,input.communityId,text(input.name,100,"name"),text(input.description,4000,"description",false),input.cadence,input.tradeReviewLimit??null,text(input.priceLabel,80,"priceLabel",false),text(input.paymentInstructions,1000,"paymentInstructions",false),input.audienceId,input.publish?"active":"draft",input.atUtc,input.atUtc);if(input.publish)this.queueDestinations(input.communityId,"plan",id,"coaching",input.atUtc);}); return id;
  }

  requestCoaching(input:Readonly<{communityId:string;actor:BaseViewer;planId:string;atUtc:string}>):string { this.requireCapability(input.communityId,input.actor,"community.view"); assertCanonicalUuidV4(input.planId,"planId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc"); const plan=this.database.prepare(`SELECT p.coach_profile_id,c.user_id,c.capacity,(SELECT count(*) FROM traderlink_community_coaching_relationships r WHERE r.coach_profile_id=c.coach_profile_id AND r.status='active') active_count FROM traderlink_community_coaching_plans p JOIN traderlink_community_coach_profiles c ON c.coach_profile_id=p.coach_profile_id WHERE p.plan_id=? AND p.community_id=? AND p.status='active' AND c.status='active'`).get(input.planId,input.communityId) as {coach_profile_id:string;user_id:string;capacity:number;active_count:number}|undefined; if(!plan||plan.user_id===input.actor.userId||plan.active_count>=plan.capacity) platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"request_coaching"}); const id=createCanonicalUuidV4(); this.database.prepare(`INSERT INTO traderlink_community_coaching_relationships(relationship_id,community_id,coach_profile_id,coach_user_id,student_user_id,plan_id,status,requested_at_utc,started_at_utc,ended_at_utc) VALUES(?,?,?,?,?,?,'pending',?,NULL,NULL)`).run(id,input.communityId,plan.coach_profile_id,plan.user_id,input.actor.userId,input.planId,input.atUtc); return id; }

  setRelationshipStatus(input:Readonly<{communityId:string;actor:BaseViewer;relationshipId:string;status:"active"|"declined"|"ended";atUtc:string}>):void { this.requireCapability(input.communityId,input.actor,"community.coaching.students"); assertCanonicalUuidV4(input.relationshipId,"relationshipId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc"); const row=this.database.prepare(`SELECT coach_user_id FROM traderlink_community_coaching_relationships WHERE relationship_id=? AND community_id=?`).get(input.relationshipId,input.communityId) as {coach_user_id:string}|undefined; const access=this.permissions.resolveAccess(input.communityId,input.actor.userId); if(!row||(row.coach_user_id!==input.actor.userId&&!access.capabilities.includes("community.coaching.manage_all"))) platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"manage_coaching_relationship"}); this.database.prepare(`UPDATE traderlink_community_coaching_relationships SET status=?,started_at_utc=CASE WHEN ?='active' THEN coalesce(started_at_utc,?) ELSE started_at_utc END,ended_at_utc=CASE WHEN ? IN ('declined','ended') THEN ? ELSE NULL END WHERE relationship_id=?`).run(input.status,input.status,input.atUtc,input.status,input.atUtc,input.relationshipId); }

  grantJournal(input:Readonly<{communityId:string;actor:BaseViewer;relationshipId:string;journalAccountId:string;dataScope:"summary"|"trades"|"journal"|"analytics"|"complete";atUtc:string}>):string { assertCanonicalUuidV4(input.relationshipId,"relationshipId"); assertCanonicalUuidV4(input.journalAccountId,"journalAccountId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc"); const row=this.database.prepare(`SELECT coach_user_id,student_user_id,status FROM traderlink_community_coaching_relationships WHERE relationship_id=? AND community_id=?`).get(input.relationshipId,input.communityId) as {coach_user_id:string;student_user_id:string;status:string}|undefined; if(!row||row.student_user_id!==input.actor.userId||row.status!=="active") platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"grant_coach_journal_access"}); const id=createCanonicalUuidV4(); this.database.prepare(`INSERT INTO traderlink_community_journal_grants(grant_id,relationship_id,community_id,coach_user_id,student_user_id,journal_account_id,data_scope,status,granted_at_utc,revoked_at_utc) VALUES(?,?,?,?,?,?,?,'active',?,NULL) ON CONFLICT(relationship_id,journal_account_id,data_scope) DO UPDATE SET status='active',granted_at_utc=excluded.granted_at_utc,revoked_at_utc=NULL`).run(id,input.relationshipId,input.communityId,row.coach_user_id,row.student_user_id,input.journalAccountId,input.dataScope,input.atUtc); return id; }

  revokeJournal(input:Readonly<{actorUserId:string;grantId:string;atUtc:string}>):void { assertCanonicalUuidV4(input.grantId,"grantId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc"); const result=this.database.prepare(`UPDATE traderlink_community_journal_grants SET status='revoked',revoked_at_utc=? WHERE grant_id=? AND student_user_id=? AND status='active'`).run(input.atUtc,input.grantId,input.actorUserId); if(result.changes!==1) platformFailure("TRADERLINK_WORKSPACE_ACCESS_DENIED",{operation:"revoke_coach_journal_access"}); }

  recordView(input:Readonly<{communityId:string;userId:string;path:string;objectType:string;objectId?:string;atUtc:string}>):void { assertCanonicalUuidV4(input.communityId,"communityId"); assertCanonicalUuidV4(input.userId,"userId"); assertCanonicalUtcTimestamp(input.atUtc,"atUtc"); const path=text(input.path,500,"path");this.write(()=>{this.database.prepare(`INSERT INTO traderlink_community_activity_events(event_id,community_id,user_id,event_type,object_type,object_id,path,occurred_at_utc) VALUES(?,?,?,'page.view',?,?,?,?)`).run(createCanonicalUuidV4(),input.communityId,input.userId,text(input.objectType,40,"objectType"),input.objectId??null,path,input.atUtc);this.database.prepare(`INSERT INTO traderlink_community_activity_daily_members(community_id,activity_day,path,user_id,views,first_viewed_at_utc,last_viewed_at_utc) VALUES(?,?,?,?,1,?,?) ON CONFLICT(community_id,activity_day,path,user_id) DO UPDATE SET views=views+1,last_viewed_at_utc=excluded.last_viewed_at_utc`).run(input.communityId,input.atUtc.slice(0,10),path,input.userId,input.atUtc,input.atUtc);const retention=(this.database.prepare(`SELECT named_activity_retention_days days FROM traderlink_community_settings WHERE community_id=?`).get(input.communityId) as {days:number}|undefined)?.days??90;const cutoff=new Date(new Date(input.atUtc).getTime()-retention*86400000).toISOString();this.database.prepare(`DELETE FROM traderlink_community_activity_events WHERE community_id=? AND occurred_at_utc<?`).run(input.communityId,cutoff);}); }

  readSnapshot(communitySlug:string,viewer:BaseViewer):TraderLinkCommunityDashboardSnapshot {
    const community=this.database.prepare(`SELECT community_id,discord_guild_id,slug,display_name,status,owner_user_id FROM traderlink_communities WHERE slug=?`).get(communitySlug) as {community_id:string;discord_guild_id:string;slug:string;display_name:string;status:"setup"|"active"|"paused"|"suspended";owner_user_id:string}|undefined;
    if(!community) platformFailure("TRADERLINK_WORKSPACE_NOT_FOUND",{resource:"community"}); const access=this.requireCapability(community.community_id,viewer,"community.view");
    const audienceRows=this.database.prepare(`SELECT a.audience_id,a.community_id,a.name,a.mode,a.status,coalesce(json_group_array(r.discord_role_id) FILTER(WHERE r.discord_role_id IS NOT NULL),'[]') role_ids FROM traderlink_community_audiences a LEFT JOIN traderlink_community_audience_discord_roles r ON r.audience_id=a.audience_id WHERE a.community_id=? GROUP BY a.audience_id ORDER BY a.name`).all(community.community_id) as any[];
    const audiences:TraderLinkCommunityAudience[]=audienceRows.map(r=>({audienceId:r.audience_id,communityId:r.community_id,name:r.name,mode:r.mode,discordRoleIds:parseJsonStrings(r.role_ids),status:r.status}));
    const allowed=new Set(audiences.filter(a=>a.status==="active"&&(a.mode==="everyone"||a.discordRoleIds.some(id=>viewer.discordRoleIds.includes(id)))).map(a=>a.audienceId)); if(access.isOwner) audiences.forEach(a=>allowed.add(a.audienceId));
    const alerts=(this.database.prepare(`SELECT a.*,u.display_name author_name FROM traderlink_community_alerts a JOIN platform_users u ON u.user_id=a.author_user_id WHERE a.community_id=? AND a.status='published' ORDER BY a.published_at_utc DESC LIMIT 100`).all(community.community_id) as any[]).filter(r=>allowed.has(r.audience_id)).map((r):TraderLinkCommunityAlert=>({alertId:r.alert_id,communityId:r.community_id,slug:r.slug,authorUserId:r.author_user_id,authorName:r.author_name,title:r.title,symbol:r.symbol,body:r.body,status:r.status,audienceId:r.audience_id,publishedAtUtc:r.published_at_utc,createdAtUtc:r.created_at_utc,updatedAtUtc:r.updated_at_utc}));
    const watchlists=(this.database.prepare(`SELECT p.*,w.title,u.display_name author_name FROM traderlink_community_watchlist_placements p JOIN community_watchlists w ON w.watchlist_id=p.watchlist_id JOIN platform_users u ON u.user_id=p.author_user_id WHERE p.community_id=? AND p.status='published' ORDER BY p.shared_at_utc DESC LIMIT 100`).all(community.community_id) as any[]).filter(r=>allowed.has(r.audience_id)).map((r):TraderLinkCommunityWatchlistPlacement=>({placementId:r.placement_id,communityId:r.community_id,watchlistId:r.watchlist_id,authorUserId:r.author_user_id,authorName:r.author_name,title:r.title,audienceId:r.audience_id,status:r.status,sharedAtUtc:r.shared_at_utc}));
    const coaches=(this.database.prepare(`SELECT c.*,(SELECT count(*) FROM traderlink_community_coaching_relationships r WHERE r.coach_profile_id=c.coach_profile_id AND r.status='active') active_students FROM traderlink_community_coach_profiles c WHERE c.community_id=? AND c.status IN ('active','paused') ORDER BY c.display_name`).all(community.community_id) as any[]).map((r):TraderLinkCommunityCoach=>({coachProfileId:r.coach_profile_id,slug:r.coach_slug,communityId:r.community_id,userId:r.user_id,displayName:r.display_name,headline:r.headline,biography:r.biography,deliverySummary:r.delivery_summary,capacity:r.capacity,activeStudents:r.active_students,status:r.status}));
    const plans=(this.database.prepare(`SELECT * FROM traderlink_community_coaching_plans WHERE community_id=? AND status='active' ORDER BY name`).all(community.community_id) as any[]).filter(r=>allowed.has(r.audience_id)).map((r):TraderLinkCommunityCoachingPlan=>({planId:r.plan_id,coachProfileId:r.coach_profile_id,communityId:r.community_id,name:r.name,description:r.description,cadence:r.cadence,tradeReviewLimit:r.trade_review_limit,priceLabel:r.price_label,paymentInstructions:r.payment_instructions,audienceId:r.audience_id,status:r.status}));
    const relationships=(this.database.prepare(`SELECT * FROM traderlink_community_coaching_relationships WHERE community_id=? AND (coach_user_id=? OR student_user_id=?) ORDER BY requested_at_utc DESC`).all(community.community_id,viewer.userId,viewer.userId) as any[]).map((r):TraderLinkCommunityRelationship=>({relationshipId:r.relationship_id,communityId:r.community_id,coachProfileId:r.coach_profile_id,coachUserId:r.coach_user_id,studentUserId:r.student_user_id,planId:r.plan_id,status:r.status,startedAtUtc:r.started_at_utc,endedAtUtc:r.ended_at_utc}));
    const relationshipIds=new Set(relationships.map(r=>r.relationshipId)); const grants=(this.database.prepare(`SELECT * FROM traderlink_community_journal_grants WHERE community_id=? AND (coach_user_id=? OR student_user_id=?) ORDER BY granted_at_utc DESC`).all(community.community_id,viewer.userId,viewer.userId) as any[]).filter(r=>relationshipIds.has(r.relationship_id)).map((r):TraderLinkCommunityJournalGrant=>({grantId:r.grant_id,relationshipId:r.relationship_id,communityId:r.community_id,coachUserId:r.coach_user_id,studentUserId:r.student_user_id,journalAccountId:r.journal_account_id,dataScope:r.data_scope,status:r.status,grantedAtUtc:r.granted_at_utc,revokedAtUtc:r.revoked_at_utc}));
    const canMembers=access.capabilities.includes("community.members.view"); const memberRows=canMembers?this.database.prepare(`SELECT m.user_id,u.display_name,m.status,m.discord_verified_at_utc,(SELECT max(e.occurred_at_utc) FROM traderlink_community_activity_events e WHERE e.community_id=m.community_id AND e.user_id=m.user_id) last_active,coalesce((SELECT json_group_array(r.name) FROM traderlink_community_member_role_assignments x JOIN traderlink_community_roles r ON r.role_id=x.role_id WHERE x.community_id=m.community_id AND x.user_id=m.user_id AND x.status='active'),'[]') roles FROM traderlink_community_memberships m JOIN platform_users u ON u.user_id=m.user_id WHERE m.community_id=? ORDER BY u.display_name`).all(community.community_id) as any[]:[];
    const members:TraderLinkCommunityMemberSummary[]=memberRows.map(r=>({userId:r.user_id,displayName:r.display_name,membershipStatus:r.status,lastVerifiedAtUtc:r.discord_verified_at_utc,lastActiveAtUtc:r.last_active,roles:parseJsonStrings(r.roles),capabilities:this.permissions.resolveAccess(community.community_id,r.user_id).capabilities}));
    const staffRoles=access.capabilities.includes("community.roles.manage")?(this.database.prepare(`SELECT r.role_id,r.name,coalesce((SELECT json_group_array(c.capability_key) FROM traderlink_community_role_capabilities c WHERE c.role_id=r.role_id),'[]') capabilities,coalesce((SELECT json_group_array(m.discord_role_id) FROM traderlink_community_discord_role_mappings m WHERE m.role_id=r.role_id AND m.status='active'),'[]') discord_roles FROM traderlink_community_roles r WHERE r.community_id=? AND r.status='active' ORDER BY r.name`).all(community.community_id) as any[]).map(r=>({roleId:r.role_id,name:r.name,capabilities:parseJsonStrings(r.capabilities) as readonly TraderLinkCommunityCapability[],discordRoleIds:parseJsonStrings(r.discord_roles)})):[];
    const channels=(access.capabilities.includes("community.discord.manage")?(this.database.prepare(`SELECT * FROM traderlink_community_discord_destinations WHERE community_id=? ORDER BY content_type,name`).all(community.community_id) as any[]):[]).map((r):TraderLinkCommunityChannel=>({destinationId:r.destination_id,communityId:r.community_id,name:r.name,discordChannelId:r.discord_channel_id,contentType:r.content_type,status:r.status}));
    const cutoff=new Date(Date.now()-30*86400000).toISOString().slice(0,10); const analyticsRow=access.capabilities.includes("community.analytics.view")?this.database.prepare(`SELECT coalesce(sum(views),0) views,count(DISTINCT user_id) users,coalesce(sum(CASE WHEN path LIKE '%/alerts%' THEN views ELSE 0 END),0) alert_views,coalesce(sum(CASE WHEN path LIKE '%/watchlists%' THEN views ELSE 0 END),0) watchlist_views,coalesce(sum(CASE WHEN path LIKE '%/coach%' THEN views ELSE 0 END),0) coaching_views FROM traderlink_community_activity_daily_members WHERE community_id=? AND activity_day>=?`).get(community.community_id,cutoff) as any:null; const topPages=access.capabilities.includes("community.analytics.view")?(this.database.prepare(`SELECT path,sum(views) views,count(DISTINCT user_id) users FROM traderlink_community_activity_daily_members WHERE community_id=? AND activity_day>=? GROUP BY path ORDER BY views DESC LIMIT 10`).all(community.community_id,cutoff) as any[]).map(r=>({path:r.path,views:r.views,uniqueMembers:r.users})):[];
    const referral=access.capabilities.includes("community.referrals.view")?this.database.prepare(`SELECT count(DISTINCT a.attribution_id) attributed,sum(CASE WHEN a.status='converted' THEN 1 ELSE 0 END) converted,coalesce(sum(e.commission_minor),0) earnings,max(p.currency) currency,max(p.commission_basis_points) bps,max(p.status) program_status FROM traderlink_community_partner_programs p LEFT JOIN traderlink_community_partner_attributions a ON a.community_id=p.community_id LEFT JOIN traderlink_community_partner_earnings e ON e.attribution_id=a.attribution_id AND e.status IN ('estimated','approved','paid') WHERE p.community_id=?`).get(community.community_id) as any:null;
    const count=(this.database.prepare(`SELECT count(*) count FROM traderlink_community_memberships WHERE community_id=? AND status='active'`).get(community.community_id) as {count:number}).count;
    return Object.freeze({community:{communityId:community.community_id,discordGuildId:community.discord_guild_id,slug:community.slug,displayName:community.display_name,status:community.status,isOwner:access.isOwner,memberCount:count},viewer:{...viewer,capabilities:access.capabilities},alerts:Object.freeze(alerts),watchlists:Object.freeze(watchlists),coaches:Object.freeze(coaches),plans:Object.freeze(plans),relationships:Object.freeze(relationships),journalGrants:Object.freeze(grants),audiences:Object.freeze(audiences),channels:Object.freeze(channels),members:Object.freeze(members),staffRoles:Object.freeze(staffRoles),analytics:{views30Days:analyticsRow?.views??0,uniqueMembers30Days:analyticsRow?.users??0,alertViews30Days:analyticsRow?.alert_views??0,watchlistViews30Days:analyticsRow?.watchlist_views??0,coachingViews30Days:analyticsRow?.coaching_views??0,topPages:Object.freeze(topPages)},referrals:{attributedMembers:referral?.attributed??0,tier2Members:referral?.converted??0,estimatedEarningsMinor:referral?.earnings??0,currency:referral?.currency??"USD",commissionLabel:referral?.program_status==="active"&&referral?.bps!=null?`${referral.bps/100}%`:"Not configured"}});
  }
}
