import AdminPanelSettingsRoundedIcon from "@mui/icons-material/AdminPanelSettingsRounded";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Grid from "@mui/material/Grid";
import MenuItem from "@mui/material/MenuItem";
import Stack from "@mui/material/Stack";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";
import Link from "next/link";

import { DashboardMetricCard, DashboardPage, DashboardPanel } from "@/app/dashboard-ui";
import { requireTraderLinkPlatformServerComponentPageIdentity } from "@/src/modules/platform/server/authentication/require-platform-request-scope";
import { withReadonlyPlatformDatabase } from "@/src/modules/platform/server/database/open-readonly-platform-database";
import { configureCommunityCoachFeeAction, configureCommunityPartnerAction, setCommunityStatusAction } from "./admin-actions";

type Row={communityId:string;slug:string;name:string;status:string;members:number;coaches:number;alerts:number};
type Snapshot={authorized:boolean;communities:number;active:number;members:number;alerts:number;watchlists:number;pending:number;earnings:number;rows:readonly Row[]};

export default async function CommunitiesAdminPage(){
  const identity=await requireTraderLinkPlatformServerComponentPageIdentity();
  const reviewAvailable=process.env.NODE_ENV!=="production"||process.env.RAILWAY_ENVIRONMENT_NAME==="staging";
  const data=withReadonlyPlatformDatabase({},database=>{
    const authorized=identity.mode==="local_development"||Boolean(database.prepare(`SELECT 1 FROM traderlink_community_operator_grants WHERE user_id=? AND status='active'`).get(identity.scope.userId));
    if(!authorized)return {authorized:false,communities:0,active:0,members:0,alerts:0,watchlists:0,pending:0,earnings:0,rows:[]};
    const total=database.prepare(`SELECT (SELECT count(*) FROM traderlink_communities) communities,(SELECT count(*) FROM traderlink_communities WHERE status='active') active,(SELECT count(*) FROM traderlink_community_memberships WHERE status='active') members,(SELECT count(*) FROM traderlink_community_alerts WHERE status='published') alerts,(SELECT count(*) FROM traderlink_community_watchlist_placements WHERE status='published') watchlists,(SELECT count(*) FROM traderlink_community_content_deliveries WHERE status IN ('pending','sending','failed')) pending,(SELECT coalesce(sum(commission_minor),0) FROM traderlink_community_partner_earnings WHERE status IN ('estimated','approved','paid')) earnings`).get() as Omit<Snapshot,"authorized"|"rows">;
    const rows=database.prepare(`SELECT c.community_id communityId,c.slug,c.display_name name,c.status,(SELECT count(*) FROM traderlink_community_memberships m WHERE m.community_id=c.community_id AND m.status='active') members,(SELECT count(*) FROM traderlink_community_coach_profiles p WHERE p.community_id=c.community_id AND p.status='active') coaches,(SELECT count(*) FROM traderlink_community_alerts a WHERE a.community_id=c.community_id AND a.status='published') alerts FROM traderlink_communities c ORDER BY c.updated_at_utc DESC`).all() as Row[];
    return {authorized:true,...total,rows};
  }) as Snapshot;
  return <DashboardPage>
    <Stack direction={{xs:"column",md:"row"}} spacing={2} sx={{alignItems:{md:"center"},justifyContent:"space-between"}}><Stack direction="row" spacing={1} sx={{alignItems:"center"}}><AdminPanelSettingsRoundedIcon color="primary"/><Typography component="h1" variant="h1">Communities Administration</Typography></Stack>{reviewAvailable?<Button component={Link} href="/communities/review/manage" variant="outlined">Open complete dashboard review</Button>:null}</Stack>
    {data.authorized?<><Grid container spacing={2}><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption={`${data.active} active`} label="Communities" value={String(data.communities)}/></Grid><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption="Verified server memberships" label="Members" value={data.members.toLocaleString()}/></Grid><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption={`${data.alerts} alerts · ${data.watchlists} watchlists`} label="Published content" value={String(data.alerts+data.watchlists)}/></Grid><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption="Configured partner programs" label="Estimated earnings" value={new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(data.earnings/100)}/></Grid></Grid>
      <DashboardPanel title="Connected Discord servers"><Stack spacing={1.5}>{data.rows.length?data.rows.map(row=><Stack direction={{xs:"column",md:"row"}} key={row.slug} sx={{alignItems:{md:"center"},border:1,borderColor:"divider",borderRadius:2,justifyContent:"space-between",p:2}}><Box><Typography style={{fontWeight:800}}>{row.name}</Typography><Typography color="text.secondary" variant="caption">{row.members} members · {row.coaches} coaches · {row.alerts} alerts · {row.status}</Typography></Box><Button component={Link} href={`/communities/${row.slug}/manage`} size="small">Inspect</Button></Stack>):<Typography color="text.secondary">No Discord servers have been connected.</Typography>}</Stack></DashboardPanel>
      <Grid container spacing={2}><Grid size={{xs:12,lg:6}}><DashboardPanel title="Tier 2 partner terms"><form action={configureCommunityPartnerAction}><Stack spacing={2}><CommunitySelect name="communityId" rows={data.rows}/><TextField defaultValue="disabled" label="Status" name="status" select><MenuItem value="disabled">Disabled</MenuItem><MenuItem value="active">Active</MenuItem><MenuItem value="paused">Paused</MenuItem></TextField><TextField helperText="Leave blank while terms are undecided." label="Commission percent" name="commissionPercent" type="number"/><TextField defaultValue={90} label="Attribution window in days" name="attributionDays" type="number"/><TextField defaultValue="USD" label="Currency" name="currency"/><Button disabled={!data.rows.length} type="submit" variant="contained">Save partner terms</Button></Stack></form></DashboardPanel></Grid><Grid size={{xs:12,lg:6}}><DashboardPanel title="Optional future coach fee"><form action={configureCommunityCoachFeeAction}><Stack spacing={2}><CommunitySelect name="communityId" rows={data.rows}/><TextField label="Specific coach user ID (optional)" name="coachUserId"/><TextField label="Fee percent" name="feePercent" type="number" required/><TextField defaultValue="disabled" label="Status" name="status" select><MenuItem value="disabled">Disabled</MenuItem><MenuItem value="active">Active</MenuItem></TextField><TextField label="Internal notes" minRows={2} multiline name="notes"/><Button disabled={!data.rows.length} type="submit" variant="contained">Save fee rule</Button><Typography color="text.secondary" variant="caption">No launch coaching payment is processed by TraderLink. This records configuration for a future compatible provider.</Typography></Stack></form></DashboardPanel></Grid></Grid>
      <Grid container spacing={2}><Grid size={{xs:12,md:6}}><DashboardPanel title="Server status"><form action={setCommunityStatusAction}><Stack spacing={2}><CommunitySelect name="communityId" rows={data.rows}/><TextField defaultValue="active" label="New status" name="status" select><MenuItem value="active">Active</MenuItem><MenuItem value="paused">Paused</MenuItem><MenuItem value="suspended">Suspended</MenuItem></TextField><Button disabled={!data.rows.length} type="submit" variant="contained">Update server</Button></Stack></form></DashboardPanel></Grid><Grid size={{xs:12,md:6}}><DashboardPanel title="Discord delivery queue"><Typography variant="h2">{data.pending}</Typography><Typography color="text.secondary" variant="body2">Pending, sending, or failed deliveries require attention.</Typography></DashboardPanel></Grid></Grid>
    </>:<DashboardPanel title="Operator access required"><Typography variant="body2">Real server, member, activity, coach, and earnings data requires an active Communities operator grant.{reviewAvailable?" Isolated review data remains available.":""}</Typography>{reviewAvailable?<Button component={Link} href="/communities/review/manage" sx={{mt:2}} variant="contained">Review owner dashboard</Button>:null}</DashboardPanel>}
  </DashboardPage>;
}

function CommunitySelect({name,rows}:{name:string;rows:readonly Row[]}){return <TextField label="Community" name={name} select required>{rows.map(row=><MenuItem key={row.communityId} value={row.communityId}>{row.name}</MenuItem>)}</TextField>}
