import { timingSafeEqual } from "node:crypto";

import { withPlatformDatabase } from "@/src/modules/platform/server/database/open-platform-database";
import { createCanonicalUtcTimestamp } from "@/src/modules/platform/server/database/platform-migration-contract";
import { TraderLinkCommunityAdminRepository } from "@/src/modules/communities/server/traderlink-community-admin-repository";

export const runtime="nodejs";export const dynamic="force-dynamic";
function authorized(request:Request){const secret=process.env.TRADERLINK_COMMUNITIES_BILLING_SYNC_SECRET?.trim();const supplied=request.headers.get("authorization");if(!secret||!supplied)return false;const expected=Buffer.from(`Bearer ${secret}`),actual=Buffer.from(supplied);return expected.length===actual.length&&timingSafeEqual(expected,actual);}
type EventBody={providerEventRef?:unknown;userId?:unknown;eventType?:unknown;periodKey?:unknown;grossMinor?:unknown;currency?:unknown;occurredAtUtc?:unknown};
export async function POST(request:Request):Promise<Response>{if(!authorized(request))return Response.json({ok:false},{status:401});let body:EventBody;try{body=await request.json() as EventBody;}catch{return Response.json({ok:false,reason:"invalid_json"},{status:400});}if(typeof body.providerEventRef!=="string"||typeof body.userId!=="string"||!(["tier2.started","tier2.renewed","tier2.refunded","tier2.ended"] as unknown[]).includes(body.eventType)||typeof body.periodKey!=="string"||typeof body.grossMinor!=="number"||typeof body.currency!=="string"||typeof body.occurredAtUtc!=="string")return Response.json({ok:false,reason:"invalid_event"},{status:400});try{const result=withPlatformDatabase({mode:"runtime"},database=>new TraderLinkCommunityAdminRepository(database).applyTier2BillingEvent({providerEventRef:body.providerEventRef as string,userId:body.userId as string,eventType:body.eventType as "tier2.started"|"tier2.renewed"|"tier2.refunded"|"tier2.ended",periodKey:body.periodKey as string,grossMinor:body.grossMinor as number,currency:body.currency as string,occurredAtUtc:body.occurredAtUtc as string,processedAtUtc:createCanonicalUtcTimestamp()}));return Response.json({ok:true,...result});}catch{return Response.json({ok:false},{status:400});}}
