import "server-only";

// Owner-authored text. No grammar, dates or trading facts have been rewritten.
// Trusted static markup only; never accept user/provider HTML into these sections.
export const SWING_TITLE = "CRML";
export const SWING_SECTIONS: readonly string[] = [
  "\n<p>This idea is based on the recent report that the U.S., Denmark and Greenland now have an agreement giving the U.S. permanent security access/control over certain security matters in Greenland and restricting hostile country strategic investments.</p>\n<p>CRML is a mining development company <strong>heavily focused on its Tanbreez project in Greenland.</strong> Tanbreez is considered <strong>one of the largest rare earth deposits</strong> outside of China.</p>\n<p>Although the news does not exactly directly related to CRML or rare earth minerals it is tied to rare earth minerals.</p>\n",
  "<h2>History of 2 previous runs:</h2>\n<h3>First run:</h3>\n<p><u>Sept 29 2025</u><br>CRML announces <strong>plans to increase ownership in Tanbreez from 42% to 92.5%</strong></p>\n<p><u>Oct 6 2025</u><br>Reuters reported the US was considering directly investing in CRML. At this time CRML ownership in Tanbreez was 42%</p>\n<p><u>From Oct 1st to Oct 14 2026</u><br>The stock <strong>ran from $6 to $32.</strong> As expected, they raised money during that run use towards their goal of increasing ownership in Tanbreez.</p>\n<h3>Second run:</h3>\n<p><u>Beginning of Jan 2026</u><br>Trump announces his interest for the USA to acquire/control Greenland.</p>\n<p><u>From Jan 1 to Jan 14 2026</u><br>The stock <strong>ran from $7 to $19 reaching a high of $21.86</strong> on Jan 26th. As expected CRML raised more money to use towards their goal of increasing ownership in Tanbreez.</p>\n<p><u>In April 2026</u><br>CRML increased it's ownership in Tanbreez to 92.5%. That is a 120% increase in their ownership from the 42% they owned during the 2 previous runs.</p>\n<p>The USA still has not invested in CRML. I assume the reason for that is because Trump turned his focus to aquiring and/or, as announced on Friday, a security agreement. This is speculative you can draw you own conclusions.</p>\n<p>Since its first run back in Oct 2025 has become a well know stock to major investors and retail investors.</p>",
  "<h2>My plan:</h2>\n<p><strong>Build position value of $10,000</strong>.</p>\n<p>As usual I plan on <strong>scaling in and Scaling out.</strong></p>\n<p>Right now the tricky part is it is up 20% since Fridays news was dropped so as always in these circumstances nobody knows what will happen next...will it continue to increase or will it see a decent pullback? - nobody knows. Pullback would be great and so would a break of 8.56. Right now its currentl price of $8.12 needs to clear though resistance which is why I would like to see the $8.56 break.</p>\n",
  "<h2>Key levels (zones)</h2>\n<p>Pullback: <strong>$7.20 - $7.50.</strong></p>\n<p>A drop below $7.20 is where i stop adding. A drop below $6.70 is where i start to get nervous. Under $6.50 I stop out. Because I will scale in carefully stopping out under 6.50 would be loss i can easily accept.</p>\n<p>If it doesn't pullback ($7.20 - $7.50) I would like to see a break above $8.56 and for it to hold above at least $8.00 after the break.</p>\n<p>Basically I will buy $7.20 and above, ideally if it breaks $8.56 theres some shallow pullback for some adds.</p>\n<hr ><h3>First Target Zone:</h3><p>$10.00 - $10.50</p>\n<h3>Second Target Zone:</h3><p>$13 - $14</p>\n<h3>Third Target Zone:</h3><p>$18 - $21 (last run highs). But I will likely unload some $17 - $18 possible $16.</p>"
];
