/** Owner-only guide: rendered in Swing Trade Plans, not the member Help index. */
export const SWING_PLAN_OWNER_HELP = [
  {title:'Unsent comment warning',text:'The warning clears for a comment when you restore its published default or successfully send that exact text. Failed or unconfirmed posts keep the warning. Retrying an older saved message does not discard a different new comment.'},
  {title:'Write and preview a plan',text:'Start a new plan or open a saved one. Add your thesis, research, entry and exit plan, key levels and risks. You can rename, reorder, hide or remove sections, and add your own. Blank and hidden sections do not appear to members. Select text to apply bold, italic, underline or a link; use the preview to see the member page.'},
  {title:'Company details',text:'Fetch company details to review the latest available profile. Use these details replaces the company fields in your draft only. You can correct the fields yourself or continue without a profile.'},
  {title:'Save versus publish',text:'Save draft keeps your work private. Publish plan updates the page Premium members can see. Neither action sends a Discord post. Publishing a later version keeps the same page link. Save and close stores your draft before closing the editor.'},
  {title:'Public preview',text:'The locked-page headline and public embed text are visible to everyone. Keep the ticker, company identity and private research out of these fields. The Premium page preview shows the research; the locked preview shows what visitors without Premium access see.'},
  {title:'Send a Discord post',text:'After publishing, choose the Premium or Free channel and preview the post. Posting and delivery checks remain available while you edit a newer draft; they use the published version, not draft changes. Premium posts include the ticker. If the saved Premium comment is blank, the visible built-in thesis section supplies the comment even if renamed; a hidden or removed thesis does not. Free posts use only your custom comment and the link. Both use the same public embed. Send each destination separately. You can adjust the message before sending.'},
  {title:'Updates and closed ideas',text:'Add a dated update or closing summary, then publish when ready. Change Idea status to Closed when the plan is finished, or Open to reopen it. Closing does not delete the research or its link. Sending an update to Discord is optional and always separate.'},
  {title:'Check a delivery',text:'Check delivery history shows saved delivery results without requiring a post comment. Typed comments are kept separately for each plan and channel while this editor page stays open, including when you publish, close the plan editor or switch plans. Leaving or reloading warns about local comment drafts. Use the saved post comment fields and Save draft for permanent reusable defaults. A successful post is not sent twice for the same published version and channel. Use Preview saved post for retry beside a failed delivery to resend that exact message, including an older version. Its link still opens the current published page. If delivery could not be confirmed, check Discord first, then record whether you found the post or want to allow a retry.'},
  {title:'View activity',text:'View activity opens the owner report. Choose a plan to see recorded page visits, known members and whether the full or locked page was available. Browser blocking, interrupted loads and missing network access can prevent a visit from being recorded; the report is not a guarantee of every visit.'},
] as const;
