import type { HelpGuide } from "./help-guide-types";

export const WATCHLIST_HELP_GUIDES: readonly HelpGuide[] = [{
  slug: "analysis", title: "Read Watchlist analysis",
  description: "Understand the posted price, setup areas and analysis updates.",
  sections: [{
    id: "analysis-cancellation", title: "Cancel analysis", summary: "Stop a pending analysis without changing the published read.",
    keywords: ["cancel", "generation", "Discord channels"],
    blocks: [{kind:"paragraph",text:"While an analysis is running, Watchlist Admin shows its elapsed time and Cancel analysis. Cancelling prevents that request from replacing the published analysis or starting a fallback request. You can manually refresh again. Work already processed by the provider may still be charged. The same automatic boundary request is paused until a manual refresh, a new published read or a runtime restart."}, {kind:"paragraph",text:"Approved Discord posts use the channel configured for their Watchlist category: Main and Top Regular, Post-Market and Overnight Watches, Swings, or General. Moving a ticker does not redirect a post already approved for delivery. Free Chat remains a separate choice."}],
  }, {
    id: "public-preview", title: "Open the Watchlist", summary: "Join and sign in to view the current Watchlist.",
    keywords: ["sign in", "Discord", "preview"],
    blocks: [{kind:"paragraph",text:"Visitors who are not signed in see a dated CNTB detail-page preview with options to join TradersLink Discord and sign in. The example is not live market data. Signed-in members with Watchlist access see the current Watchlist."}],
  }, {
    id: "x-posting", title: "Post to X", summary: "Choose which approved analyses to share publicly.",
    keywords: ["X", "Twitter", "Buffer", "caption"],
    blocks: [{kind:"paragraph",text:"Post to X opens an editable caption and delivery status. The counter follows X character rules, including links and emojis. Also post to X selects that draft for sharing after approval; automatic updates are not selected. You can share the published analysis later with Post to X. Images match the selected approved analysis. X failures never block Watchlist or Discord publication. Accepted by Buffer means delivery is pending; Posted to X confirms Buffer reports it sent. If delivery is uncertain, check Buffer before retrying to avoid duplicates."}],
  }, {
    id: "free-chat", title: "Free Chat", summary: "Choose which approved analyses to share to Free Chat.",
    keywords: ["Discord", "Free Chat", "sharing"],
    blocks: [{kind:"paragraph",text:"Owners can select Also post to Free Chat beside analysis approval. Free Chat on a ticker row opens Post to Free Chat for a later share of the published analysis, without repeating Watchlist, email or push notifications. The post tags everyone and includes the approved analysis images and Watchlist links. Automatically post analysis updates to Free Chat is off by default and applies only to future automatically published updates for that ticker. Manual refresh alone does not share a draft. Delivery status and sent time appear in these controls. A Free Chat failure does not undo or block normal approval."}],
  }, {
    id: "plan-access", title: "Plan access", summary: "List, ticker details and analysis can have different access.",
    keywords: ["plans", "membership", "locked", "analysis", "ticker details"],
    blocks: [{ kind: "paragraph", text: "The owner can include the main Watchlist, Ticker details and Trade analysis & preparation separately in any plan. If a feature is locked, its message links to public plans containing it. Ticker detail access also applies to archives and indicators. Analysis access includes the preparation card and its publication history. Private coaching or invitation offers do not appear in these upgrade results." }],
  }, {
    id: "setups", title: "TradersLink Analysis", summary: "Read the setup that fits your trading style.",
    keywords: ["watchlist", "pullback", "breakout", "failure", "posted price"],
    blocks: [{ kind: "paragraph", text: "In Watchlist Admin, each ticker keeps its review actions visible. The Premium-only ticker and Premium-only analysis checkboxes appear below the main action buttons. In Edit Discord post, select Save text to keep your changes after reloading or editing the same analysis. Ticker-only posts, analysis posts and moves keep separate drafts. A newly generated analysis starts with fresh post text. Reset to generated text removes your saved override. Saving does not send a notification. Expand More actions for Move, Posting, Settings, Diagnostics and removal controls. Premium-only ticker hides a ticker from free members on the list and locks its detail page. Access Premium opens the membership page. Turning this setting off restores normal ticker access; the independent Premium-only analysis setting remains unchanged. Neither toggle sends notifications. Previously shared URLs or images cannot be recalled. Some ticker analyses are reserved for Premium members. Free members can read a preview with prices concealed and use Access Premium to join. Other ticker cards remain available under their normal access settings. The owner can change Premium-only analysis separately for each ticker; this does not generate analysis or send a notification. The setting does not recall previously shared Discord or X images." }, { kind: "paragraph", text: "Watchlist posts highlight active stocks attracting volume and attention—they are not signals to rush into a trade. Wait for your setup and use the pullback, breakout, and failure levels. A break below the failure level invalidates the momentum idea. The posted price reflects the price at the time of analysis." },
      { kind: "paragraph", text: "General Watchlist contains stocks without a specific trading session or day-trade/swing-trade focus. Open a ticker for its available notes, analysis and levels. Each ticker has an Indicator card switch in Watchlist Admin. Turning it off hides the card and stops its indicator data requests; turning it on resumes scheduled updates. Analysis and other ticker features are unchanged. The old Trader Read card and lifecycle labels are retired. Private is an owner-only category in Watchlist Admin. Private tickers are not available to members, including Premium members, and cannot send member notifications or social posts. Notes and analysis can be prepared privately. Moving out of Private publishes as a normal new listing, without mentioning its private origin. The notify-users choice controls notifications. Public post time starts when published. Moving a previously public ticker into Private does not recall existing external posts. Owners can select General Watchlist when adding a ticker or use Move to List in either direction. Swings is a separate list for swing-trade ideas. Select Swings when adding a ticker or use Move to List to move tickers into or out of it. Choosing this list does not change how analysis is generated. Overnight Watches displays stocks selected ahead of the next trading session. Add or move tickers into Overnight Watches in Admin; dates there distinguish saved groups, while members see one Overnight Watches section. Existing assignments remain unchanged. Moving preserves notes, the approved analysis and original tracking time; it does not request an analysis or send notifications. Trader notes are written by the Watchlist owner. A ticker can be published with notes and no generated analysis. An analysis may be added later after owner review. An analysis can include shallow and deep pullback areas, breakout continuation, where price could go next, and a separate recovery setup. Not every section is available for every ticker. An omitted setup does not mean the remaining analysis was rejected. If no analysis is displayed, available support and resistance levels still provide price context." }],
  }, {
    id: "updates", title: "Price and analysis updates", summary: "Live data and a new analysis are separate updates.",
    keywords: ["live price", "analysis time", "refresh"],
    blocks: [{ kind: "paragraph", text: "Price and market data can continue updating while the published analysis remains unchanged. Green Live data: On means the feed is on; red Off means it is not live. When Off, the price note shows the last available price time in Eastern Time, not the post or page update time, and the delayed-price label is hidden. If the price time is unavailable, the card says so. Under the analysis title, Analysis posted shows the original published analysis time and reference price. Each Analysis updated line shows a later published analysis and its own time and reference price. Times are Eastern Time, without seconds. Unapproved drafts are not included. Where it could go next rows can be inserted above or below another row, moved up or down, or sorted by price while keeping each explanation with its price. New full-analysis drafts include the breakout level in that ordered path; you can still edit or remove it. Moving a ticker normally changes its list only. Select Move Discord post and notify users to announce its destination and notify opted-in members; source-category Discord posts are deleted after the new post is confirmed. Free Chat and X are unchanged. Move delivery details provides delivery and cleanup retry controls. An analysis update after a move keeps its original/update price context and identifies the new list. Potential Gain keeps the original Watchlist starting price; it does not restart when the analysis changes. Updated-analysis notifications identify automatic AI updates or approval by \"This Guy\" and compare the first published analysis price with the updated analysis price when both are available. That comparison is separate from Potential Gain. Automatic boundary-update Discord posts are text-only with links to the full analysis. Initial posts and manually approved updates keep their analysis images. The ticker-detail header also shows this saved price as Posted at beside the posted date. It is not the current price or a refreshed analysis price. When an overnight price is available on addition, Potential Path uses that fixed price for its levels and percentage distances. The Overnight price note shows when it was checked, not the last trade time. Fresh premarket prices resume normal updates and remove the note. Indicators retain their completed-session readings and original update time." }],
  }, {
    id: "indicators", title: "Indicators", summary: "Read current market conditions separately from the saved analysis.",
    keywords: ["EMA", "RSI", "VWAP", "ATR", "volume", "momentum", "timeframe", "Unavailable"],
    blocks: [{ kind: "paragraph", text: "The Indicators card summarizes 1m, 5m and 15m conditions together. Select 1m, 5m, 15m or Daily for details; the card starts on 5m and remembers your selection in this browser. Trend, momentum, RSI, moving averages, volume and ATR describe the selected timeframe. A dash means that particular indicator does not yet have enough usable data; it does not invalidate the others." },
      { kind: "paragraph", text: "Trend & moving averages combines the trend reading with EMA9/EMA20 prices and alignment. RSI & momentum combines current RSI strength, overbought/oversold conditions and whether momentum is increasing or easing. VWAP, Volume and ATR remain separate. Moving averages show bullish, bearish or mixed alignment. Volume describes trading activity, while ATR describes widening, narrowing or steady price swings; neither assigns a bullish or bearish direction. Click or tap the information button beside any indicator to read what it means and how it is calculated, even when its value is unavailable. Click it again, click outside the readings, or press Escape to close the explanation." },
      { kind: "paragraph", text: "Trend and Momentum use green, red or orange tags for their current state. RSI shows its number and a bullish, bearish or neutral momentum tag: upward price movement has the advantage above 50, downward movement below 50, and neither at 50. A separate orange Overbought tag appears above 70 or Oversold below 30. These describe stretched conditions, separately from momentum direction." },
      { kind: "paragraph", text: "EMA 9 and EMA 20 show shorter-term price direction. RSI describes momentum, including overbought or oversold conditions and whether it is rising or falling. Overbought is not an automatic sell signal, and oversold is not an automatic buy signal. A small indicator change does not by itself invalidate the analysis thesis." },
      { kind: "paragraph", text: "Volume and VWAP show Unavailable when the data needed for those readings is missing or unreliable. This does not mean no shares traded. Price-based indicators can still be shown when their candle data is usable." },
      { kind: "paragraph", text: "VWAP is shared across the tabs: today's volume-weighted average from completed one-minute candles, including extended hours, beginning with the market's premarket session. It resets each trading date and is not calculated from yesterday's warm-up candles. Its price comparison can change with the live price without requesting another analysis." },
      { kind: "paragraph", text: "Intraday volume compares completed bars within the same premarket, regular or postmarket session. Early in a session it shows available bar facts or a bar-to-bar comparison before a mature baseline exists. Daily volume compares completed trading days. ATR 14 uses Wilder smoothing to describe the selected timeframe's usual candle range and whether volatility is expanding or contracting; it is not a projected gain or a prescribed stop. Potential Path keeps its separate support/resistance and ATR logic." },
      { kind: "paragraph", text: "A shared refresh runs about every two minutes for active Watchlist tickers. Viewing the card or changing tabs does not create an AI request or a separate provider refresh. Last updated is the time through which completed candles were used, not the page-load time; VWAP has its own timestamp. A failed refresh can leave the last available values and their original timestamps in place. While the market is closed, unsuccessful timeframes can receive two delayed recovery attempts; successful timeframes stay cached." }],
  }],
}, {
  slug: "owner-review", title: "Review and publish Watchlist analysis",
  description: "Owner controls for drafts, approval, delivery and audit export.",
  sections: [{
    id: "approval", title: "Analysis Review", summary: "Review a saved analysis before publishing it.",
    keywords: ["owner", "admin", "approve", "draft", "Discord"],
    blocks: [{kind:"paragraph",text:"In AI Controls, choose Current analysis or Simple analysis, then save review controls. The selection applies to new requests only; existing drafts and published reads keep their format. Simple analysis focuses on the setup, pullbacks, where price could go next and thesis invalidation. It always requires owner approval when AI generation runs. Edit prices, ranges and text in the card, or uncheck Show this section to hide it. Saving does not publish or request another analysis."}, { kind: "steps", items: [
      { title: "Open the draft", text: "In Watchlist Admin, review status and View / edit analysis appear on eligible ticker rows automatically. That button opens the actual analysis card with inline section editors. The existing Analysis Review workflow in AI Controls also remains available. When review is required, the new post stays private while analysis is prepared and reviewed. A failed replacement leaves the previous saved version available; a storage error is not a successful save or publication." },
      { title: "Edit and save", text: "Expand Edit beside a card section to change text and prices, add or remove supported rows, include a missing setup, or hide/show a section. Save and close saves a separate edited version without publishing. Close warns before discarding unsaved edits. Editing does not request another AI analysis. Choose Approve and publish on the ticker row to publish the saved version, whether or not you edited it. Delivery details opens the existing recovery controls when delivery needs attention." },
      { title: "Preview and approve", text: "Preview the saved version. Website preview shows the analysis card; Discord preview shows the short notification linking to the Watchlist and ticker page. New approved posts also attach images of the saved analysis. Discord and X images use the light theme with a green app.traderslink.pro/watchlist address at the top and bottom and a watermark. The two images show where the trade could go next, then pullback areas with confirmation and invalidation details. Empty or hidden groups do not create blank images; sections are never cut across images. The complete analysis remains available on the website. New Discord analysis posts include the note: Images show part of the analysis. View full analysis in the app 👇 Hidden sections stay hidden. These images keep the approved prices and time; they do not update with live prices. If images cannot be created, the normal linked notification can still post. Approve and publish authorizes that saved version. Published with omissions identifies recorded validation removals still reflected in the approved version. Review the saved analysis checks for details. If you edit again, save and preview again before approval." },
    ] }, { kind: "paragraph", text: "If a breakout was omitted from a draft, its editing fields remain available. Enter your corrected price and explanation, enable Show this section if needed, then save and preview. Price-order warnings do not rewrite or block your correction. The original and your saved version remain separate." },
      { kind: "paragraph", text: "A generation may provide a primary breakout and an optional supported backup in the same AI request. Both the price and explanation are checked before selection. Only the selected breakout appears in the draft; you can edit it before approval. If neither works, independent valid setups can remain. Candidate selection and omission reasons are kept in the audit." },
      { kind: "paragraph", text: "Website and Discord delivery are tracked separately. If delivery needs attention, inspect its status before retrying. An uncertain delivery must not be treated as a confirmed failure or blindly resent." },
      { kind: "paragraph", text: "Under Discord notifications, Delete Discord posts when removing tickers is on by default. Removing a ticker or clearing a list deletes its receipt-tracked Watchlist posts, including analysis updates. Turn it off to keep posts. Free Chat, potential-gain and X posts stay unchanged. Pending deletions and failures appear in that section. Old posts without saved message receipts cannot be deleted automatically. Every second successful Watchlist X post includes a direct Watchlist link; the count is separate from press-release posts. The selected caption is retained on retries. Leave 25 characters for the link when writing a custom caption. Open Discord notifications from the main Watchlist Admin to switch @everyone and individual role mentions on or off. Add a role using its Discord role ID and a recognizable label, or remove it from these settings without deleting the Discord role. Save mentions applies to future notifications, including approved analysis updates when Notify users is selected. Posts already approved retain their audience on retries. Discord post deletion failures can be retried from Discord notifications settings. Retry failed deletions only retries removal of the saved messages; it does not repost or notify members. These controls do not change email, push or Discord channel access. Discord role permissions and each member's notification preferences still apply." },
      { kind: "paragraph", text: "If an approved message appeared in Discord but its delivery is awaiting confirmation, select that message part, enter its Discord message ID, and choose Verify existing message. Verification checks the existing message against the approved text and records a matching receipt; it does not send a message. After successful verification, Retry Discord delivery can finish any remaining parts without resending confirmed parts. A message that cannot be verified stays unresolved." }],
  }, {
    id: "notifications", title: "Watchlist notifications", summary: "Choose push or email updates in Account Notifications.",
    keywords: ["push", "email", "approval", "notifications"],
    blocks: [{ kind: "paragraph", text: "Publish ticker without analysis lists the ticker with its available levels, indicators and saved Trader notes. Notify published without analysis starts checked; uncheck it to list silently. Any analysis draft stays private until you approve it. Approving the analysis together with a new ticker sends one listing announcement. For a ticker already listed, Approve and publish analysis adds the approved read; select Notify Published beside the approval button to announce it, or leave it unchecked to publish silently. The first published analysis is announced as Analysis published; later published analyses use Analysis updated. Listing a ticker without analysis does not count as an earlier analysis. The checkbox starts unchecked for each new approval. Discord analysis updates include the approved images when available; push and email contain links only. Members choose push and email independently in Account Notifications, and both start off. Saving edits or retrying delivery does not create another announcement. Delivery problems do not undo your approval." }],
  }, {
    id: "controls", title: "Generation controls", summary: "Choose review and automatic follow-up behavior.",
    keywords: ["automatic updates", "manual refresh", "session", "cost"],
    // Interrupted requests must not look like a never-generated activation.
    blocks: [{ kind: "paragraph", text: "The listing Added time and ticker header Posted time record first publication to members, not addition to admin. Posted price is the latest available quote saved for that publication, not the analysis reference price. Later analysis updates and list moves preserve this original record. The full analysis labels its nearer dip-buy plan Pullback and its lower alternative Deeper pullback. If only one plan is displayed, it is labelled Pullback. Meaningful resistance can appear before and after the main breakout; the analysis need not fill every available row. Analysis card: Shown/Hidden controls the whole analysis for one ticker. In AI Controls, Analysis display has a global Show failure and recovery section setting. It defaults off for all tickers, hides the whole Failure and recovery section including downside checkpoints, and preserves saved analysis. Momentum failure remains a separate level. Edit the analysis to hide individual pullback sections. Refresh Levels is in ticker diagnostics for troubleshooting; it rebuilds support/resistance and can invoke the existing Discord level-snapshot path. Remove from list removes a ticker, Cancel stops a pending activation, and Retry activation retries a failed activation." }, { kind: "paragraph", text: "Uncheck Generate analysis beside the ticker field to add a notes-only ticker. Enter My notes, then add the ticker. It stays private until you publish it, even if global analysis generation is off. My notes on its row lets you save a draft; after listing, Publish notes updates the member card without notifications. Blank published notes remove that card. Generate analysis on the row requests an analysis later when global/session generation is enabled; review and approve it before members see it. Publishing a new ticker with its approved analysis also publishes your saved Trader notes. Published notes remain alongside the analysis, and unsent notes drafts stay private. The per-ticker choice prevents automatic analysis requests after restart as well. Automatic follow-up AI requests are off by default. Turning them off preserves their settings for later and does not stop live price/data updates. Manual refresh remains available and requests a new analysis. When a required-review replacement is waiting for approval or its generation failed, another automatic request waits for owner action; live data continues." },
      { kind: "paragraph", text: "Automatically publish refreshed analyses applies only to new automatic boundary refreshes of tickers already on the Watchlist. When off, the replacement waits for your review while the existing analysis stays visible. When on, the replacement publishes automatically. Notify users when analyses publish automatically controls member Discord, push and email notifications. It defaults on; off publishes automatic boundary updates silently. Manual approval choices and owner review alerts are unchanged. Initial analyses, manual refreshes and drafts already waiting for review are unchanged. Automatic AI updates must also be on; session settings and request limits still apply." },
      { kind: "paragraph", text: "Notify me when an analysis needs review sends automatic replacement review alerts to your owner account. Push uses that account's AI review notification preference and subscribed devices. Send review notifications to Discord adds an alert to the separately configured private owner channel, not the member Watchlist channel. Reload review controls to see owner delivery status. A notification problem does not generate another analysis or prevent you from approving the saved draft. Member Discord, email and push titles include by \"This Guy\" when you approve the publication. Automatically published updates omit your name." },
      { kind: "paragraph", text: "Post potential gain opens an image preview for that ticker in Watchlist Admin. Add an optional message, then choose Send to Discord to post that exact image to the separate potential gain channel. Every potential gain post tags @everyone, including posts without an optional message. It uses the existing potential gain card, does not generate analysis, and does not send email or push notifications. The image does not update after posting. If delivery cannot be confirmed, check Discord before posting again." },
      { kind: "paragraph", text: "Review before publishing applies to new activations when analysis generation is enabled for that session. If generation is off when you add the ticker, the post follows the normal publishing path without an initial AI request, even if settings or the session change while it prepares. Manual refresh remains available when generation is enabled. With review enabled, replacement analyses also wait for approval, including refreshes of older public tickers. The existing public analysis and live data remain available. Changing review settings does not silently approve a post already waiting for review." },
      { kind: "paragraph", text: "If a request was interrupted before publication was acknowledged, restart keeps that status visible. With automatic updates off, it does not send another initial request. Manual refresh remains a separate request when generation is enabled." }],
  }, {
    id: "inspect-request", title: "Inspect request", summary: "Open available request records in Watchlist Admin.",
    keywords: ["request", "input packet", "response", "omission", "validation"],
    blocks: [{ kind: "paragraph", text: "Choose an Audit generation, then Inspect request. Analysis checks summarize recorded section omissions, optional objective omissions and breakout selection. New original drafts retain their validation decisions with the saved version, so those reasons remain available even if temporary diagnostics expire. Owner edits remain separate from the original decisions. Expand the validation records or original version for full reasons and prices, or inspect the input packet, AI response and saved versions. Missing diagnostics are labelled. Very large sections are shortened on screen for performance; Export audit contains the full available record. Inspecting does not generate or publish analysis." },
      { kind: "paragraph", text: "Analysis checks also explain recorded core and must-clear price anchors and failed checks. A pullback or recovery explanation that fails a volume or session-high claim check can be omitted without removing an independent valid setup. Open its validation record for the original explanation and exact reason. These checks describe the generated analysis, not your later corrections; owner edits are saved separately." },
      { kind: "paragraph", text: "Captured records lists how many input, response, validation, prepared-analysis and transport-error records are available. A zero does not prove that no request was sent or that the stage never occurred; it means that record is unavailable in this audit." },
      { kind: "paragraph", text: "New input records include prompt, schema and request hashes, plus a fingerprint of the named analysis code files and the deployed commit when available. Missing code files are marked incomplete. This fingerprint covers the listed analysis modules, not the entire application." },
      { kind: "paragraph", text: "A rejected checkpoint can also remove levels that depend on it. Separately supported independent levels can remain. Older responses without dependency details may omit the later part of that sequence. The audit preserves the omitted levels and reasons; you can still edit the draft before approval." },
      { kind: "paragraph", text: "AI Controls shows full model versions: GPT-5.6 Luna, GPT-5.6 Terra, GPT-6 Luna and GPT-6 Sol. Choose None, Low, Medium, High, Extra high or Max reasoning effort, then Apply Model. This affects future requests only; it does not regenerate or publish an analysis. Higher effort can use more tokens and take longer. Existing selections stay unchanged until you apply another choice. Fallback model defaults to Off. You can choose a fallback model and its effort, then Apply Model. If the first request cannot produce a draft, one additional paid request is allowed; a usable draft retained for your review does not trigger fallback. Both attempts and their costs appear in usage. Existing generation switches and daily budget still apply, and approval is unchanged. New cost estimates use current standard token rates unless the operator configured an override; saved historical costs are not rewritten. API requests counts distinct recorded attempt IDs for the selected generation, not the number of status or edit rows. Estimated cost uses recorded usage and pricing, including available usage for rejected analyses. Missing historical diagnostics, usage or pricing show Unavailable rather than zero. These recorded totals are not a provider billing statement." }],
  }, {
    id: "audit", title: "Export audit", summary: "Select the generation you want to inspect.",
    keywords: ["original", "edited", "audit", "failed request"],
    blocks: [{ kind: "paragraph", text: "Export audit downloads the selected generation's available request/response diagnostics and saved review history, including original, edited and approved versions when present. Failed generations can also be selected. Use Ticker history to inspect earlier saved histories, including before a ticker was removed and added again. Historical records are read only; select a request there to export its saved analysis and revisions. Review ticker returns to the current review. Missing or unavailable diagnostics are labelled; older requests are not reconstructed. Export does not automatically share the file with Codex or anyone else." }],
  }, {
    id: "indicator-audit", title: "Indicator Audit", summary: "Inspect deterministic indicator refreshes without requesting AI analysis.",
    keywords: ["indicators", "Moomoo", "Yahoo", "fallback", "rate limit", "requests", "calculation"],
    blocks: [{ kind: "paragraph", text: "Choose Indicator Audit directly from the Watchlist Admin menu. Open a refresh to see its ticker activation, outcome, provider attempts, fallback results, timeframe coverage and calculation reference. Moomoo is primary; Yahoo is the fallback. Provider connection status remains in the existing Market Data Connections area. Changing sections keeps the runtime forms and saved analysis controls mounted." },
      { kind: "paragraph", text: "Request counts deduplicate recorded transport IDs across the displayed refresh records. Started, finished and shared-consumer events do not each count as another request. These are observed Indicators/shared-candle requests, not all usage on your provider account. Expand provider requests for explicit HTTP rate-limit evidence, retry timing and failures; a timeout alone is not proof of a rate limit." },
      { kind: "paragraph", text: "Choose Check calculation inputs, then Export calculation JSON when available. The export refers to that exact retained calculation, not the ticker's latest data, and includes available candles, starting state and calculation version. Expired inputs are labelled rather than reconstructed. Exporting does not automatically share data with Codex. Audit coverage shows retention, expired records and dropped writes; buffered events may be missing after a restart." }],
  }],
}];
