import Button from "@mui/material/Button";
import Chip from "@mui/material/Chip";
import Grid from "@mui/material/Grid";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import Link from "next/link";

import { DashboardMetricCard, DashboardPage, DashboardPanel, DashboardUnavailableState } from "@/app/dashboard-ui";
import { requireTraderLinkPlatformServerComponentPageIdentity } from "@/src/modules/platform/server/authentication/require-platform-request-scope";
import { withReadonlyPlatformDatabase } from "@/src/modules/platform/server/database/open-readonly-platform-database";
import { TraderLinkCommunityCoachJournalReadService } from "@/src/modules/communities/server/traderlink-community-coach-journal-read-service";

export default async function CoachStudentPage({params}:{params:Promise<{communitySlug:string;relationshipId:string}>}){const {communitySlug,relationshipId}=await params;const identity=await requireTraderLinkPlatformServerComponentPageIdentity();if(communitySlug==="review")return <Review/>;const data=withReadonlyPlatformDatabase({},database=>new TraderLinkCommunityCoachJournalReadService(database).read({coachUserId:identity.scope.userId,relationshipId}));return <DashboardPage><Button component={Link} href={`/communities/${communitySlug}/workspace`}>← Coach workspace</Button><Typography component="h1" variant="h1">{data.studentName}</Typography><Typography color="text.secondary">{data.accountName} · Shared scope: {data.dataScope}</Typography><Grid container spacing={2}><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption="Factually closed" label="Closed trades" value={String(data.closedTrades)}/></Grid><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption="Confirmed open" label="Open trades" value={String(data.openTrades)}/></Grid><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption="Across shared history" label="Symbols" value={String(data.symbols)}/></Grid><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption={`Coverage ${data.coverage}`} label="Data decisions" value={String(data.pendingDecisions)}/></Grid></Grid><DashboardPanel title="Shared trades">{data.trades.length?<Stack spacing={1}>{data.trades.map(trade=><Stack direction="row" key={trade.roundTripId} sx={{alignItems:"center",borderBottom:1,borderColor:"divider",justifyContent:"space-between",py:1}}><Stack direction="row" spacing={1}><Chip label={trade.symbol}/><Typography>{trade.direction}</Typography></Stack><Typography color="text.secondary" variant="body2">{trade.closedAtUtc?"Closed":"Open"}</Typography></Stack>)}</Stack>:<DashboardUnavailableState compact description="The trader shared summary or analytics access, not individual trades." title="Trade rows are private"/>}</DashboardPanel></DashboardPage>}
function Review(){return <DashboardPage><Button component={Link} href="/communities/review/workspace">← Coach workspace</Button><Typography component="h1" variant="h1">TinaTrades</Typography><Typography color="text.secondary">Primary trading account · Shared scope: trades</Typography><Grid container spacing={2}><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption="Factually closed" label="Closed trades" value="126"/></Grid><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption="Confirmed open" label="Open trades" value="2"/></Grid><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption="Across shared history" label="Symbols" value="48"/></Grid><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption="Coverage complete" label="Data decisions" value="1"/></Grid></Grid><DashboardPanel title="Shared trades"><Stack spacing={1}>{[{s:"NVDA",d:"long",state:"Closed"},{s:"SPY",d:"short",state:"Closed"},{s:"AMD",d:"long",state:"Open"}].map((trade,index)=><Stack direction="row" key={index} sx={{borderBottom:1,borderColor:"divider",justifyContent:"space-between",py:1}}><Stack direction="row" spacing={1}><Chip label={trade.s}/><Typography>{trade.d}</Typography></Stack><Typography color="text.secondary">{trade.state}</Typography></Stack>)}</Stack></DashboardPanel><Typography color="text.secondary" variant="caption">Review data only. A real coach can open this page only while both the coaching relationship and the trader’s separate Journal grant are active.</Typography></DashboardPage>}
