import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Checkbox from "@mui/material/Checkbox";
import Chip from "@mui/material/Chip";
import FormControlLabel from "@mui/material/FormControlLabel";
import Grid from "@mui/material/Grid";
import MenuItem from "@mui/material/MenuItem";
import Stack from "@mui/material/Stack";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";
import Link from "next/link";
import { notFound } from "next/navigation";
import { DashboardMetricCard as BaseDashboardMetricCard, DashboardPage, DashboardPanel, DashboardUnavailableState } from "@/app/dashboard-ui";
import { requireTraderLinkPlatformServerComponentPageIdentity } from "@/src/modules/platform/server/authentication/require-platform-request-scope";
import { withReadonlyPlatformDatabase } from "@/src/modules/platform/server/database/open-readonly-platform-database";
import { TraderLinkCommunityCoachJournalReadService } from "@/src/modules/communities/server/traderlink-community-coach-journal-read-service";
import { createTraderLinkCommunityReviewFixture } from "@/src/modules/communities/server/traderlink-community-review-fixture";
import { loadCommunityDashboard } from "../../../../community-dashboard-loader";
import { createCommunityCoachingRecordAction, createCommunityCoachingTaskAction, sendCommunityCoachingMessageAction, setStudentCoachingServicesAction, updateCommunityCoachingTaskAction, updateCommunityTradeReviewAction } from "../../../../community-actions";

const stamp=(value:string|null)=>value?new Intl.DateTimeFormat("en",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"UTC"}).format(new Date(value))+" UTC":"None";
function DashboardMetricCard(props:Omit<Parameters<typeof BaseDashboardMetricCard>[0],"caption">&{caption?:string}){return <BaseDashboardMetricCard {...props} caption={props.caption??"Current"}/>}

export default async function CoachStudentPage({params}:{params:Promise<{communitySlug:string;relationshipId:string}>}){
 const {communitySlug,relationshipId}=await params;const review=communitySlug==="review";const snapshot=review?createTraderLinkCommunityReviewFixture():(await loadCommunityDashboard(communitySlug,`/communities/${communitySlug}/workspace/students/${relationshipId}`)).snapshot;const relationship=snapshot.relationships.find(item=>item.relationshipId===relationshipId&&item.coachUserId===snapshot.viewer.userId)??(review?snapshot.relationships[0]:undefined);if(!relationship)notFound();const id=relationship.relationshipId;const tasks=snapshot.coachingTasks.filter(x=>x.relationshipId===id);const messages=snapshot.coachingMessages.filter(x=>x.relationshipId===id);const reviews=snapshot.tradeReviews.filter(x=>x.relationshipId===id);const records=snapshot.coachingRecords.filter(x=>x.relationshipId===id);const grants=snapshot.journalGrants.filter(x=>x.relationshipId===id&&x.status==="active");const journal=review?{closedTrades:126,openTrades:2,symbols:48,pendingDecisions:1,trades:[{roundTripId:"1",symbol:"NVDA",direction:"long",closedAtUtc:"2026-09-04T18:00:00.000Z"},{roundTripId:"2",symbol:"AMD",direction:"long",closedAtUtc:null}]}:grants.length?await readJournal(id):null;
 return <DashboardPage>
  <Stack direction={{xs:"column",sm:"row"}} spacing={1}><Button component={Link} href={`/communities/${communitySlug}/workspace`}>Coaching work</Button><Button component={Link} href={`/communities/${communitySlug}/workspace/students`}>Students</Button><Button component={Link} href={`/communities/${communitySlug}/workspace/setup`}>Coach setup</Button></Stack>
  <Stack direction="row" sx={{alignItems:"center",justifyContent:"space-between"}}><Box><Typography component="h1" variant="h1">{relationship.studentDisplayName}</Typography><Typography color="text.secondary">{relationship.planName}</Typography></Box><Chip color={relationship.status==="active"?"success":"default"} label={relationship.status}/></Stack>
  <Grid container spacing={2}><Grid size={{xs:6,lg:3}}><DashboardMetricCard label="Open tasks" value={String(tasks.filter(x=>x.status==="open").length)}/></Grid><Grid size={{xs:6,lg:3}}><DashboardMetricCard label="Trade reviews" value={String(reviews.filter(x=>x.status!=="completed"&&x.status!=="cancelled").length)}/></Grid><Grid size={{xs:6,lg:3}}><DashboardMetricCard label="Messages" value={String(messages.length)}/></Grid><Grid size={{xs:6,lg:3}}><DashboardMetricCard label="Journal access" value={grants.length?"On":"Off"}/></Grid></Grid>
  <DashboardPanel title="Student services"><Box action={review?undefined:setStudentCoachingServicesAction} component="form"><input name="communitySlug" type="hidden" value={communitySlug}/><input name="relationshipId" type="hidden" value={id}/><Stack direction={{xs:"column",md:"row"}} sx={{alignItems:{md:"center"},justifyContent:"space-between"}}><Stack><FormControlLabel control={<Checkbox defaultChecked={relationship.studentMessagingEnabled} name="messagingEnabled"/>} label="Student messaging"/><FormControlLabel control={<Checkbox defaultChecked={relationship.studentTradeReviewsEnabled} name="tradeReviewsEnabled"/>} label="Student trade-review requests"/></Stack><Button disabled={review} type="submit" variant="contained">Save access</Button></Stack></Box></DashboardPanel>
  <Grid container spacing={2}><Grid size={{xs:12,lg:6}}><DashboardPanel title="Tasks"><Stack spacing={1}>{tasks.map(task=><Stack direction="row" key={task.taskId} sx={{alignItems:"center",borderBottom:1,borderColor:"divider",justifyContent:"space-between",pb:1}}><Box><Typography style={{fontWeight:800}}>{task.title}</Typography><Typography color="text.secondary" variant="caption">{task.priority} · {stamp(task.dueAtUtc)}</Typography></Box>{task.status==="open"?<Box action={review?undefined:updateCommunityCoachingTaskAction} component="form"><Hidden communitySlug={communitySlug} relationshipId={id}/><input name="taskId" type="hidden" value={task.taskId}/><Button disabled={review} name="status" type="submit" value="completed">Complete</Button></Box>:<Chip color="success" label={task.status}/>}</Stack>)}</Stack><Box action={review?undefined:createCommunityCoachingTaskAction} component="form" sx={{mt:2}}><Hidden communitySlug={communitySlug} relationshipId={id}/><Stack spacing={1}><TextField label="Task" name="title" required/><TextField label="Due" name="dueAt" slotProps={{inputLabel:{shrink:true}}} type="datetime-local"/><TextField defaultValue="normal" label="Priority" name="priority" select><MenuItem value="normal">Normal</MenuItem><MenuItem value="high">High</MenuItem></TextField><Button disabled={review} type="submit" variant="outlined">Add task</Button></Stack></Box></DashboardPanel></Grid>
  <Grid size={{xs:12,lg:6}}><DashboardPanel title="Messages"><Stack spacing={1}>{messages.map(message=><Box key={message.messageId} sx={{borderBottom:1,borderColor:"divider",pb:1}}><Stack direction="row" sx={{justifyContent:"space-between"}}><Typography style={{fontWeight:800}}>{message.authorName}</Typography><Typography color="text.secondary" variant="caption">{stamp(message.createdAtUtc)}</Typography></Stack><Typography variant="body2">{message.body}</Typography></Box>)}</Stack><Box action={review?undefined:sendCommunityCoachingMessageAction} component="form" sx={{mt:2}}><Hidden communitySlug={communitySlug} relationshipId={id}/><Stack direction={{xs:"column",sm:"row"}} spacing={1}><TextField fullWidth label="Message" name="body" required/><Button disabled={review} type="submit" variant="contained">Send</Button></Stack></Box></DashboardPanel></Grid></Grid>
  <DashboardPanel title="Trade reviews"><Grid container spacing={2}>{reviews.map(item=><Grid key={item.reviewId} size={{xs:12,lg:6}}><Box action={review?undefined:updateCommunityTradeReviewAction} component="form" sx={{border:1,borderColor:"divider",borderRadius:2,p:2}}><input name="communitySlug" type="hidden" value={communitySlug}/><input name="reviewId" type="hidden" value={item.reviewId}/><Stack spacing={1}><Stack direction="row" sx={{justifyContent:"space-between"}}><Typography style={{fontWeight:800}}>{item.title}</Typography><Chip color={item.status==="completed"?"success":"warning"} label={item.status}/></Stack><Typography variant="body2">{item.studentContext}</Typography><TextField defaultValue={item.coachFeedback} label="Coach feedback" minRows={3} multiline name="coachFeedback"/><Stack direction="row" spacing={1}><Button disabled={review} name="status" type="submit" value="in_review">Save draft</Button><Button disabled={review} name="status" type="submit" value="completed" variant="contained">Complete review</Button></Stack></Stack></Box></Grid>)}</Grid></DashboardPanel>
  <Grid container spacing={2}><Grid size={{xs:12,lg:7}}><DashboardPanel title="Shared Journal">{journal?<><Grid container spacing={1}><Grid size={{xs:6,md:3}}><DashboardMetricCard label="Closed trades" value={String(journal.closedTrades)}/></Grid><Grid size={{xs:6,md:3}}><DashboardMetricCard label="Open trades" value={String(journal.openTrades)}/></Grid><Grid size={{xs:6,md:3}}><DashboardMetricCard label="Symbols" value={String(journal.symbols)}/></Grid><Grid size={{xs:6,md:3}}><DashboardMetricCard label="Data decisions" value={String(journal.pendingDecisions)}/></Grid></Grid><Stack spacing={1} sx={{mt:2}}>{journal.trades.map(trade=><Stack direction="row" key={trade.roundTripId} sx={{justifyContent:"space-between"}}><Stack direction="row" spacing={1}><Chip label={trade.symbol}/><Typography>{trade.direction}</Typography></Stack><Typography color="text.secondary">{trade.closedAtUtc?"Closed":"Open"}</Typography></Stack>)}</Stack></>:<DashboardUnavailableState compact description="" title="Journal access is off"/>}</DashboardPanel></Grid>
  <Grid size={{xs:12,lg:5}}><DashboardPanel title="Coaching history"><Stack spacing={1}>{records.map(record=><Box key={record.recordId} sx={{borderBottom:1,borderColor:"divider",pb:1}}><Stack direction="row" sx={{justifyContent:"space-between"}}><Typography style={{fontWeight:800}}>{record.title}</Typography><Chip label={record.visibility==="coach_private"?"Private":"Shared"} size="small"/></Stack><Typography color="text.secondary" variant="caption">{record.recordType} · {stamp(record.occurredAtUtc)}</Typography><Typography variant="body2">{record.body}</Typography></Box>)}</Stack><Box action={review?undefined:createCommunityCoachingRecordAction} component="form" sx={{mt:2}}><Hidden communitySlug={communitySlug} relationshipId={id}/><Stack spacing={1}><TextField defaultValue="session" label="Type" name="recordType" select><MenuItem value="session">Session</MenuItem><MenuItem value="note">Note</MenuItem></TextField><TextField defaultValue="shared" label="Visibility" name="visibility" select><MenuItem value="shared">Shared</MenuItem><MenuItem value="coach_private">Coach only</MenuItem></TextField><TextField label="Title" name="title" required/><TextField label="Notes" minRows={3} multiline name="body"/><Button disabled={review} type="submit" variant="outlined">Save history</Button></Stack></Box></DashboardPanel></Grid></Grid>
 </DashboardPage>;
}
function Hidden({communitySlug,relationshipId}:{communitySlug:string;relationshipId:string}){return <><input name="communitySlug" type="hidden" value={communitySlug}/><input name="relationshipId" type="hidden" value={relationshipId}/></>}
async function readJournal(relationshipId:string){const identity=await requireTraderLinkPlatformServerComponentPageIdentity();return withReadonlyPlatformDatabase({},database=>new TraderLinkCommunityCoachJournalReadService(database).read({coachUserId:identity.scope.userId,relationshipId}));}
