import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Chip from "@mui/material/Chip";
import Grid from "@mui/material/Grid";
import Stack from "@mui/material/Stack";
import {notFound} from "next/navigation";
import {DashboardPage,DashboardPanel} from "@/app/dashboard-ui";
import {createTraderLinkCommunityReviewFixture} from "@/src/modules/communities/server/traderlink-community-review-fixture";
import {loadCommunityDashboard} from "../../../../../../../community-dashboard-loader";
import {CoachWorkspaceNavigation} from "../../../../../../../coach-workspace-navigation";
import {CommunityTypography as Typography} from "../../../../../../../community-typography";

export default async function FinalReviewPage({params}:{params:Promise<{communitySlug:string;relationshipId:string;reviewId:string}>}){
 const {communitySlug,relationshipId,reviewId}=await params;const isReview=communitySlug==="review";const snapshot=isReview?createTraderLinkCommunityReviewFixture("coach"):(await loadCommunityDashboard(communitySlug,`/communities/${communitySlug}/workspace/students/${relationshipId}/reviews/${reviewId}/final`)).snapshot;const relationship=snapshot.relationships.find(item=>item.relationshipId===relationshipId&&item.coachUserId===snapshot.viewer.userId);const review=snapshot.tradeReviews.find(item=>item.reviewId===reviewId&&item.relationshipId===relationshipId);if(!relationship||!review)notFound();const sections=[["Review",review.coachFeedback],["What went well",review.wentWell],["What needs work",review.needsWork],["Progress on previous focus",review.previousFocusAssessment],["Next focus",review.nextFocus]].filter(([,value])=>Boolean(value));
 return <DashboardPage><CoachWorkspaceNavigation slug={communitySlug}/><Stack direction={{xs:"column",sm:"row"}} spacing={1} sx={{alignItems:{sm:"center"},justifyContent:"space-between"}}><Box><Typography component="h1" variant="h1">Review and send</Typography><Typography color="text.secondary">{relationship.studentDisplayName} · {review.title}</Typography></Box><Chip color="warning" label="Draft"/></Stack><Grid container spacing={2}><Grid size={{xs:6,md:3}}><Summary label="Trade reviews" value={String(review.roundTripIds.length)}/></Grid><Grid size={{xs:6,md:3}}><Summary label="Overall review" value={review.coachFeedback?"Ready":"Not added"}/></Grid><Grid size={{xs:6,md:3}}><Summary label="Next focus" value={review.nextFocus?"Ready":"Not added"}/></Grid><Grid size={{xs:6,md:3}}><Summary label="Student actions" value="0"/></Grid></Grid><DashboardPanel title="Trade reviews"><Stack spacing={1.5}>{review.roundTripIds.map((trade,index)=><Box key={trade} sx={{borderBottom:1,borderColor:"divider",pb:1.5}}><Stack direction="row" sx={{alignItems:"center",justifyContent:"space-between"}}><Typography fontWeight={800}>Trade {index+1}</Typography><Chip color="success" label="Ready" size="small"/></Stack><Typography sx={{mt:.5}} variant="body2">Saved trade review</Typography></Box>)}</Stack></DashboardPanel>{sections.map(([title,value])=><DashboardPanel key={title} title={title}><Typography variant="body2">{value}</Typography></DashboardPanel>)}<Stack direction={{xs:"column",sm:"row"}} spacing={1} sx={{justifyContent:"flex-end"}}><Button href={`/communities/${communitySlug}/workspace/students/${relationshipId}/reviews/${reviewId}`} variant="outlined">Return to workspace</Button><Button disabled={isReview} variant="contained">Send review to {relationship.studentDisplayName}</Button></Stack></DashboardPage>;
}
function Summary({label,value}:{label:string;value:string}){return <DashboardPanel title={label}><Typography fontWeight={800}>{value}</Typography></DashboardPanel>}
