import ForumRoundedIcon from "@mui/icons-material/ForumRounded";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Chip from "@mui/material/Chip";
import Divider from "@mui/material/Divider";
import Grid from "@mui/material/Grid";
import MenuItem from "@mui/material/MenuItem";
import Stack from "@mui/material/Stack";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";
import Link from "next/link";

import { DashboardMetricCard, DashboardPanel } from "@/app/dashboard-ui";
import { withJournalAdminPageDatabase } from "@/src/modules/platform/server/administration/require-journal-admin-page";
import { configureCommunityCoachFeeAction, configureCommunityPartnerAction, setCommunityStatusAction } from "@/app/(dashboard)/admin/communities/admin-actions";

type CommunityRow=Readonly<{communityId:string;slug:string;name:string;status:string;guildId:string;members:number;coaches:number;alerts:number;watchlists:number;pending:number}>;
type AdminItem=Readonly<{community:string;name:string;detail:string;status:string}>;

export default async function JournalCommunitiesAdminPage(){
  const snapshot=await withJournalAdminPageDatabase((database)=>{
    const rows=database.prepare(`SELECT c.community_id communityId,c.slug,c.display_name name,c.status,c.discord_guild_id guildId,
  (SELECT count(*) FROM traderlink_community_memberships m WHERE m.community_id=c.community_id AND m.status='active') members,
  (SELECT count(*) FROM traderlink_community_coach_profiles p WHERE p.community_id=c.community_id AND p.status='active') coaches,
  (SELECT count(*) FROM traderlink_community_alerts a WHERE a.community_id=c.community_id AND a.status='published') alerts,
  ((SELECT count(*) FROM traderlink_community_watchlist_placements w WHERE w.community_id=c.community_id AND w.status='published')+
   (SELECT count(*) FROM traderlink_community_server_watchlists w WHERE w.community_id=c.community_id AND w.status='published')) watchlists,
  (SELECT count(*) FROM traderlink_community_content_deliveries d WHERE d.community_id=c.community_id AND d.status IN ('pending','sending','failed')) pending
FROM traderlink_communities c ORDER BY c.updated_at_utc DESC`).all() as CommunityRow[];
    const owners=database.prepare(`SELECT c.display_name community,u.display_name name,c.discord_guild_id detail,c.status FROM traderlink_communities c JOIN platform_users u ON u.user_id=c.owner_user_id ORDER BY c.display_name`).all() as AdminItem[];
    const staff=database.prepare(`SELECT c.display_name community,u.display_name name,r.name||' · '||group_concat(cap.capability_key,', ') detail,a.status FROM traderlink_community_member_role_assignments a JOIN traderlink_communities c ON c.community_id=a.community_id JOIN platform_users u ON u.user_id=a.user_id JOIN traderlink_community_roles r ON r.role_id=a.role_id LEFT JOIN traderlink_community_role_capabilities cap ON cap.role_id=r.role_id GROUP BY a.assignment_id ORDER BY c.display_name,u.display_name`).all() as AdminItem[];
    const content=database.prepare(`SELECT c.display_name community,u.display_name name,'Alert · '||a.title detail,a.status FROM traderlink_community_alerts a JOIN traderlink_communities c ON c.community_id=a.community_id JOIN platform_users u ON u.user_id=a.author_user_id UNION ALL SELECT c.display_name,u.display_name,'Watchlist · '||w.title,w.status FROM traderlink_community_server_watchlists w JOIN traderlink_communities c ON c.community_id=w.community_id JOIN platform_users u ON u.user_id=w.author_user_id ORDER BY community,name`).all() as AdminItem[];
    const coaches=database.prepare(`SELECT c.display_name community,p.display_name name,p.active_students||' / '||p.capacity||' students' detail,p.status FROM (SELECT profile.*, (SELECT count(*) FROM traderlink_community_coaching_relationships r WHERE r.coach_profile_id=profile.coach_profile_id AND r.status='active') active_students FROM traderlink_community_coach_profiles profile) p JOIN traderlink_communities c ON c.community_id=p.community_id ORDER BY c.display_name,p.display_name`).all() as AdminItem[];
    const integrations=database.prepare(`SELECT c.display_name community,d.name name,d.content_type||' · '||d.discord_channel_id detail,d.status FROM traderlink_community_discord_destinations d JOIN traderlink_communities c ON c.community_id=d.community_id ORDER BY c.display_name,d.content_type`).all() as AdminItem[];
    const audit=database.prepare(`SELECT c.display_name community,u.display_name name,e.action detail,e.occurred_at_utc status FROM traderlink_community_authorization_audit_events e JOIN traderlink_communities c ON c.community_id=e.community_id JOIN platform_users u ON u.user_id=e.actor_user_id ORDER BY e.occurred_at_utc DESC LIMIT 50`).all() as AdminItem[];
    return Object.freeze({rows:Object.freeze(rows),owners:Object.freeze(owners),staff:Object.freeze(staff),content:Object.freeze(content),coaches:Object.freeze(coaches),integrations:Object.freeze(integrations),audit:Object.freeze(audit),members:rows.reduce((sum,row)=>sum+row.members,0),contentCount:rows.reduce((sum,row)=>sum+row.alerts+row.watchlists,0),pending:rows.reduce((sum,row)=>sum+row.pending,0)});
  });
  return <Stack spacing={3}>
    <Stack direction="row" spacing={1} sx={{alignItems:"center"}}><ForumRoundedIcon color="primary"/><Typography component="h1" variant="h1">Communities</Typography></Stack>
    <Grid container spacing={2}><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption={`${snapshot.rows.filter(row=>row.status==="active").length} active`} label="Discord servers" value={String(snapshot.rows.length)}/></Grid><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption="Verified memberships" label="Members" value={snapshot.members.toLocaleString()}/></Grid><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption="Alerts and watchlists" label="Published content" value={snapshot.contentCount.toLocaleString()}/></Grid><Grid size={{xs:6,lg:3}}><DashboardMetricCard caption="Pending or failed" label="Delivery queue" value={snapshot.pending.toLocaleString()}/></Grid></Grid>
    <DashboardPanel title="Connected Discord servers"><Stack spacing={1.5}>{snapshot.rows.map(row=><Stack direction={{xs:"column",md:"row"}} key={row.slug} sx={{alignItems:{md:"center"},border:1,borderColor:"divider",borderRadius:2,justifyContent:"space-between",p:2}}><Stack><Typography style={{fontWeight:800}}>{row.name}</Typography><Typography color="text.secondary" variant="caption">Guild {row.guildId} · {row.members} members · {row.coaches} coaches · {row.alerts} alerts · {row.watchlists} watchlists · {row.status}</Typography></Stack><Button component={Link} href={`/communities/${row.slug}/manage`} size="small" variant="outlined">Open server dashboard</Button></Stack>)}{!snapshot.rows.length?<Typography color="text.secondary">No Discord servers have been connected.</Typography>:null}</Stack></DashboardPanel>
    <Grid container spacing={2}>
      <Grid size={{xs:12,lg:6}}><DashboardPanel title="Tier 2 partner terms"><Box action={configureCommunityPartnerAction} component="form"><Stack spacing={2}><CommunitySelect rows={snapshot.rows}/><TextField defaultValue="disabled" label="Status" name="status" select><MenuItem value="disabled">Disabled</MenuItem><MenuItem value="active">Active</MenuItem><MenuItem value="paused">Paused</MenuItem></TextField><TextField helperText="Leave blank until you decide the server's share." label="Commission percent" name="commissionPercent" type="number"/><TextField defaultValue={90} label="Attribution window in days" name="attributionDays" type="number"/><TextField defaultValue="USD" label="Currency" name="currency"/><Button disabled={!snapshot.rows.length} type="submit" variant="contained">Save partner terms</Button></Stack></Box></DashboardPanel></Grid>
      <Grid size={{xs:12,lg:6}}><DashboardPanel title="Optional future coach fee"><Box action={configureCommunityCoachFeeAction} component="form"><Stack spacing={2}><CommunitySelect rows={snapshot.rows}/><TextField helperText="Leave blank to apply the rule to every coach in this server." label="Specific coach user ID" name="coachUserId"/><TextField label="Fee percent" name="feePercent" type="number" required/><TextField defaultValue="disabled" label="Status" name="status" select><MenuItem value="disabled">Disabled</MenuItem><MenuItem value="active">Active</MenuItem></TextField><TextField label="Internal notes" minRows={2} multiline name="notes"/><Button disabled={!snapshot.rows.length} type="submit" variant="contained">Save fee rule</Button><Typography color="text.secondary" variant="caption">TraderLink does not process coaching payments in this pilot. This control stays disabled until a compatible provider is selected.</Typography></Stack></Box></DashboardPanel></Grid>
    </Grid>
    <Grid container spacing={2}><Grid size={{xs:12,md:6}}><DashboardPanel title="Server status"><Box action={setCommunityStatusAction} component="form"><Stack spacing={2}><CommunitySelect rows={snapshot.rows}/><TextField defaultValue="active" label="New status" name="status" select><MenuItem value="active">Active</MenuItem><MenuItem value="paused">Paused</MenuItem><MenuItem value="suspended">Suspended</MenuItem></TextField><Button disabled={!snapshot.rows.length} type="submit" variant="contained">Update server</Button></Stack></Box></DashboardPanel></Grid><Grid size={{xs:12,md:6}}><DashboardPanel title="Discord delivery queue"><Typography variant="h2">{snapshot.pending}</Typography><Typography color="text.secondary" variant="body2">Pending, sending, or failed deliveries require attention.</Typography></DashboardPanel></Grid></Grid>
    <Grid container spacing={2}><Grid size={{xs:12,lg:6}}><AdminList items={snapshot.owners} title="Server owners"/></Grid><Grid size={{xs:12,lg:6}}><AdminList items={snapshot.staff} title="Staff assignments"/></Grid><Grid size={{xs:12,lg:6}}><AdminList items={snapshot.content} title="Community content"/></Grid><Grid size={{xs:12,lg:6}}><AdminList items={snapshot.coaches} title="Coaches"/></Grid><Grid size={{xs:12,lg:6}}><AdminList items={snapshot.integrations} title="Integrations"/></Grid><Grid size={{xs:12,lg:6}}><AdminList items={snapshot.audit} title="Audit"/></Grid></Grid>
  </Stack>;
}

function CommunitySelect({rows}:{rows:readonly CommunityRow[]}){return <TextField label="Community" name="communityId" select required>{rows.map(row=><MenuItem key={row.communityId} value={row.communityId}>{row.name}</MenuItem>)}</TextField>}
function AdminList({items,title}:{items:readonly AdminItem[];title:string}){return <DashboardPanel title={title}><Stack divider={<Divider/>}>{items.slice(0,20).map((item,index)=><Stack direction={{xs:"column",sm:"row"}} key={`${item.community}-${item.name}-${index}`} sx={{alignItems:{sm:"center"},justifyContent:"space-between",py:1.25}}><Box><Typography style={{fontWeight:800}}>{item.name}</Typography><Typography color="text.secondary" variant="caption">{item.community} · {item.detail}</Typography></Box><Chip color={item.status==="active"||item.status==="published"?"success":"warning"} label={item.status} size="small"/></Stack>)}</Stack></DashboardPanel>}
