/* This file is generated by src/scripts/generate-coach-ai-chat-language-registry.ts. */
/* Do not edit it by hand or treat vocabulary coverage as calculation support. */

export const COACH_AI_CHAT_LANGUAGE_INVENTORY_SOURCE_SHA256 = "1ef13dcba80b9198e83e9c80cca815e97c0af4af0c3ecc19fabea2bb8f87771e" as const;

export type CoachAiChatLanguageInventoryEntry = Readonly<{
  canonicalName: string;
  categoryFile: string;
  sourceCapabilityStatus: string;
  runtimeCapabilityId: string | null;
}>;

export const coachAiChatLanguageInventory = Object.freeze([
  {
    "canonicalName": "retrieve_records",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "summarize_performance",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "calculate_metric",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "compare_groups",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "group_and_aggregate",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "rank_results",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "detect_pattern",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "explain_result",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "diagnose_performance",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "identify_strengths",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "evaluate_rule",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "evaluate_label",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "analyze_trade",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "find_similar_trades",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "analyze_sequence",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "analyze_trend",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "run_counterfactual",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "evaluate_goal",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "generate_coaching",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "explain_concept",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "inspect_data_quality",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "assist_journaling",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "product_help",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": "product_help"
  },
  {
    "canonicalName": "unsupported_request",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "prepare_manual_execution_draft",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": "manual_execution_drafts"
  },
  {
    "canonicalName": "prepare_user_setting_change",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": "review_delivery_draft"
  },
  {
    "canonicalName": "assist_daily_review",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": "daily_tracker_drafts"
  },
  {
    "canonicalName": "gross_profit",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "gross_loss",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "gross_pnl",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "net_pnl",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "realized_pnl",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "unrealized_pnl",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "total_return",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "average_net_pnl_per_trade",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "median_net_pnl_per_trade",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "average_percentage_return",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "median_percentage_return",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "largest_win",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "largest_loss",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "average_winning_trade",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "average_losing_trade",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "average_daily_pnl",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "average_weekly_pnl",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "average_monthly_pnl",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "profit_per_share",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "pnl_by_direction",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "pnl_before_fees",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "pnl_after_fees",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "trade_count",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "winning_trades",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "losing_trades",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "breakeven_trades",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "open_trades",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "closed_trades",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "win_rate",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "loss_rate",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "breakeven_rate",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "green_days",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "red_days",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "flat_days",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "percentage_of_profitable_days",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "consecutive_wins",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "consecutive_losses",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "maximum_win_streak",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "maximum_loss_streak",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "expectancy",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "profit_factor",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "payoff_ratio",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "average_win_to_average_loss_ratio",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "median_win_to_median_loss_ratio",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "consistency",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "return_dispersion",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "standard_deviation",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "percentage_of_total_profit_from_top_trades",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "percentage_of_total_loss_from_worst_trades",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "dependency_on_outliers",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "results_excluding_best_trade",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "results_excluding_worst_trade",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "total_commissions",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "total_regulatory_fees",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "total_transaction_costs",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "fees_per_trade",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "fees_per_share",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "fees_as_percentage_of_gross_profit",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "trades_turned_from_green_to_red_by_fees",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "fee_impact_on_expectancy",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "fee_impact_by_broker",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "fee_completeness",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "shares_purchased",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "shares_sold",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "average_position_size",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "median_position_size",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "maximum_position_size",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "average_dollar_exposure",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "maximum_dollar_exposure",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "size_relative_to_normal_size",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "performance_by_size_bucket",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "size_after_wins",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "size_after_losses",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "size_escalation",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "size_reduction",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "profit_per_dollar_exposed",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "entry_time",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "exit_time",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "hold_duration",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "average_hold_duration",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "median_hold_duration",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "time_to_first_exit",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "session",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "weekday",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "week",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "month",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "quarter",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "year",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "days_held",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "trades_per_day",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "time_between_trades",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "time_after_previous_loss",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "time_after_previous_win",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "first_trade_time",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "last_trade_time",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "number_of_entries",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "number_of_exits",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "average_entry_price",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "average_exit_price",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "weighted_average_entry_price",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "weighted_average_exit_price",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "entry_execution_count",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "exit_execution_count",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "scale_in_count",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "scale_out_count",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "partial_exit_percentage",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "position_flips",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "repeat_attempts",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "trade_sequence",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "average_shares_per_execution",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "execution_duration",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "entry_to_exit_quantity_reconciliation",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "unmatched_executions",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "remaining_open_quantity",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "overtrading_frequency",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "fourth_or_later_performance",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "performance_after_a_loss",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "performance_after_two_losses",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "performance_after_a_win",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "performance_after_a_large_win",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "performance_after_a_large_loss",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "repeat_attempt_performance",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "loss_chasing_proxy",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "size_increase_after_losses",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "shortened_wait_time_after_losses",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "profit_giveback",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "daily_loss_limit_violations",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "continued_trading_after_profit_target",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "continued_trading_after_stop_threshold",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "time_cutoff_violations",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "rule_adherence",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "mistake_frequency",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "mistake_cost",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "setup_discipline",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "plan_adherence",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "mfe",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "mae",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "profit_giveback",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "maximum_favourable_price",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "maximum_adverse_price",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "percentage_of_available_move_captured",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "entry_distance_from_vwap",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "entry_distance_from_high_of_day",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "entry_distance_from_low_of_day",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "volume_at_entry",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "relative_volume",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "price_change_after_entry",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "time_to_maximum_favourable_excursion",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "time_to_maximum_adverse_excursion",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "recovery_to_entry",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "post_exit_continuation",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "stop_distance",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "target_distance",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "user",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "account",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "broker",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "import_source",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "currency",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "instrument_type",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "ticker",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "exchange",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "trade_id",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "journal_entry_id",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "execution_id",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "import_batch",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "exact_date",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "date_range",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "today",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "yesterday",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "this_week",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "last_week",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "this_month",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "last_month",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "this_year",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "rolling_number_of_days",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "last_number_of_trades",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "before_or_after_a_time",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "between_two_times",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "premarket",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "regular_session",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "after_hours",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "weekday",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "month",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "quarter",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "year",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": "closed_trade_facts"
  },
  {
    "canonicalName": "earnings_period_if_supplied_by_external_data",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "custom_trading_session",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "entry_price",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "exit_price",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "lowest_execution_price",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "highest_execution_price",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "trade_price_range",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "stocks_under_a_price",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "stocks_over_a_price",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "price_buckets",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "penny_stocks_where_explicitly_defined",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "sub_dollar_stocks",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "average_entry_cost",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "winning",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "losing",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "breakeven",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "open",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "closed",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "gross_winner",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "net_winner",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "gross_winner_turned_into_net_loser_by_fees",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "reached_green_then_closed_red",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "recovered",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "did_not_recover",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "long",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "short",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "buy_to_open",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "sell_to_open",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "mixed_or_flipped_position",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "unknown_direction",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "share_size_range",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "dollar_size_range",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "size_bucket",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "size_relative_to_personal_median",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "size_relative_to_recent_baseline",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "largest_positions",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "smallest_positions",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "first_trade_of_the_day",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "second_trade",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "third_trade",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "fourth_or_later_trade",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "first_attempt_on_ticker",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "second_attempt",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "third_attempt",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "fourth_or_later_attempt",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "trade_after_win",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "trade_after_loss",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "trade_after_two_losses",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "trade_during_a_winning_streak",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "trade_during_a_losing_streak",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "trade_after_daily_target_reached",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "trade_after_daily_loss_threshold_reached",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "setup",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "strategy",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "playbook",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "custom_tag",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "mistake",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "emotion",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "rule",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "rule_followed",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "rule_broken",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "confidence_rating",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "quality_rating",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "notes_present",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "notes_missing",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "screenshot_present",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "screenshot_missing",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "planned_trade",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "unplanned_trade",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "reviewed",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "not_reviewed",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "scalp",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "intraday",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "overnight",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "swing",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "custom_duration",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "under_a_number_of_minutes",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "over_a_number_of_minutes",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "duration_buckets",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "equality",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "inequality",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "greater_than",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "greater_than_or_equal",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "less_than",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "less_than_or_equal",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "range",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "inclusion",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "exclusion",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "membership",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "text_search",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "calendar_dates",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "relative_dates",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "trading_dates",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "rolling_windows",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "record_count_windows",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "session_times",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "display_timezone",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "account_timezone",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "daily_trade_tracker_eastern_market_time",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "best",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "worst",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "top",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "bottom",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "most_profitable",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "least_profitable",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "biggest",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "smallest",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "most_consistent",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "most_frequent",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "most_costly",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "highest_win_rate",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "lowest_expectancy",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "better_than",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "worse_than",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "improved",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "declined",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "more_profitable",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "less_consistent",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "larger_losses",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "smaller_positions",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "higher_frequency",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "before_versus_after",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "current_versus_previous",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "selected_trade_versus_similar_trades",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "one_ticker_versus_all_other_tickers",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "tagged_versus_untagged",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "followed_rule_versus_broke_rule",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "superlative_and_extremum_questions",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "last_intent",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "last_metric_or_metric_set",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "active_date_range",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "active_filters",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "active_comparison",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "active_grouping",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "selected_trade",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "selected_ticker",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "selected_journal_entry",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "current_account",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "response_detail_level",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "unresolved_ambiguity",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "filter_modification",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "time_modification",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "metric_modification",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "grouping_modification",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "detail_modification",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "comparison_continuation",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "trade_outcome_vocabulary",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "trading_frequency_vocabulary",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "profit_giveback_vocabulary",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "repeat_trading_vocabulary",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "position_size_vocabulary",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "price_terms_vocabulary",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "user_tag_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "user_setup_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "user_strategy_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "user_rule_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "user_mistake_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "user_playbook_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "user_session_name_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "user_price_bucket_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "user_goal_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "best_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "worst_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "better_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "profit_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "size_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "risk_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "later_trades_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "recent_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "cheap_stocks_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "scalp_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "overtrading_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "good_trade_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "bad_trade_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "normal_size_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "large_loss_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "performance_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "consistency_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "brief",
    "categoryFile": "18-response-preferences.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "standard",
    "categoryFile": "18-response-preferences.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "detailed",
    "categoryFile": "18-response-preferences.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "table",
    "categoryFile": "18-response-preferences.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "coach",
    "categoryFile": "18-response-preferences.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "audit",
    "categoryFile": "18-response-preferences.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "deterministic_truth_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "server_authoritative_scope_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "privacy_minimization_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "evidence_and_coverage_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "missing_data_no_invention_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "unsupported_request_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "causation_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "prediction_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "advice_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "protected_action_confirmation_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "untrusted_content_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "canonical_question_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "paraphrase_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "misspelling_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "shorthand_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "multi_part_request_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "follow_up_context_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "negation_scope_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "ambiguity_handling_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "adversarial_language_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  },
  {
    "canonicalName": "cross_category_combination_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityId": null
  }
]) satisfies readonly CoachAiChatLanguageInventoryEntry[];
