/* This file is generated by src/scripts/generate-coach-ai-chat-language-registry.ts. */
/* Do not edit it by hand or treat vocabulary coverage as calculation support. */

export const COACH_AI_CHAT_LANGUAGE_INVENTORY_SOURCE_SHA256 = "9f3dff75bb7ab825c3be83dae610bed2adf1814f3be16f7d7b4da3b206178a99" as const;

export type CoachAiChatLanguageInventoryEntry = Readonly<{
  canonicalName: string;
  categoryFile: string;
  sourceCapabilityStatus: string;
  runtimeCapabilityIds: readonly string[];
}>;

export type CoachAiChatRuntimeCapabilityCoverage = Readonly<{
  runtimeCapabilityId: string;
  canonicalNames: readonly string[];
  representativeFixtures: readonly Readonly<{
    id: string;
    surface: string;
    input: string;
    expectedRoute: string;
    expectedKind: "factual_read" | "confirmed_draft";
    expectedFactualToolNames: readonly string[];
    expectedActionDraftKind?: string;
  }>[];
}>;

export const coachAiChatLanguageInventory = Object.freeze([
  {
    "canonicalName": "retrieve_records",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "closed_trade_facts",
      "current_dashboard_journal_reads",
      "journal_period_context"
    ]
  },
  {
    "canonicalName": "summarize_performance",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "closed_trade_facts",
      "current_dashboard_analytics_reads"
    ]
  },
  {
    "canonicalName": "calculate_metric",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "closed_trade_facts",
      "current_dashboard_analytics_reads"
    ]
  },
  {
    "canonicalName": "compare_groups",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "closed_trade_facts",
      "current_dashboard_analytics_reads"
    ]
  },
  {
    "canonicalName": "group_and_aggregate",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "closed_trade_facts",
      "current_dashboard_analytics_reads"
    ]
  },
  {
    "canonicalName": "rank_results",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "closed_trade_facts",
      "current_dashboard_analytics_reads"
    ]
  },
  {
    "canonicalName": "detect_pattern",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "explain_result",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "closed_trade_facts",
      "saved_ai_review_follow_up"
    ]
  },
  {
    "canonicalName": "diagnose_performance",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "identify_strengths",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "evaluate_rule",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "confirmed_product_changes",
      "trading_rule_and_tag_reads"
    ]
  },
  {
    "canonicalName": "evaluate_label",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "analyze_trade",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "current_dashboard_journal_reads",
      "saved_trade_analyzer_reads"
    ]
  },
  {
    "canonicalName": "find_similar_trades",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "analyze_sequence",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "analyze_trend",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "run_counterfactual",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "evaluate_goal",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "generate_coaching",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "explain_concept",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "product_help"
    ]
  },
  {
    "canonicalName": "inspect_data_quality",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "current_product_status_reads"
    ]
  },
  {
    "canonicalName": "assist_journaling",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "confirmed_product_changes",
      "daily_tracker_drafts"
    ]
  },
  {
    "canonicalName": "product_help",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "product_help"
    ]
  },
  {
    "canonicalName": "unsupported_request",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "prepare_manual_execution_draft",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "confirmed_product_changes",
      "manual_execution_drafts"
    ]
  },
  {
    "canonicalName": "prepare_user_setting_change",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "confirmed_product_changes",
      "review_delivery_draft"
    ]
  },
  {
    "canonicalName": "assist_daily_review",
    "categoryFile": "01-intents.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "daily_tracker_drafts"
    ]
  },
  {
    "canonicalName": "gross_profit",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "gross_loss",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "gross_pnl",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts",
      "current_dashboard_analytics_reads"
    ]
  },
  {
    "canonicalName": "net_pnl",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts",
      "current_dashboard_analytics_reads"
    ]
  },
  {
    "canonicalName": "realized_pnl",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "unrealized_pnl",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "total_return",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "average_net_pnl_per_trade",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "median_net_pnl_per_trade",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "average_percentage_return",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "median_percentage_return",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "largest_win",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "largest_loss",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "average_winning_trade",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "average_losing_trade",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "average_daily_pnl",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "average_weekly_pnl",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "average_monthly_pnl",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "profit_per_share",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "pnl_by_direction",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "pnl_before_fees",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "pnl_after_fees",
    "categoryFile": "02-metrics-profit-loss.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "trade_count",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "winning_trades",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "losing_trades",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "breakeven_trades",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "open_trades",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "closed_trades",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "win_rate",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts",
      "current_dashboard_analytics_reads"
    ]
  },
  {
    "canonicalName": "loss_rate",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "breakeven_rate",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "green_days",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "red_days",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "flat_days",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "percentage_of_profitable_days",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "consecutive_wins",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "consecutive_losses",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "maximum_win_streak",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "maximum_loss_streak",
    "categoryFile": "03-metrics-outcomes.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "expectancy",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts",
      "current_dashboard_analytics_reads"
    ]
  },
  {
    "canonicalName": "profit_factor",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "payoff_ratio",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "average_win_to_average_loss_ratio",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "median_win_to_median_loss_ratio",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "consistency",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "return_dispersion",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "standard_deviation",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "percentage_of_total_profit_from_top_trades",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "percentage_of_total_loss_from_worst_trades",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "dependency_on_outliers",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "results_excluding_best_trade",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "results_excluding_worst_trade",
    "categoryFile": "04-metrics-edge-quality.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "total_commissions",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "total_regulatory_fees",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "total_transaction_costs",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "fees_per_trade",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "fees_per_share",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "fees_as_percentage_of_gross_profit",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "trades_turned_from_green_to_red_by_fees",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "fee_impact_on_expectancy",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "fee_impact_by_broker",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "fee_completeness",
    "categoryFile": "05-metrics-fees-costs.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "shares_purchased",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "shares_sold",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "average_position_size",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "median_position_size",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "maximum_position_size",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "average_dollar_exposure",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "maximum_dollar_exposure",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "size_relative_to_normal_size",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "performance_by_size_bucket",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "size_after_wins",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "size_after_losses",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "size_escalation",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "size_reduction",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "profit_per_dollar_exposed",
    "categoryFile": "06-metrics-position-size.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "entry_time",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "exit_time",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "hold_duration",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "average_hold_duration",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "median_hold_duration",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "time_to_first_exit",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "session",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "weekday",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "week",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "month",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "quarter",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "year",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Supported",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "days_held",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "trades_per_day",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "time_between_trades",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "time_after_previous_loss",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "time_after_previous_win",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "first_trade_time",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "last_trade_time",
    "categoryFile": "07-metrics-time-duration.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "number_of_entries",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "number_of_exits",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "average_entry_price",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "average_exit_price",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "weighted_average_entry_price",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "weighted_average_exit_price",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "entry_execution_count",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "exit_execution_count",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "scale_in_count",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "scale_out_count",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "partial_exit_percentage",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "position_flips",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "repeat_attempts",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "trade_sequence",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "average_shares_per_execution",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "execution_duration",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "entry_to_exit_quantity_reconciliation",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "unmatched_executions",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "remaining_open_quantity",
    "categoryFile": "08-metrics-execution.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "overtrading_frequency",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "fourth_or_later_performance",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "performance_after_a_loss",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "performance_after_two_losses",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "performance_after_a_win",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "performance_after_a_large_win",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "performance_after_a_large_loss",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "repeat_attempt_performance",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "loss_chasing_proxy",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "size_increase_after_losses",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "shortened_wait_time_after_losses",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "profit_giveback",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "saved_trade_analyzer_reads"
    ]
  },
  {
    "canonicalName": "daily_loss_limit_violations",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "continued_trading_after_profit_target",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "continued_trading_after_stop_threshold",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "time_cutoff_violations",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "rule_adherence",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "mistake_frequency",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "mistake_cost",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "setup_discipline",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "plan_adherence",
    "categoryFile": "09-metrics-behaviour.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "mfe",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "saved_trade_analyzer_reads"
    ]
  },
  {
    "canonicalName": "mae",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "saved_trade_analyzer_reads"
    ]
  },
  {
    "canonicalName": "profit_giveback",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "saved_trade_analyzer_reads"
    ]
  },
  {
    "canonicalName": "maximum_favourable_price",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "maximum_adverse_price",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "percentage_of_available_move_captured",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "entry_distance_from_vwap",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "entry_distance_from_high_of_day",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "entry_distance_from_low_of_day",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "volume_at_entry",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "relative_volume",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "price_change_after_entry",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "time_to_maximum_favourable_excursion",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "time_to_maximum_adverse_excursion",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "recovery_to_entry",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "post_exit_continuation",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "stop_distance",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "target_distance",
    "categoryFile": "10-metrics-candle-analytics.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "user",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "account",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "current_product_status_reads"
    ]
  },
  {
    "canonicalName": "broker",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "import_source",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "current_product_status_reads"
    ]
  },
  {
    "canonicalName": "currency",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "current_product_status_reads"
    ]
  },
  {
    "canonicalName": "instrument_type",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "ticker",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "exchange",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "trade_id",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "journal_entry_id",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "execution_id",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "import_batch",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "exact_date",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "date_range",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "today",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "yesterday",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "this_week",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "last_week",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "this_month",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "last_month",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "this_year",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "rolling_number_of_days",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "last_number_of_trades",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "before_or_after_a_time",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "between_two_times",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "premarket",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "regular_session",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "after_hours",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "weekday",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "month",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "quarter",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "year",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "closed_trade_facts"
    ]
  },
  {
    "canonicalName": "earnings_period_if_supplied_by_external_data",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "custom_trading_session",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "entry_price",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "exit_price",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "lowest_execution_price",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "highest_execution_price",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "trade_price_range",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "stocks_under_a_price",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "stocks_over_a_price",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "price_buckets",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "penny_stocks_where_explicitly_defined",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "sub_dollar_stocks",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "average_entry_cost",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "winning",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "losing",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "breakeven",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "open",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "current_dashboard_journal_reads"
    ]
  },
  {
    "canonicalName": "closed",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "current_dashboard_journal_reads"
    ]
  },
  {
    "canonicalName": "gross_winner",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "net_winner",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "gross_winner_turned_into_net_loser_by_fees",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "reached_green_then_closed_red",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "recovered",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "did_not_recover",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "long",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "short",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "buy_to_open",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "sell_to_open",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "mixed_or_flipped_position",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "unknown_direction",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "share_size_range",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "dollar_size_range",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "size_bucket",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "size_relative_to_personal_median",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "size_relative_to_recent_baseline",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "largest_positions",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "smallest_positions",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "first_trade_of_the_day",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "second_trade",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "third_trade",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "fourth_or_later_trade",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "first_attempt_on_ticker",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "second_attempt",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "third_attempt",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "fourth_or_later_attempt",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "trade_after_win",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "trade_after_loss",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "trade_after_two_losses",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "trade_during_a_winning_streak",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "trade_during_a_losing_streak",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "trade_after_daily_target_reached",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "trade_after_daily_loss_threshold_reached",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "setup",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "strategy",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "playbook",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "custom_tag",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "journal_period_context",
      "trading_rule_and_tag_reads"
    ]
  },
  {
    "canonicalName": "mistake",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "emotion",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "rule",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "journal_period_context",
      "trading_rule_and_tag_reads"
    ]
  },
  {
    "canonicalName": "rule_followed",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "rule_broken",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "confidence_rating",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "quality_rating",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "notes_present",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "journal_period_context"
    ]
  },
  {
    "canonicalName": "notes_missing",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "screenshot_present",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "screenshot_missing",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "planned_trade",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "unplanned_trade",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "reviewed",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "not_reviewed",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "scalp",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "intraday",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "overnight",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "swing",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": [
      "current_dashboard_journal_reads"
    ]
  },
  {
    "canonicalName": "custom_duration",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "under_a_number_of_minutes",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "over_a_number_of_minutes",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "duration_buckets",
    "categoryFile": "11-dimensions.md",
    "sourceCapabilityStatus": "Unavailable",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "equality",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "inequality",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "greater_than",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "greater_than_or_equal",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "less_than",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "less_than_or_equal",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "range",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "inclusion",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "exclusion",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "membership",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "text_search",
    "categoryFile": "12-operators.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "calendar_dates",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "relative_dates",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "trading_dates",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "rolling_windows",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "record_count_windows",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "session_times",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "display_timezone",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "account_timezone",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "daily_trade_tracker_eastern_market_time",
    "categoryFile": "13-date-time-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "best",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "worst",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "top",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "bottom",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "most_profitable",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "least_profitable",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "biggest",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "smallest",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "most_consistent",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "most_frequent",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "most_costly",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "highest_win_rate",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "lowest_expectancy",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "better_than",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "worse_than",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "improved",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "declined",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "more_profitable",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "less_consistent",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "larger_losses",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "smaller_positions",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "higher_frequency",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "before_versus_after",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "current_versus_previous",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "selected_trade_versus_similar_trades",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "one_ticker_versus_all_other_tickers",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "tagged_versus_untagged",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "followed_rule_versus_broke_rule",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "superlative_and_extremum_questions",
    "categoryFile": "14-comparison-ranking-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "last_intent",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "last_metric_or_metric_set",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "active_date_range",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "journal_period_context",
      "saved_ai_review_follow_up"
    ]
  },
  {
    "canonicalName": "active_filters",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "active_comparison",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "active_grouping",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "selected_trade",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "current_dashboard_journal_reads",
      "saved_trade_analyzer_reads",
      "trading_rule_and_tag_reads"
    ]
  },
  {
    "canonicalName": "selected_ticker",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "current_dashboard_analytics_reads",
      "current_dashboard_journal_reads"
    ]
  },
  {
    "canonicalName": "selected_journal_entry",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "current_dashboard_journal_reads",
      "daily_tracker_drafts",
      "journal_period_context",
      "saved_ai_review_follow_up"
    ]
  },
  {
    "canonicalName": "current_account",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "confirmed_product_changes",
      "current_dashboard_journal_reads",
      "current_product_status_reads",
      "daily_tracker_drafts",
      "manual_execution_drafts",
      "review_delivery_draft"
    ]
  },
  {
    "canonicalName": "response_detail_level",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "unresolved_ambiguity",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "filter_modification",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "time_modification",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "metric_modification",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "grouping_modification",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "detail_modification",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "saved_ai_review_follow_up"
    ]
  },
  {
    "canonicalName": "comparison_continuation",
    "categoryFile": "15-context-conversation-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "trade_outcome_vocabulary",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "trading_frequency_vocabulary",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "profit_giveback_vocabulary",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "repeat_trading_vocabulary",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "position_size_vocabulary",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "price_terms_vocabulary",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "user_tag_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "trading_rule_and_tag_reads"
    ]
  },
  {
    "canonicalName": "user_setup_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "user_strategy_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "user_rule_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": [
      "trading_rule_and_tag_reads"
    ]
  },
  {
    "canonicalName": "user_mistake_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "user_playbook_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "user_session_name_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "user_price_bucket_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "user_goal_language",
    "categoryFile": "16-trader-terminology-slang.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "best_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "worst_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "better_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "profit_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "size_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "risk_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "later_trades_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "recent_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "cheap_stocks_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "scalp_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "overtrading_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "good_trade_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "bad_trade_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "normal_size_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "large_loss_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "performance_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "consistency_ambiguity",
    "categoryFile": "17-ambiguity-language.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "brief",
    "categoryFile": "18-response-preferences.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "standard",
    "categoryFile": "18-response-preferences.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "detailed",
    "categoryFile": "18-response-preferences.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "table",
    "categoryFile": "18-response-preferences.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "coach",
    "categoryFile": "18-response-preferences.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "audit",
    "categoryFile": "18-response-preferences.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "deterministic_truth_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "server_authoritative_scope_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "privacy_minimization_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "evidence_and_coverage_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "missing_data_no_invention_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "unsupported_request_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "causation_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "prediction_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "advice_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "protected_action_confirmation_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "untrusted_content_policy",
    "categoryFile": "19-language-policies.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "canonical_question_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "paraphrase_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "misspelling_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "shorthand_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "multi_part_request_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "follow_up_context_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "negation_scope_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "ambiguity_handling_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "adversarial_language_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  },
  {
    "canonicalName": "cross_category_combination_coverage",
    "categoryFile": "20-evaluation-suite.md",
    "sourceCapabilityStatus": "Planned",
    "runtimeCapabilityIds": []
  }
]) satisfies readonly CoachAiChatLanguageInventoryEntry[];

export const coachAiChatRuntimeCapabilityCoverage = Object.freeze([
  {
    "runtimeCapabilityId": "closed_trade_facts",
    "canonicalNames": [
      "retrieve_records",
      "summarize_performance",
      "calculate_metric",
      "compare_groups",
      "group_and_aggregate",
      "rank_results",
      "explain_result",
      "gross_profit",
      "gross_loss",
      "gross_pnl",
      "net_pnl",
      "average_net_pnl_per_trade",
      "median_net_pnl_per_trade",
      "largest_win",
      "largest_loss",
      "average_winning_trade",
      "average_losing_trade",
      "pnl_by_direction",
      "pnl_before_fees",
      "pnl_after_fees",
      "trade_count",
      "winning_trades",
      "losing_trades",
      "breakeven_trades",
      "closed_trades",
      "win_rate",
      "loss_rate",
      "breakeven_rate",
      "expectancy",
      "profit_factor",
      "week",
      "month",
      "year"
    ],
    "representativeFixtures": [
      {
        "id": "runtime-closed-trades-summary",
        "surface": "Completed-trade facts",
        "input": "Show my selected-period gross P and L and win rate for ready-closed trades.",
        "expectedRoute": "bounded completed-trade summary",
        "expectedKind": "factual_read",
        "expectedFactualToolNames": [
          "summarize_closed_trades",
          "group_closed_trades",
          "list_closed_trades",
          "get_closed_trade_details"
        ]
      }
    ]
  },
  {
    "runtimeCapabilityId": "daily_tracker_drafts",
    "canonicalNames": [
      "assist_journaling",
      "assist_daily_review",
      "selected_journal_entry",
      "current_account"
    ],
    "representativeFixtures": [
      {
        "id": "runtime-daily-tracker-draft",
        "surface": "Daily Trade Tracker",
        "input": "Draft a note for this trading day from the facts I supplied; do not save it.",
        "expectedRoute": "Daily Tracker editable draft and confirmation gate",
        "expectedKind": "confirmed_draft",
        "expectedFactualToolNames": []
      }
    ]
  },
  {
    "runtimeCapabilityId": "manual_execution_drafts",
    "canonicalNames": [
      "prepare_manual_execution_draft",
      "current_account"
    ],
    "representativeFixtures": [
      {
        "id": "runtime-manual-execution-draft",
        "surface": "Daily and Swing Trackers",
        "input": "Prepare a manual execution draft from the exact date, Eastern time, ticker, side, quantity, and price I supplied.",
        "expectedRoute": "canonical manual-entry preview and confirmation gate",
        "expectedKind": "confirmed_draft",
        "expectedFactualToolNames": []
      }
    ]
  },
  {
    "runtimeCapabilityId": "review_delivery_draft",
    "canonicalNames": [
      "prepare_user_setting_change",
      "current_account"
    ],
    "representativeFixtures": [
      {
        "id": "runtime-ai-review-delivery",
        "surface": "Account AI",
        "input": "Change my AI Review delivery to Sunday evening Eastern and show the exact draft first.",
        "expectedRoute": "AI Review delivery draft and confirmation gate",
        "expectedKind": "confirmed_draft",
        "expectedFactualToolNames": []
      }
    ]
  },
  {
    "runtimeCapabilityId": "journal_period_context",
    "canonicalNames": [
      "retrieve_records",
      "selected_journal_entry",
      "rule",
      "custom_tag",
      "notes_present",
      "active_date_range"
    ],
    "representativeFixtures": [
      {
        "id": "runtime-journal-period-context",
        "surface": "Calendar and Daily Tracker",
        "input": "Summarize this saved trading week with its rules, focuses, notes, and tags.",
        "expectedRoute": "bounded Journal day, week, or month context",
        "expectedKind": "factual_read",
        "expectedFactualToolNames": [
          "summarize_journal_period"
        ]
      }
    ]
  },
  {
    "runtimeCapabilityId": "saved_ai_review_follow_up",
    "canonicalNames": [
      "explain_result",
      "detail_modification",
      "active_date_range",
      "selected_journal_entry"
    ],
    "representativeFixtures": [
      {
        "id": "runtime-saved-ai-review-follow-up",
        "surface": "Workspace and AI Reviews",
        "input": "Explain the saved two-week AI Review and keep its original period separate from later trading.",
        "expectedRoute": "saved weekly, two-week, or monthly AI Review read",
        "expectedKind": "factual_read",
        "expectedFactualToolNames": [
          "list_saved_ai_reviews",
          "get_saved_ai_review"
        ]
      }
    ]
  },
  {
    "runtimeCapabilityId": "product_help",
    "canonicalNames": [
      "product_help",
      "explain_concept"
    ],
    "representativeFixtures": [
      {
        "id": "runtime-product-help",
        "surface": "Help Center and Whop access",
        "input": "How do TraderLink AI Reviews and paid-plan access work?",
        "expectedRoute": "maintained Help Center search",
        "expectedKind": "factual_read",
        "expectedFactualToolNames": [
          "search_product_help"
        ]
      }
    ]
  },
  {
    "runtimeCapabilityId": "current_dashboard_journal_reads",
    "canonicalNames": [
      "retrieve_records",
      "analyze_trade",
      "selected_trade",
      "selected_ticker",
      "selected_journal_entry",
      "open",
      "closed",
      "swing",
      "current_account"
    ],
    "representativeFixtures": [
      {
        "id": "runtime-dashboard-journal-reads",
        "surface": "Workspace, Calendar, Daily and Swing Trackers",
        "input": "Show the current saved status and annotations for this selected Swing position.",
        "expectedRoute": "current account-scoped dashboard Journal read",
        "expectedKind": "factual_read",
        "expectedFactualToolNames": [
          "get_workspace_summary",
          "get_trading_day_details",
          "get_calendar_period",
          "list_open_positions",
          "get_open_position_details",
          "list_swing_positions",
          "get_swing_position_details"
        ]
      }
    ]
  },
  {
    "runtimeCapabilityId": "current_dashboard_analytics_reads",
    "canonicalNames": [
      "summarize_performance",
      "calculate_metric",
      "compare_groups",
      "group_and_aggregate",
      "rank_results",
      "gross_pnl",
      "net_pnl",
      "win_rate",
      "expectancy",
      "selected_ticker"
    ],
    "representativeFixtures": [
      {
        "id": "runtime-dashboard-analytics-reads",
        "surface": "Analytics and Trade Explorer",
        "input": "Compare ready-closed gross P and L by ticker in the selected period and show bounded supporting trades.",
        "expectedRoute": "canonical analytics page read or bounded versioned Trade Explorer query",
        "expectedKind": "factual_read",
        "expectedFactualToolNames": [
          "get_analytics_overview",
          "get_results_by_ticker",
          "get_timing_analytics",
          "get_execution_analytics",
          "query_trade_explorer"
        ]
      }
    ]
  },
  {
    "runtimeCapabilityId": "current_product_status_reads",
    "canonicalNames": [
      "inspect_data_quality",
      "import_source",
      "account",
      "current_account",
      "currency"
    ],
    "representativeFixtures": [
      {
        "id": "runtime-product-status-reads",
        "surface": "Imports, Data Decisions, Notifications, Account and Moomoo",
        "input": "Show the privacy-safe status of my imports, unresolved decisions, notifications, and automatic-import setup.",
        "expectedRoute": "bounded current-product status read without raw statement or credential data",
        "expectedKind": "factual_read",
        "expectedFactualToolNames": [
          "list_imports",
          "list_data_decisions",
          "get_data_decision_details",
          "list_notifications",
          "get_account_profile",
          "get_account_trading",
          "get_account_preferences",
          "get_account_ai_plan"
        ]
      }
    ]
  },
  {
    "runtimeCapabilityId": "saved_trade_analyzer_reads",
    "canonicalNames": [
      "analyze_trade",
      "mfe",
      "mae",
      "profit_giveback",
      "selected_trade"
    ],
    "representativeFixtures": [
      {
        "id": "runtime-saved-trade-analyzer",
        "surface": "Trade Analyzer and Candle Review",
        "input": "Explain the saved MFE, MAE, and Candle Review facts for this selected analyzed trade.",
        "expectedRoute": "saved Analyzer or Candle Review read; no market-data refresh",
        "expectedKind": "factual_read",
        "expectedFactualToolNames": [
          "get_trade_analyzer_results",
          "list_analyzed_trades",
          "get_saved_candle_review"
        ]
      }
    ]
  },
  {
    "runtimeCapabilityId": "trading_rule_and_tag_reads",
    "canonicalNames": [
      "evaluate_rule",
      "rule",
      "custom_tag",
      "user_rule_language",
      "user_tag_language",
      "selected_trade"
    ],
    "representativeFixtures": [
      {
        "id": "runtime-rules-tags",
        "surface": "Trading Rules and Trade Tags",
        "input": "Show the exact saved rule results, tags, and note for this completed trade without inferring why it happened.",
        "expectedRoute": "saved rule, annotation, and review evidence read",
        "expectedKind": "factual_read",
        "expectedFactualToolNames": [
          "list_trading_rules",
          "get_trading_rule_results",
          "get_trade_annotations"
        ]
      }
    ]
  },
  {
    "runtimeCapabilityId": "confirmed_product_changes",
    "canonicalNames": [
      "prepare_user_setting_change",
      "assist_journaling",
      "evaluate_rule",
      "prepare_manual_execution_draft",
      "current_account"
    ],
    "representativeFixtures": [
      {
        "id": "runtime-action-reporting-currency",
        "surface": "Account preferences",
        "input": "Prepare a reporting-currency change and show the exact before and after values.",
        "expectedRoute": "reporting-currency draft with stale-value check",
        "expectedKind": "confirmed_draft",
        "expectedFactualToolNames": [],
        "expectedActionDraftKind": "reporting_currency"
      },
      {
        "id": "runtime-action-mark-notification-read",
        "surface": "Notifications",
        "input": "Prepare marking this exact notification as read; do not change it until I confirm.",
        "expectedRoute": "one current notification read-state draft",
        "expectedKind": "confirmed_draft",
        "expectedFactualToolNames": [],
        "expectedActionDraftKind": "mark_notification_read"
      },
      {
        "id": "runtime-action-select-journal-account",
        "surface": "Account trading",
        "input": "Prepare switching to the exact current Journal account I selected.",
        "expectedRoute": "current account-selection draft",
        "expectedKind": "confirmed_draft",
        "expectedFactualToolNames": [],
        "expectedActionDraftKind": "select_journal_account"
      },
      {
        "id": "runtime-action-create-journal-account",
        "surface": "Account trading",
        "input": "Prepare a new Trade Tracker account with the exact name, currency, and timezone I supplied.",
        "expectedRoute": "validated account-creation draft",
        "expectedKind": "confirmed_draft",
        "expectedFactualToolNames": [],
        "expectedActionDraftKind": "create_journal_account"
      },
      {
        "id": "runtime-action-swing-note",
        "surface": "Swing Tracker",
        "input": "Prepare this dated Swing note from my exact text and show it before saving.",
        "expectedRoute": "revision-protected Swing-note draft",
        "expectedKind": "confirmed_draft",
        "expectedFactualToolNames": [],
        "expectedActionDraftKind": "swing_note"
      },
      {
        "id": "runtime-action-trade-style",
        "surface": "Open Positions and Swing Tracker",
        "input": "Prepare the exact trader-selected position type change and wait for confirmation.",
        "expectedRoute": "revision-protected position-style draft",
        "expectedKind": "confirmed_draft",
        "expectedFactualToolNames": [],
        "expectedActionDraftKind": "trade_style"
      },
      {
        "id": "runtime-action-notification-preferences",
        "surface": "Notifications",
        "input": "Prepare my exact Discord notification preference change; do not save it yet.",
        "expectedRoute": "notification-preference draft",
        "expectedKind": "confirmed_draft",
        "expectedFactualToolNames": [],
        "expectedActionDraftKind": "notification_preferences"
      },
      {
        "id": "runtime-action-ai-review-setting",
        "surface": "Account AI",
        "input": "Prepare the exact AI Review enabled-setting change and show the preview.",
        "expectedRoute": "AI Review setting draft",
        "expectedKind": "confirmed_draft",
        "expectedFactualToolNames": [],
        "expectedActionDraftKind": "ai_review_account_setting"
      },
      {
        "id": "runtime-action-ai-review-request",
        "surface": "AI Reviews",
        "input": "Prepare a request for this exact available two-week AI Review period.",
        "expectedRoute": "eligible review-request draft",
        "expectedKind": "confirmed_draft",
        "expectedFactualToolNames": [],
        "expectedActionDraftKind": "ai_review_request"
      },
      {
        "id": "runtime-action-trade-tags",
        "surface": "Trade Tags",
        "input": "Prepare replacing the tags on this exact completed trade with my supplied saved tags.",
        "expectedRoute": "current-tag and catalog-revision draft",
        "expectedKind": "confirmed_draft",
        "expectedFactualToolNames": [],
        "expectedActionDraftKind": "trade_tags"
      },
      {
        "id": "runtime-action-trading-rule",
        "surface": "Trading Rules",
        "input": "Prepare the exact saved Trading Rule change and show the before and after rule details.",
        "expectedRoute": "validated Trading Rule draft",
        "expectedKind": "confirmed_draft",
        "expectedFactualToolNames": [],
        "expectedActionDraftKind": "rule_change"
      },
      {
        "id": "runtime-action-data-decision",
        "surface": "Data Decisions",
        "input": "Prepare the exact supported resolution for this one pending Data Decision from its returned evidence.",
        "expectedRoute": "one current Data Decision draft",
        "expectedKind": "confirmed_draft",
        "expectedFactualToolNames": [],
        "expectedActionDraftKind": "data_decision"
      }
    ]
  }
]) satisfies readonly CoachAiChatRuntimeCapabilityCoverage[];
