import Button from "@mui/material/Button";
import Chip from "@mui/material/Chip";
import Grid from "@mui/material/Grid";
import LinearProgress from "@mui/material/LinearProgress";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import { notFound } from "next/navigation";

import { DashboardPage, DashboardPanel } from "@/app/dashboard-ui";
import { loadCommunityDashboard } from "../../../community-dashboard-loader";
import { requestCommunityCoachingAction } from "../../../community-actions";

export default async function CommunityCoachPage({params}:{params:Promise<{communitySlug:string;coachSlug:string}>}){const {communitySlug,coachSlug}=await params;const loaded=await loadCommunityDashboard(communitySlug);const coach=loaded.snapshot.coaches.find(item=>item.slug===coachSlug);if(!coach)notFound();const plans=loaded.snapshot.plans.filter(plan=>plan.coachProfileId===coach.coachProfileId);return <DashboardPage><Typography component="a" href={`/communities/${communitySlug}/coaches`} sx={{color:"primary.main",fontWeight:800,textDecoration:"none"}}>← Back to coaches</Typography><Grid container spacing={2}><Grid size={{xs:12,lg:5}}><DashboardPanel hideHeader><Stack spacing={1.5}><Stack direction="row" sx={{justifyContent:"space-between"}}><Typography component="h1" variant="h1">{coach.displayName}</Typography><Chip color={coach.activeStudents<coach.capacity?"success":"default"} label={coach.activeStudents<coach.capacity?"Accepting students":"At capacity"}/></Stack><Typography color="primary.main" style={{fontWeight:800}}>{coach.headline}</Typography><Typography sx={{lineHeight:1.7}}>{coach.biography}</Typography><Typography style={{fontWeight:800}}>How coaching is provided</Typography><Typography color="text.secondary">{coach.deliverySummary}</Typography><LinearProgress value={Math.min(100,coach.activeStudents/coach.capacity*100)} variant="determinate"/><Typography color="text.secondary" variant="caption">{coach.activeStudents} of {coach.capacity} places filled</Typography></Stack></DashboardPanel></Grid><Grid size={{xs:12,lg:7}}><DashboardPanel title="Plans offered in this server"><Stack spacing={2}>{plans.map(plan=><Stack key={plan.planId} sx={{border:1,borderColor:"divider",borderRadius:2,p:2}} spacing={1}><Stack direction="row" sx={{justifyContent:"space-between"}}><Typography variant="h2">{plan.name}</Typography><Typography color="primary.main" style={{fontWeight:900}}>{plan.priceLabel}</Typography></Stack><Typography color="text.secondary" variant="body2">{plan.description}</Typography><Typography variant="body2">{plan.paymentInstructions}</Typography><form action={loaded.isReview?undefined:requestCommunityCoachingAction}><input name="communitySlug" type="hidden" value={communitySlug}/><input name="planId" type="hidden" value={plan.planId}/><Button disabled={loaded.isReview||coach.activeStudents>=coach.capacity} type="submit" variant="contained">Request coaching</Button></form></Stack>)}</Stack></DashboardPanel></Grid></Grid><Typography color="text.secondary" variant="caption">Payments and service arrangements are handled by the coach and Discord community. TraderLink takes no launch coaching payment or commission.</Typography></DashboardPage>}
