import Button from "@mui/material/Button";
import MenuItem from "@mui/material/MenuItem";
import Stack from "@mui/material/Stack";
import TextField from "@mui/material/TextField";
import Typography from "@mui/material/Typography";

import { DashboardPage, DashboardPanel, DashboardUnavailableState } from "@/app/dashboard-ui";
import { requireTraderLinkPlatformServerComponentPageIdentity } from "@/src/modules/platform/server/authentication/require-platform-request-scope";
import { withReadonlyPlatformDatabase } from "@/src/modules/platform/server/database/open-readonly-platform-database";
import { onboardDiscordCommunityAction } from "../onboarding-actions";

export default async function CommunityOnboardingPage(){const identity=await requireTraderLinkPlatformServerComponentPageIdentity(); const guilds=withReadonlyPlatformDatabase({},database=>database.prepare(`SELECT discord_guild_id guildId,guild_name guildName FROM traderlink_community_discord_guild_candidates WHERE user_id=? AND guild_owner=1 ORDER BY guild_name`).all(identity.scope.userId) as {guildId:string;guildName:string}[]); return <DashboardPage><Typography component="h1" variant="h1">Connect a Discord community</Typography><DashboardPanel title="Server owner setup">{guilds.length?<form action={onboardDiscordCommunityAction}><Stack spacing={2}><TextField label="Discord server" name="discordGuildId" select required>{guilds.map(g=><MenuItem key={g.guildId} value={g.guildId}>{g.guildName}</MenuItem>)}</TextField><TextField label="Community name" name="displayName" required/><TextField helperText="Used in the private TraderLink URL" label="URL name" name="slug" placeholder="momentum-trading-room" required/><Button type="submit" variant="contained">Connect server</Button></Stack></form>:<DashboardUnavailableState actionHref="/api/auth/discord/login?prompt=consent&returnTo=%2Fcommunities%2Fonboarding" actionLabel="Refresh Discord servers" description="Sign in again so TraderLink can verify which Discord servers you own. TraderLink does not store your Discord access token." title="No owned Discord server verified"/>}</DashboardPanel><DashboardPanel title="What happens next"><Typography variant="body2">Every verified member of this server can use TraderLink. You decide which Discord roles can open your alerts, watchlists, and coaching. Payments stay in Discord or with the provider you choose.</Typography></DashboardPanel></DashboardPage>}
