"use client";
import {Box,Button,Chip,Grid,Stack,TextField} from "@mui/material";
import {DashboardPanel} from "@/app/dashboard-ui";
import type {TraderLinkCommunityDashboardSnapshot} from "@/src/modules/communities/contracts/traderlink-community-platform-contracts";
import {saveCommunityCoachAction,setCoachingRelationshipStatusAction,updateCommunityCoachingPlanStatusAction} from "./community-actions";
import {CoachWorkspaceNavigation} from "./coach-workspace-navigation";
import {CoachingPlanBuilder} from "./coaching-plan-builder";
import MuiTypography from "@mui/material/Typography";
import type {TypographyProps} from "@mui/material/Typography";

function Typography({fontWeight,style,...props}:TypographyProps&{fontWeight?:number}){return <MuiTypography {...props} style={{...style,fontWeight}}/>}

export function CoachSetupPage({snapshot,isReview=false}:{snapshot:TraderLinkCommunityDashboardSnapshot;isReview?:boolean}){
 const profile=snapshot.coaches.find(item=>item.userId===snapshot.viewer.userId); const plans=profile?snapshot.plans.filter(item=>item.coachProfileId===profile.coachProfileId):[]; const requests=snapshot.relationships.filter(item=>item.coachUserId===snapshot.viewer.userId&&item.status==="pending");
 return <><CoachWorkspaceNavigation slug={snapshot.community.slug}/><Grid container spacing={2}><Grid size={{xs:12,lg:5}}><DashboardPanel title="Coach profile"><Box action={isReview?undefined:saveCommunityCoachAction} component="form"><input name="communitySlug" type="hidden" value={snapshot.community.slug}/><input name="capacity" type="hidden" value="10000"/><Stack spacing={1}><TextField defaultValue={profile?.displayName??snapshot.viewer.displayName} label="Coach name" name="displayName" required/><TextField defaultValue={profile?.headline} label="Headline" name="headline"/><TextField defaultValue={profile?.biography} label="About your coaching" minRows={3} multiline name="biography"/><TextField defaultValue={profile?.deliverySummary} label="How you coach" minRows={2} multiline name="deliverySummary"/><Button disabled={isReview} type="submit" variant="contained">Save coach profile</Button></Stack></Box></DashboardPanel></Grid><Grid size={{xs:12,lg:7}}><DashboardPanel title="Enrollment requests"><Stack spacing={1}>{requests.map(item=><Stack direction="row" key={item.relationshipId} sx={{alignItems:"center",justifyContent:"space-between"}}><Box><Typography fontWeight={800}>{item.studentDisplayName}</Typography><Typography color="text.secondary" variant="body2">{item.planName}</Typography></Box><Stack direction="row">{["active","declined"].map(status=><Box action={isReview?undefined:setCoachingRelationshipStatusAction} component="form" key={status}><input name="relationshipId" type="hidden" value={item.relationshipId}/><input name="status" type="hidden" value={status}/><Button disabled={isReview} type="submit">{status==="active"?"Accept":"Decline"}</Button></Box>)}</Stack></Stack>)}</Stack></DashboardPanel></Grid></Grid>
 {profile?<DashboardPanel title="Create coaching plan"><CoachingPlanBuilder coachProfileId={profile.coachProfileId} isReview={isReview} snapshot={snapshot}/></DashboardPanel>:null}
 <DashboardPanel title="Coaching plans"><Stack spacing={1}>{plans.map(plan=><Stack direction={{xs:"column",sm:"row"}} key={plan.planId} sx={{alignItems:{sm:"center"},justifyContent:"space-between",py:1}}><Box><Stack direction="row" spacing={1}><Typography fontWeight={800}>{plan.name}</Typography><Chip color={plan.status==="active"?"success":"warning"} label={plan.status==="active"?"Published":plan.status[0].toUpperCase()+plan.status.slice(1)} size="small"/></Stack><Typography color="text.secondary" variant="body2">{plan.quoteRequired?"Quote required":plan.priceLabel} · {plan.billingCadence.replace("_"," ")} · {plan.items.length} coaching items · {plan.studentCapacity} students</Typography><Typography color="text.secondary" variant="caption">Discord role {plan.requiredDiscordRoleId??"Not selected"}</Typography></Box><Box action={isReview?undefined:updateCommunityCoachingPlanStatusAction} component="form"><input name="communitySlug" type="hidden" value={snapshot.community.slug}/><input name="planId" type="hidden" value={plan.planId}/><Button disabled={isReview} name="status" type="submit" value={plan.status==="paused"?"active":"paused"}>{plan.status==="paused"?"Publish":"Pause"}</Button><Button color="error" disabled={isReview} name="status" type="submit" value="archived">Archive</Button></Box></Stack>)}</Stack></DashboardPanel></>;
}
