"use client";
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Chip from "@mui/material/Chip";
import Grid from "@mui/material/Grid";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import Link from "next/link";
import { DashboardMetricCard, DashboardPanel, DashboardUnavailableState } from "@/app/dashboard-ui";
import type { TraderLinkCommunityDashboardSnapshot } from "@/src/modules/communities/contracts/traderlink-community-platform-contracts";

export function CoachWorkspaceNavigation({slug}:{slug:string}){return <Stack direction={{xs:"column",sm:"row"}} spacing={1}><Button component={Link} href={`/communities/${slug}/workspace`}>Coaching work</Button><Button component={Link} href={`/communities/${slug}/workspace/students`}>Students</Button><Button component={Link} href={`/communities/${slug}/workspace/setup`}>Coach setup</Button></Stack>}

export function CoachingWorkPage({snapshot}:{snapshot:TraderLinkCommunityDashboardSnapshot}){const mine=new Set(snapshot.relationships.filter(x=>x.coachUserId===snapshot.viewer.userId).map(x=>x.relationshipId));const tasks=snapshot.coachingTasks.filter(x=>mine.has(x.relationshipId)&&x.status==="open");const reviews=snapshot.tradeReviews.filter(x=>mine.has(x.relationshipId)&&x.status!=="completed"&&x.status!=="cancelled");const messages=snapshot.coachingMessages.filter(x=>mine.has(x.relationshipId));return <><CoachWorkspaceNavigation slug={snapshot.community.slug}/><Grid container spacing={2}><Grid size={{xs:12,sm:4}}><DashboardMetricCard label="Open tasks" value={String(tasks.length)}/></Grid><Grid size={{xs:12,sm:4}}><DashboardMetricCard label="Trade reviews" value={String(reviews.length)}/></Grid><Grid size={{xs:12,sm:4}}><DashboardMetricCard label="Messages" value={String(messages.length)}/></Grid></Grid><Grid container spacing={2}><Grid size={{xs:12,lg:6}}><DashboardPanel title="Work queue"><Stack spacing={1}>{tasks.map(task=>{const relationship=snapshot.relationships.find(x=>x.relationshipId===task.relationshipId);return <Box key={task.taskId} sx={{borderBottom:1,borderColor:"divider",pb:1}}><Stack direction="row" sx={{justifyContent:"space-between"}}><Typography style={{fontWeight:800}}>{task.title}</Typography><Chip color={task.priority==="high"?"error":"default"} label={task.priority}/></Stack><Button component={Link} href={`/communities/${snapshot.community.slug}/workspace/students/${task.relationshipId}`}>{relationship?.studentDisplayName}</Button></Box>})}{!tasks.length?<DashboardUnavailableState compact description="" title="No open tasks"/>:null}</Stack></DashboardPanel></Grid><Grid size={{xs:12,lg:6}}><DashboardPanel title="Trade reviews"><Stack spacing={1}>{reviews.map(review=>{const relationship=snapshot.relationships.find(x=>x.relationshipId===review.relationshipId);return <Stack direction="row" key={review.reviewId} sx={{alignItems:"center",borderBottom:1,borderColor:"divider",justifyContent:"space-between",pb:1}}><Box><Typography style={{fontWeight:800}}>{review.title}</Typography><Typography color="text.secondary" variant="caption">{relationship?.studentDisplayName}</Typography></Box><Button component={Link} href={`/communities/${snapshot.community.slug}/workspace/students/${review.relationshipId}`}>Open</Button></Stack>})}{!reviews.length?<DashboardUnavailableState compact description="" title="No trade reviews"/>:null}</Stack></DashboardPanel></Grid></Grid></>}

export function StudentsPage({snapshot}:{snapshot:TraderLinkCommunityDashboardSnapshot}){const students=snapshot.relationships.filter(x=>x.coachUserId===snapshot.viewer.userId&&x.status==="active");return <><CoachWorkspaceNavigation slug={snapshot.community.slug}/><DashboardPanel title="Students"><Stack spacing={1}>{students.map(student=>{const tasks=snapshot.coachingTasks.filter(x=>x.relationshipId===student.relationshipId&&x.status==="open").length;const reviews=snapshot.tradeReviews.filter(x=>x.relationshipId===student.relationshipId&&x.status!=="completed"&&x.status!=="cancelled").length;const journal=snapshot.journalGrants.some(x=>x.relationshipId===student.relationshipId&&x.status==="active");return <Stack direction={{xs:"column",md:"row"}} key={student.relationshipId} sx={{alignItems:{md:"center"},borderBottom:1,borderColor:"divider",justifyContent:"space-between",py:1}}><Box><Typography style={{fontWeight:800}}>{student.studentDisplayName}</Typography><Typography color="text.secondary" variant="body2">{student.planName}</Typography></Box><Stack direction="row" spacing={1} sx={{alignItems:"center",flexWrap:"wrap"}}><Chip label={`${tasks} tasks`}/><Chip label={`${reviews} reviews`}/><Chip color={journal?"success":"default"} label={`Journal ${journal?"on":"off"}`}/><Button component={Link} href={`/communities/${snapshot.community.slug}/workspace/students/${student.relationshipId}`} variant="contained">Open student</Button></Stack></Stack>})}{!students.length?<DashboardUnavailableState compact description="" title="No active students"/>:null}</Stack></DashboardPanel></>}
