import Link from "next/link";
import {Box,Button,Chip,Grid,MenuItem,Stack,TextField,Typography} from "@mui/material";
import {DashboardMetricCard,DashboardPanel,DashboardUnavailableState} from "@/app/dashboard-ui";
import type {TraderLinkCommunityDashboardSnapshot} from "@/src/modules/communities/contracts/traderlink-community-platform-contracts";
import {createCommunityTeachingAction} from "./community-actions";
import {CoachWorkspaceNavigation} from "./coach-workspace-navigation";

const mine=(snapshot:TraderLinkCommunityDashboardSnapshot)=>new Set(snapshot.relationships.filter(item=>item.coachUserId===snapshot.viewer.userId).map(item=>item.relationshipId));

export function ReviewsPage({snapshot}:{snapshot:TraderLinkCommunityDashboardSnapshot}){const ids=mine(snapshot);const reviews=snapshot.tradeReviews.filter(item=>ids.has(item.relationshipId));return <><CoachWorkspaceNavigation slug={snapshot.community.slug}/><Grid container spacing={2}><Grid size={{xs:6,md:3}}><DashboardMetricCard label="Open" value={String(reviews.filter(item=>item.status!=="completed"&&item.status!=="cancelled").length)}/></Grid><Grid size={{xs:6,md:3}}><DashboardMetricCard label="Completed" value={String(reviews.filter(item=>item.status==="completed").length)}/></Grid><Grid size={{xs:6,md:3}}><DashboardMetricCard label="Period reviews" value={String(reviews.filter(item=>["weekly","monthly","general"].includes(item.reviewType)).length)}/></Grid><Grid size={{xs:6,md:3}}><DashboardMetricCard label="Trade sets" value={String(reviews.reduce((sum,item)=>sum+item.roundTripIds.length,0))}/></Grid></Grid><DashboardPanel title="Reviews"><Stack spacing={1.5}>{reviews.map(review=>{const student=snapshot.relationships.find(item=>item.relationshipId===review.relationshipId);return <Box key={review.reviewId} sx={{border:1,borderColor:"divider",borderRadius:2,p:2}}><Stack direction={{xs:"column",sm:"row"}} sx={{justifyContent:"space-between"}}><Box><Typography fontWeight={800}>{review.title}</Typography><Typography color="text.secondary" variant="body2">{student?.studentDisplayName} · {review.reviewType.replaceAll("_"," ")}</Typography></Box><Stack direction="row" spacing={1}><Chip color={review.status==="completed"?"success":"warning"} label={review.status}/><Button component={Link} href={`/communities/${snapshot.community.slug}/workspace/students/${review.relationshipId}`}>Open</Button></Stack></Stack>{review.periodStart?<Typography sx={{mt:1}} variant="body2">{review.periodStart} – {review.periodEnd}</Typography>:null}<Typography sx={{mt:1}} variant="body2">{review.studentContext}</Typography></Box>})}{!reviews.length?<DashboardUnavailableState compact description="" title="No reviews"/>:null}</Stack></DashboardPanel></>}

export function SessionsPage({snapshot}:{snapshot:TraderLinkCommunityDashboardSnapshot}){const ids=mine(snapshot);const sessions=snapshot.coachingSessions.filter(item=>ids.has(item.relationshipId));return <><CoachWorkspaceNavigation slug={snapshot.community.slug}/><DashboardPanel title="Sessions"><Stack spacing={1.5}>{sessions.map(session=>{const student=snapshot.relationships.find(item=>item.relationshipId===session.relationshipId);return <Box key={session.sessionId} sx={{border:1,borderColor:"divider",borderRadius:2,p:2}}><Stack direction={{xs:"column",sm:"row"}} sx={{justifyContent:"space-between"}}><Box><Typography fontWeight={800}>{session.title}</Typography><Typography color="text.secondary" variant="body2">{student?.studentDisplayName}{session.scheduledAtUtc?` · ${new Date(session.scheduledAtUtc).toLocaleString()}`:""}</Typography></Box><Chip color={session.status==="completed"?"success":"info"} label={session.status}/></Stack><Typography sx={{mt:1}} variant="body2">{session.agenda}</Typography>{session.notes?<Typography sx={{mt:1}} variant="body2">{session.notes}</Typography>:null}</Box>})}{!sessions.length?<DashboardUnavailableState compact description="" title="No sessions"/>:null}</Stack></DashboardPanel></>}

export function TeachingPage({snapshot,isReview}:{snapshot:TraderLinkCommunityDashboardSnapshot;isReview:boolean}){const students=snapshot.relationships.filter(item=>item.coachUserId===snapshot.viewer.userId&&item.status==="active");return <><CoachWorkspaceNavigation slug={snapshot.community.slug}/><Grid container spacing={2}><Grid size={{xs:12,lg:5}}><DashboardPanel title="Create"><Box action={isReview?undefined:createCommunityTeachingAction} component="form"><input name="communitySlug" type="hidden" value={snapshot.community.slug}/><Stack spacing={1.5}><TextField label="Title" name="title" required/><TextField defaultValue="lesson" label="Type" name="teachingType" select><MenuItem value="lesson">Lesson</MenuItem><MenuItem value="class">Class</MenuItem><MenuItem value="assignment">Assignment</MenuItem></TextField><TextField label="Content" minRows={4} multiline name="body"/><TextField label="Delivery link" name="deliveryUrl"/><TextField InputLabelProps={{shrink:true}} label="Schedule" name="scheduledAt" type="datetime-local"/><TextField defaultValue="all_students" label="Audience" name="audienceMode" select><MenuItem value="all_students">All students</MenuItem><MenuItem value="plan">Plan</MenuItem><MenuItem value="selected_students">Selected students</MenuItem></TextField><TextField label="Plan" name="planId" select><MenuItem value="">None</MenuItem>{snapshot.plans.map(plan=><MenuItem key={plan.planId} value={plan.planId}>{plan.name}</MenuItem>)}</TextField>{students.map(student=><label key={student.relationshipId}><input name="relationshipId" type="checkbox" value={student.relationshipId}/> {student.studentDisplayName}</label>)}<label><input defaultChecked name="publish" type="checkbox"/> Publish</label><Button disabled={isReview} type="submit" variant="contained">Save</Button></Stack></Box></DashboardPanel></Grid><Grid size={{xs:12,lg:7}}><DashboardPanel title="Lessons, classes and assignments"><Stack spacing={1.5}>{snapshot.teachingItems.map(item=><Box key={item.teachingId} sx={{border:1,borderColor:"divider",borderRadius:2,p:2}}><Stack direction="row" sx={{justifyContent:"space-between"}}><Typography fontWeight={800}>{item.title}</Typography><Chip color={item.teachingType==="class"?"secondary":item.teachingType==="assignment"?"warning":"info"} label={item.teachingType}/></Stack><Typography color="text.secondary" variant="body2">{item.students.length} students · {item.status}</Typography><Typography sx={{mt:1}} variant="body2">{item.body}</Typography></Box>)}</Stack></DashboardPanel></Grid></Grid></>}
