"use client";

import {useMemo,useState} from "react";
import {Box,Button,Checkbox,Chip,FormControlLabel,Grid,MenuItem,Stack,TextField,Typography} from "@mui/material";
import type {TraderLinkCommunityCoachingItemType,TraderLinkCommunityDashboardSnapshot} from "@/src/modules/communities/contracts/traderlink-community-platform-contracts";
import {createCommunityCoachingPlanAction} from "./community-actions";

const OFFER_ITEMS:readonly {type:TraderLinkCommunityCoachingItemType;label:string;trades?:boolean}[]=[
 {type:"trade_review",label:"Trade reviews",trades:true},{type:"trading_day_review",label:"Trading-day reviews",trades:true},{type:"performance_review",label:"Performance reviews"},{type:"journal_review",label:"Journal reviews"},{type:"rules_review",label:"Rules reviews"},{type:"strategy_review",label:"Strategy reviews"},{type:"risk_review",label:"Risk reviews"},{type:"goal_review",label:"Goal reviews"},{type:"student_check_in",label:"Student check-ins"},{type:"review_follow_up",label:"Review follow-ups"},{type:"private_session",label:"Private sessions"},{type:"group_lesson",label:"Group lessons"},{type:"questions",label:"Student questions"},{type:"custom_task",label:"Custom coaching work"},
];
const JOURNAL_SCOPES=["trades","trade_notes","rules","tags","analytics","open_positions","journal_notes","images"] as const;
const label=(value:string)=>value.split("_").map(word=>word[0]?.toUpperCase()+word.slice(1)).join(" ");

export function CoachingPlanBuilder({snapshot,coachProfileId,isReview=false}:{snapshot:TraderLinkCommunityDashboardSnapshot;coachProfileId:string;isReview?:boolean}){
 const [selected,setSelected]=useState<TraderLinkCommunityCoachingItemType[]>(["trade_review","performance_review","review_follow_up"]);
 const [quoteRequired,setQuoteRequired]=useState(false);
 const roles=useMemo(()=>Array.from(new Set([...snapshot.audiences.flatMap(item=>item.discordRoleIds),...snapshot.staffRoles.flatMap(item=>item.discordRoleIds)])),[snapshot]);
 const toggle=(type:TraderLinkCommunityCoachingItemType)=>setSelected(current=>current.includes(type)?current.filter(item=>item!==type):[...current,type]);
 return <Box action={isReview?undefined:createCommunityCoachingPlanAction} component="form">
  <input name="communitySlug" type="hidden" value={snapshot.community.slug}/><input name="coachProfileId" type="hidden" value={coachProfileId}/>
  <Stack spacing={3}>
   <Grid container spacing={2}>
    <Grid size={{xs:12,md:6}}><TextField fullWidth label="Plan name" name="name" required/></Grid>
    <Grid size={{xs:12,sm:6,md:3}}><TextField defaultValue="monthly" fullWidth label="Billing" name="billingCadence" select><MenuItem value="weekly">Weekly</MenuItem><MenuItem value="monthly">Monthly</MenuItem><MenuItem value="one_time">One-time</MenuItem><MenuItem value="custom">Custom</MenuItem></TextField></Grid>
    <Grid size={{xs:12,sm:6,md:3}}><TextField disabled={quoteRequired} fullWidth label="Price" name="price" slotProps={{htmlInput:{min:0,step:"0.01"}}} type="number"/></Grid>
    <Grid size={{xs:12,sm:6,md:3}}><TextField defaultValue="USD" fullWidth label="Currency" name="currency" select><MenuItem value="USD">USD</MenuItem><MenuItem value="CAD">CAD</MenuItem></TextField></Grid>
    <Grid size={{xs:12,sm:6,md:3}}><TextField defaultValue={10} fullWidth label="Student capacity" name="studentCapacity" required slotProps={{htmlInput:{min:1}}} type="number"/></Grid>
    <Grid size={{xs:12,md:6}}><TextField defaultValue={roles[0]??""} fullWidth label="Required Discord coaching role" name="requiredDiscordRoleId" required select={roles.length>0}>{roles.map(role=><MenuItem key={role} value={role}>{role}</MenuItem>)}</TextField></Grid>
    <Grid size={{xs:12}}><FormControlLabel control={<Checkbox checked={quoteRequired} name="quoteRequired" onChange={event=>setQuoteRequired(event.target.checked)}/>} label="Quote required"/></Grid>
   </Grid>
   <Box><Typography fontWeight={800} sx={{mb:1}}>Coaching included</Typography><Grid container spacing={1}>{OFFER_ITEMS.map(item=><Grid key={item.type} size={{xs:12,sm:6,lg:4}}><Button color={selected.includes(item.type)?"primary":"inherit"} fullWidth onClick={()=>toggle(item.type)} sx={{justifyContent:"space-between"}} variant={selected.includes(item.type)?"contained":"outlined"}>{item.label}<Chip color={selected.includes(item.type)?"success":"default"} label={selected.includes(item.type)?"Added":"Add"} size="small"/></Button><input checked={selected.includes(item.type)} name={`item:${item.type}`} onChange={()=>undefined} type="checkbox" hidden/>{selected.includes(item.type)?<Grid container spacing={1} sx={{mt:1}}><Grid size={6}><TextField defaultValue="weekly" fullWidth label="Frequency" name={`frequency:${item.type}`} select size="small"><MenuItem value="weekly">Weekly</MenuItem><MenuItem value="every_two_weeks">Every two weeks</MenuItem><MenuItem value="monthly">Monthly</MenuItem><MenuItem value="once">Once</MenuItem><MenuItem value="custom">Custom</MenuItem></TextField></Grid><Grid size={6}><TextField defaultValue={1} fullWidth label={item.trades?"Trades":"Items"} name={`quantity:${item.type}`} size="small" slotProps={{htmlInput:{min:1}}} type="number"/></Grid><Grid size={6}><TextField defaultValue="previous_7_days" fullWidth label="Covers" name={`coverage:${item.type}`} select size="small"><MenuItem value="single_item">One item</MenuItem><MenuItem value="previous_7_days">Previous 7 days</MenuItem><MenuItem value="since_last_review">Since last review</MenuItem><MenuItem value="calendar_week">Calendar week</MenuItem><MenuItem value="previous_month">Previous month</MenuItem><MenuItem value="custom">Custom</MenuItem></TextField></Grid><Grid size={6}><TextField defaultValue={2} fullWidth label="Due after (days)" name={`due:${item.type}`} size="small" slotProps={{htmlInput:{min:0}}} type="number"/></Grid>{item.trades?<Grid size={12}><TextField defaultValue="coach_or_student" fullWidth label="Trades chosen by" name={`selection:${item.type}`} select size="small"><MenuItem value="coach">Coach</MenuItem><MenuItem value="student">Student</MenuItem><MenuItem value="coach_or_student">Coach or student</MenuItem></TextField></Grid>:null}{item.type==="review_follow_up"?<Grid size={12}><TextField defaultValue={3} fullWidth label="Follow-up period (days)" name={`followUp:${item.type}`} size="small" slotProps={{htmlInput:{min:0}}} type="number"/></Grid>:null}</Grid>:null}</Grid>)}</Grid></Box>
   <Box><Typography fontWeight={800}>Required Journal access</Typography><Stack direction="row" flexWrap="wrap">{JOURNAL_SCOPES.map(scope=><FormControlLabel control={<Checkbox name="journalScope" value={scope}/>} key={scope} label={label(scope)}/>)}</Stack></Box>
   <Grid container spacing={2}><Grid size={{xs:12,md:6}}><TextField fullWidth label="What the student receives" minRows={3} multiline name="description"/></Grid><Grid size={{xs:12,md:6}}><TextField fullWidth label="Payment and Discord role instructions" minRows={3} multiline name="paymentInstructions"/></Grid><Grid size={{xs:12,md:4}}><TextField defaultValue="" fullWidth label="Archive paused students after" name="autoArchiveAfterDays" select><MenuItem value="">Never</MenuItem><MenuItem value="30">30 days</MenuItem><MenuItem value="60">60 days</MenuItem><MenuItem value="90">90 days</MenuItem></TextField></Grid></Grid>
   <Stack direction="row" justifyContent="flex-end" spacing={1}><Button disabled={isReview||selected.length===0} name="intent" type="submit" value="draft" variant="outlined">Save draft</Button><Button disabled={isReview||selected.length===0||roles.length===0} name="intent" type="submit" value="publish" variant="contained">Publish plan</Button></Stack>
  </Stack>
 </Box>;
}
