"use client";

import {useMemo,useState} from "react";
import Link from "next/link";
import {Box,Button,Chip,Grid,MenuItem,Stack,Table,TableBody,TableCell,TableContainer,TableHead,TableRow,TextField,ToggleButton,ToggleButtonGroup} from "@mui/material";
import {DashboardMetricCard as BaseMetric,DashboardPanel,DashboardUnavailableState} from "@/app/dashboard-ui";
import type {TraderLinkCommunityDashboardSnapshot} from "@/src/modules/communities/contracts/traderlink-community-platform-contracts";
import {CommunityTypography as Typography} from "./community-typography";

type View="upcoming"|"week"|"month"|"custom";
type Status="not_started"|"in_progress"|"delivered"|"completed"|"cancelled";
type Due="overdue"|"due_today"|"due_soon"|"scheduled"|"none";
type Item=Readonly<{id:string;student:string;plan:string;title:string;detail:string;type:"review"|"task"|"session"|"teaching";typeLabel:string;status:Status;dueAt:string|null;href:string}>;
const day=(date:Date)=>new Date(date.getFullYear(),date.getMonth(),date.getDate());
const plus=(date:Date,count:number)=>{const next=new Date(date);next.setDate(next.getDate()+count);return next};
const week=(date:Date)=>plus(day(date),-((date.getDay()+6)%7));
const label=(value:string)=>value.replaceAll("_"," ").replace(/\b\w/g,letter=>letter.toUpperCase());
const statusLabel=(value:Status)=>value==="not_started"?"Not started":value==="in_progress"?"In progress":label(value);
const dueLabel=(value:Due)=>value==="due_today"?"Due today":value==="due_soon"?"Due soon":value==="none"?"—":label(value);
const dueState=(value:string|null,now:Date):Due=>{if(!value)return "none";const due=day(new Date(value)),today=day(now);if(due<today)return "overdue";if(due.getTime()===today.getTime())return "due_today";return due<plus(today,4)?"due_soon":"scheduled"};
const dateLabel=(value:string|null)=>value?new Intl.DateTimeFormat("en",{month:"short",day:"numeric",year:"numeric"}).format(new Date(value)):"—";
const statusColor=(value:Status):"default"|"info"|"warning"|"success"=>value==="in_progress"?"warning":value==="delivered"||value==="completed"?"success":value==="not_started"?"info":"default";
const dueColor=(value:Due):"default"|"error"|"warning"|"info"=>value==="overdue"?"error":value==="due_today"||value==="due_soon"?"warning":value==="scheduled"?"info":"default";
const action=(item:Item)=>item.status==="in_progress"?(item.type==="review"?"Continue review":"Continue"):item.status==="not_started"?(item.type==="review"?"Start review":item.type==="session"?"Open session":item.type==="teaching"?`Open ${item.typeLabel.toLowerCase()}`:"Start"):"View";
function Metric(props:Omit<Parameters<typeof BaseMetric>[0],"caption">){return <BaseMetric {...props} caption="" hideCaption/>}

function buildItems(snapshot:TraderLinkCommunityDashboardSnapshot):readonly Item[]{
 const relations=new Map(snapshot.relationships.filter(row=>row.coachUserId===snapshot.viewer.userId).map(row=>[row.relationshipId,row]));
 const used=new Set<string>(),items:Item[]=[];
 for(const review of snapshot.tradeReviews){const relation=relations.get(review.relationshipId);if(!relation)continue;const task=snapshot.coachingTasks.filter(row=>row.relationshipId===review.relationshipId&&row.status==="open"&&!used.has(row.taskId)).sort((a,b)=>(a.dueAtUtc??"9999").localeCompare(b.dueAtUtc??"9999"))[0];if(task)used.add(task.taskId);items.push({id:`review:${review.reviewId}`,student:relation.studentDisplayName,plan:relation.planName,title:review.title,detail:review.reviewType==="multiple_trades"?`${review.roundTripIds.length} selected trades`:label(review.reviewType),type:"review",typeLabel:"Review",status:review.status==="requested"?"not_started":review.status==="in_review"?"in_progress":review.status,dueAt:task?.dueAtUtc??(review.periodEnd?`${review.periodEnd}T23:59:59.000Z`:null),href:`/communities/${snapshot.community.slug}/workspace/students/${review.relationshipId}`})}
 for(const task of snapshot.coachingTasks){if(used.has(task.taskId))continue;const relation=relations.get(task.relationshipId);if(!relation)continue;items.push({id:`task:${task.taskId}`,student:relation.studentDisplayName,plan:relation.planName,title:task.title,detail:task.priority==="high"?"High priority":"Coaching task",type:"task",typeLabel:"Task",status:task.status==="open"?"not_started":task.status,dueAt:task.dueAtUtc,href:`/communities/${snapshot.community.slug}/workspace/students/${task.relationshipId}`})}
 for(const session of snapshot.coachingSessions){const relation=relations.get(session.relationshipId);if(!relation)continue;items.push({id:`session:${session.sessionId}`,student:relation.studentDisplayName,plan:relation.planName,title:session.title,detail:"Session",type:"session",typeLabel:"Session",status:session.status==="scheduled"?"not_started":session.status,dueAt:session.scheduledAtUtc,href:`/communities/${snapshot.community.slug}/workspace/students/${session.relationshipId}`})}
 for(const teaching of snapshot.teachingItems){if(teaching.coachUserId!==snapshot.viewer.userId||teaching.status==="draft")continue;items.push({id:`teaching:${teaching.teachingId}`,student:teaching.audienceMode==="all_students"?"All students":`${teaching.students.length} students`,plan:snapshot.plans.find(plan=>plan.planId===teaching.planId)?.name??"Group coaching",title:teaching.title,detail:label(teaching.teachingType),type:"teaching",typeLabel:label(teaching.teachingType),status:teaching.status==="published"?"not_started":teaching.status,dueAt:teaching.scheduledAtUtc,href:`/communities/${snapshot.community.slug}/workspace/teaching`})}
 return items;
}

export function CoachWorkspaceNavigation({slug}:{slug:string}){return <Stack direction={{xs:"column",sm:"row"}} spacing={1} sx={{flexWrap:"wrap"}}><Button component={Link} href={`/communities/${slug}/workspace`}>Coaching Work</Button><Button component={Link} href={`/communities/${slug}/workspace/students`}>Students</Button><Button component={Link} href={`/communities/${slug}/workspace/teaching`}>Teaching</Button><Button component={Link} href={`/communities/${slug}/workspace/setup`}>Coach Setup</Button></Stack>}

export function CoachingWorkPage({snapshot}:{snapshot:TraderLinkCommunityDashboardSnapshot}){
 const [view,setView]=useState<View>("upcoming"),[days,setDays]=useState(5),[query,setQuery]=useState(""),[plan,setPlan]=useState("all"),[type,setType]=useState("all"),[workStatus,setWorkStatus]=useState("active"),[dueStatus,setDueStatus]=useState("all"),[sort,setSort]=useState("due_soonest"),[customStart,setCustomStart]=useState(""),[customEnd,setCustomEnd]=useState("");
 const now=useMemo(()=>new Date(),[]),all=useMemo(()=>buildItems(snapshot),[snapshot]);
 const range=useMemo(()=>{const today=day(now);if(view==="week"){const start=week(today);return {start,end:plus(start,7)}}if(view==="month")return {start:new Date(today.getFullYear(),today.getMonth(),1),end:new Date(today.getFullYear(),today.getMonth()+1,1)};if(view==="custom")return {start:customStart?new Date(`${customStart}T00:00:00`):null,end:customEnd?plus(new Date(`${customEnd}T00:00:00`),1):null};return {start:today,end:plus(today,Math.max(1,Math.min(days||1,365))) }},[customEnd,customStart,days,now,view]);
 const filtered=useMemo(()=>{const text=query.trim().toLowerCase();return all.filter(item=>{const due=item.dueAt?new Date(item.dueAt):null,state=dueState(item.dueAt,now),active=!(["completed","cancelled"] as string[]).includes(item.status),inRange=!due||((!range.start||due>=range.start)&&(!range.end||due<range.end));return inRange&&(plan==="all"||item.plan===plan)&&(type==="all"||item.type===type)&&(workStatus==="all"||(workStatus==="active"?active:item.status===workStatus))&&(dueStatus==="all"||state===dueStatus)&&(!text||`${item.title} ${item.student} ${item.plan} ${item.typeLabel} ${item.detail}`.toLowerCase().includes(text))}).sort((a,b)=>sort==="student"?a.student.localeCompare(b.student):sort==="plan"?a.plan.localeCompare(b.plan):(sort==="due_latest"?-1:1)*((a.dueAt?new Date(a.dueAt).getTime():Number.MAX_SAFE_INTEGER)-(b.dueAt?new Date(b.dueAt).getTime():Number.MAX_SAFE_INTEGER)))},[all,dueStatus,now,plan,query,range,sort,type,workStatus]);
 const planCounts=useMemo(()=>{const counts=new Map<string,number>();for(const item of filtered)counts.set(item.plan,(counts.get(item.plan)??0)+1);return [...counts].sort((a,b)=>b[1]-a[1]).slice(0,3)},[filtered]);
 const overdue=filtered.filter(item=>dueState(item.dueAt,now)==="overdue").length,dueToday=filtered.filter(item=>dueState(item.dueAt,now)==="due_today").length;
 return <Stack spacing={2}><CoachWorkspaceNavigation slug={snapshot.community.slug}/><Stack direction={{xs:"column",md:"row"}} spacing={1.5} sx={{alignItems:{md:"center"},justifyContent:"space-between"}}><Typography component="h2" variant="h2">Coaching Work</Typography><ToggleButtonGroup exclusive onChange={(_,value:View|null)=>value&&setView(value)} size="small" value={view}><ToggleButton value="upcoming">Upcoming</ToggleButton><ToggleButton value="week">Week</ToggleButton><ToggleButton value="month">Month</ToggleButton><ToggleButton value="custom">Custom</ToggleButton></ToggleButtonGroup></Stack>
 <DashboardPanel title="Filters"><Grid container spacing={1.5}>{view==="upcoming"?<Grid size={{xs:12,sm:4,lg:2}}><TextField fullWidth label="Number of days" onChange={event=>setDays(Number(event.target.value))} slotProps={{htmlInput:{min:1,max:365}}} type="number" value={days}/></Grid>:null}{view==="custom"?<><Grid size={{xs:12,sm:6,lg:2}}><TextField fullWidth label="Start date" onChange={event=>setCustomStart(event.target.value)} slotProps={{inputLabel:{shrink:true}}} type="date" value={customStart}/></Grid><Grid size={{xs:12,sm:6,lg:2}}><TextField fullWidth label="End date" onChange={event=>setCustomEnd(event.target.value)} slotProps={{inputLabel:{shrink:true}}} type="date" value={customEnd}/></Grid></>:null}<Grid size={{xs:12,sm:6,lg:3}}><TextField fullWidth label="Search" onChange={event=>setQuery(event.target.value)} value={query}/></Grid><Grid size={{xs:12,sm:6,lg:2}}><TextField fullWidth label="Coaching plan" onChange={event=>setPlan(event.target.value)} select value={plan}><MenuItem value="all">All plans</MenuItem>{[...new Set(all.map(item=>item.plan))].map(name=><MenuItem key={name} value={name}>{name}</MenuItem>)}</TextField></Grid><Grid size={{xs:12,sm:6,lg:2}}><TextField fullWidth label="Work type" onChange={event=>setType(event.target.value)} select value={type}><MenuItem value="all">All work</MenuItem><MenuItem value="review">Reviews</MenuItem><MenuItem value="task">Tasks</MenuItem><MenuItem value="session">Sessions</MenuItem><MenuItem value="teaching">Teaching</MenuItem></TextField></Grid><Grid size={{xs:12,sm:6,lg:2}}><TextField fullWidth label="Work status" onChange={event=>setWorkStatus(event.target.value)} select value={workStatus}><MenuItem value="active">Active work</MenuItem><MenuItem value="all">All statuses</MenuItem><MenuItem value="not_started">Not started</MenuItem><MenuItem value="in_progress">In progress</MenuItem><MenuItem value="delivered">Delivered</MenuItem><MenuItem value="completed">Completed</MenuItem><MenuItem value="cancelled">Cancelled</MenuItem></TextField></Grid><Grid size={{xs:12,sm:6,lg:2}}><TextField fullWidth label="Due status" onChange={event=>setDueStatus(event.target.value)} select value={dueStatus}><MenuItem value="all">All due dates</MenuItem><MenuItem value="overdue">Overdue</MenuItem><MenuItem value="due_today">Due today</MenuItem><MenuItem value="due_soon">Due soon</MenuItem><MenuItem value="scheduled">Scheduled</MenuItem></TextField></Grid><Grid size={{xs:12,sm:6,lg:2}}><TextField fullWidth label="Sort" onChange={event=>setSort(event.target.value)} select value={sort}><MenuItem value="due_soonest">Due soonest</MenuItem><MenuItem value="due_latest">Due latest</MenuItem><MenuItem value="student">Student</MenuItem><MenuItem value="plan">Plan</MenuItem></TextField></Grid></Grid></DashboardPanel>
 <Grid container spacing={2}><Grid size={{xs:6,md:4,lg:"grow"}}><Metric label="Total due" value={String(filtered.length)}/></Grid><Grid size={{xs:6,md:4,lg:"grow"}}><Metric label="Overdue" value={String(overdue)}/></Grid><Grid size={{xs:6,md:4,lg:"grow"}}><Metric label="Due today" value={String(dueToday)}/></Grid>{planCounts.map(([name,count])=><Grid key={name} size={{xs:6,md:4,lg:"grow"}}><Metric label={name} value={String(count)}/></Grid>)}</Grid>
 <DashboardPanel title="Upcoming work">{filtered.length?<><TableContainer sx={{display:{xs:"none",md:"block"}}}><Table size="small"><TableHead><TableRow><TableCell>Work</TableCell><TableCell>Plan</TableCell><TableCell>Type</TableCell><TableCell>Work status</TableCell><TableCell>Due status</TableCell><TableCell>Due date</TableCell><TableCell align="right">Action</TableCell></TableRow></TableHead><TableBody>{filtered.map(item=><DesktopRow item={item} key={item.id} now={now}/>)}</TableBody></Table></TableContainer><Stack divider={<Box sx={{borderBottom:1,borderColor:"divider"}}/>} sx={{display:{xs:"flex",md:"none"}}}>{filtered.map(item=><MobileCard item={item} key={item.id} now={now}/>)}</Stack></>:<DashboardUnavailableState compact description="" title="No coaching work in this period"/>}</DashboardPanel></Stack>
}
function DesktopRow({item,now}:{item:Item;now:Date}){const due=dueState(item.dueAt,now);return <TableRow hover><TableCell><Typography fontWeight={800}>{item.title}</Typography><Typography color="text.secondary" variant="caption">{item.student} · {item.detail}</Typography></TableCell><TableCell>{item.plan}</TableCell><TableCell>{item.typeLabel}</TableCell><TableCell><Chip color={statusColor(item.status)} label={statusLabel(item.status)} size="small"/></TableCell><TableCell>{due==="none"?"—":<Chip color={dueColor(due)} label={dueLabel(due)} size="small"/>}</TableCell><TableCell>{dateLabel(item.dueAt)}</TableCell><TableCell align="right"><Button component={Link} href={item.href} size="small" variant={item.status==="in_progress"?"contained":"outlined"}>{action(item)}</Button></TableCell></TableRow>}
function MobileCard({item,now}:{item:Item;now:Date}){const due=dueState(item.dueAt,now);return <Box sx={{py:2}}><Stack spacing={1.25}><Box><Typography fontWeight={800}>{item.title}</Typography><Typography color="text.secondary" variant="body2">{item.student} · {item.detail}</Typography></Box><Grid container spacing={1}><Grid size={6}><Typography color="text.secondary" variant="caption">Plan</Typography><Typography variant="body2">{item.plan}</Typography></Grid><Grid size={6}><Typography color="text.secondary" variant="caption">Type</Typography><Typography variant="body2">{item.typeLabel}</Typography></Grid><Grid size={6}><Typography color="text.secondary" variant="caption">Work status</Typography><Box sx={{mt:.5}}><Chip color={statusColor(item.status)} label={statusLabel(item.status)} size="small"/></Box></Grid><Grid size={6}><Typography color="text.secondary" variant="caption">Due status</Typography><Box sx={{mt:.5}}>{due==="none"?"—":<Chip color={dueColor(due)} label={dueLabel(due)} size="small"/>}</Box></Grid><Grid size={12}><Typography color="text.secondary" variant="caption">Due date</Typography><Typography variant="body2">{dateLabel(item.dueAt)}</Typography></Grid></Grid><Button component={Link} fullWidth href={item.href} variant={item.status==="in_progress"?"contained":"outlined"}>{action(item)}</Button></Stack></Box>}

export function StudentsPage({snapshot}:{snapshot:TraderLinkCommunityDashboardSnapshot}){const students=snapshot.relationships.filter(item=>item.coachUserId===snapshot.viewer.userId&&item.status==="active");return <><CoachWorkspaceNavigation slug={snapshot.community.slug}/><DashboardPanel title="Students"><Stack spacing={1}>{students.map(student=>{const work=snapshot.coachingTasks.filter(item=>item.relationshipId===student.relationshipId&&item.status==="open").length+snapshot.tradeReviews.filter(item=>item.relationshipId===student.relationshipId&&item.status!=="completed"&&item.status!=="cancelled").length,journal=snapshot.journalGrants.some(item=>item.relationshipId===student.relationshipId&&item.status==="active"),paused=student.accessStatus==="access_paused";return <Stack direction={{xs:"column",md:"row"}} key={student.relationshipId} sx={{alignItems:{md:"center"},borderBottom:1,borderColor:"divider",justifyContent:"space-between",py:1}}><Box><Stack direction="row" spacing={1}><Typography fontWeight={800}>{student.studentDisplayName}</Typography>{paused?<Chip color="error" label="Access paused" size="small"/>:null}</Stack><Typography color="text.secondary" variant="body2">{student.planName}</Typography>{paused?<Typography color="error" variant="caption">The Discord role required for this student’s coaching agreement could not be verified. New coaching work and delivery are paused.</Typography>:null}</Box><Stack direction="row" spacing={1} sx={{alignItems:"center",flexWrap:"wrap"}}><Chip label={`${work} work due`}/><Chip color={journal?"success":"default"} label={`Journal ${journal?"shared":"not shared"}`}/><Button component={Link} href={`/communities/${snapshot.community.slug}/workspace/students/${student.relationshipId}`} variant="contained">Open student</Button></Stack></Stack>})}{!students.length?<DashboardUnavailableState compact description="" title="No active students"/>:null}</Stack></DashboardPanel></>}
