"use client";
import {useState} from "react";
import {CoachingAgreementPanel} from "./coaching-agreement-panel";
import {StudentReviewRequest} from "./student-review-request";
import {StudentCoachingReview} from "./student-coaching-review";
import {Box,Button,Chip,Grid,MenuItem,Stack,TextField} from "@mui/material";
import {DashboardPanel,DashboardUnavailableState} from "@/app/dashboard-ui";
import type {TraderLinkCommunityDashboardSnapshot} from "@/src/modules/communities/contracts/traderlink-community-platform-contracts";
import {sendCommunityCoachingMessageAction,updateCommunityTeachingStudentAction,uploadCommunityCoachingImageAction} from "./community-actions";
import {CommunityTypography as Typography} from "./community-typography";
const stamp=(value:string|null)=>value?new Intl.DateTimeFormat("en",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"UTC"}).format(new Date(value))+" UTC":"";
export function StudentCoachingWorkspace({snapshot,isReview}:{snapshot:TraderLinkCommunityDashboardSnapshot;isReview:boolean}){
 const relationships=snapshot.relationships.filter(item=>item.studentUserId===snapshot.viewer.userId&&item.status==="active");
 const [selectedId,setSelectedId]=useState(relationships[0]?.relationshipId??"");
 const selected=relationships.find(item=>item.relationshipId===selectedId)??relationships[0];
 if(!selected)return <DashboardUnavailableState compact description="" title="No active coaching"/>;
 return <Stack spacing={2}>{relationships.length>1?<TextField label="Coach and plan" select value={selected.relationshipId} onChange={event=>setSelectedId(event.target.value)}>{relationships.map(item=><MenuItem key={item.relationshipId} value={item.relationshipId}>{item.coachDisplayName} · {item.planName}</MenuItem>)}</TextField>:null}<StudentRelationshipWorkspace key={selected.relationshipId} snapshot={snapshot} isReview={isReview} relationshipId={selected.relationshipId}/></Stack>;
}
function StudentRelationshipWorkspace({snapshot,isReview,relationshipId}:{snapshot:TraderLinkCommunityDashboardSnapshot;isReview:boolean;relationshipId:string}){
 const relationship=snapshot.relationships.find(item=>item.relationshipId===relationshipId&&item.studentUserId===snapshot.viewer.userId&&item.status==="active");
 if(!relationship)return <DashboardUnavailableState compact description="" title="No active coaching"/>;
 const id=relationship.relationshipId,reviews=snapshot.tradeReviews.filter(item=>item.relationshipId===id),sessions=snapshot.coachingSessions.filter(item=>item.relationshipId===id),teaching=snapshot.teachingItems.filter(item=>item.students.some(student=>student.relationshipId===id)),tasks=snapshot.coachingTasks.filter(item=>item.relationshipId===id),messages=snapshot.coachingMessages.filter(item=>item.relationshipId===id),images=snapshot.coachingAttachments.filter(item=>item.relationshipId===id&&item.targetType==="message"),paused=relationship.accessStatus==="access_paused";
 return <Stack spacing={2}>
  <CoachingAgreementPanel snapshot={snapshot} relationshipId={id} disabled={isReview}/>
  {paused?<DashboardPanel title="Coaching access paused"><Typography>TraderLink can no longer verify the Discord role required for this coaching service. If this is a mistake, contact your Discord server owner or administrator.</Typography></DashboardPanel>:null}
  <Grid container spacing={2}><Grid size={{xs:12,lg:7}}><DashboardPanel title="My coach"><Typography fontWeight={800}>{relationship.coachDisplayName}</Typography><Typography color="text.secondary" variant="body2">{relationship.planName}</Typography></DashboardPanel></Grid><Grid size={{xs:12,lg:5}}><DashboardPanel title="Upcoming"><Stack spacing={1}>{sessions.filter(item=>item.status==="scheduled").map(item=><Box key={item.sessionId}><Typography fontWeight={800}>{item.title}</Typography><Typography color="text.secondary" variant="body2">{stamp(item.scheduledAtUtc)}{item.durationMinutes?` · ${item.durationMinutes} min`:""}</Typography>{item.meetingUrl?<Button disabled={paused} href={item.meetingUrl} target="_blank" rel="noopener noreferrer">Join session</Button>:null}<Typography>{item.agenda}</Typography></Box>)}{tasks.filter(item=>item.status==="open").map(item=><Box key={item.taskId}><Typography fontWeight={800}>{item.title}</Typography><Typography color="text.secondary" variant="body2">{stamp(item.dueAtUtc)}</Typography></Box>)}</Stack></DashboardPanel></Grid></Grid>
  <Grid container spacing={2}><Grid size={{xs:12,lg:7}}><DashboardPanel title="Messages">{snapshot.questionAllowances?.[id]?<Chip color="info" label={`${snapshot.questionAllowances[id]!.remaining} questions remaining${snapshot.questionAllowances[id]!.renewsOn?` · Renews ${snapshot.questionAllowances[id]!.renewsOn}`:""}`}/>:null}<Stack spacing={1}>{messages.map(message=><Box key={message.messageId}><Typography fontWeight={800} variant="body2">{message.authorName}</Typography><Typography variant="body2">{message.body}</Typography></Box>)}{images.map(image=><Box key={image.attachmentId}><Typography color="text.secondary" variant="caption">{image.filename}</Typography><Box alt={image.filename} component="img" src={image.href} sx={{display:"block",maxHeight:280,maxWidth:"100%",mt:.5,borderRadius:2}}/></Box>)}</Stack>{relationship.studentMessagingEnabled?<Box action={isReview?undefined:sendCommunityCoachingMessageAction} component="form" sx={{mt:2}}><Hidden communitySlug={snapshot.community.slug} relationshipId={id}/><Stack direction={{xs:"column",sm:"row"}} spacing={1}><TextField fullWidth label="Message" name="body" required/><Button disabled={isReview||paused} type="submit" variant="contained">Send</Button></Stack></Box>:null}{relationship.studentMessagingEnabled?<Box action={isReview?undefined:uploadCommunityCoachingImageAction} component="form" encType="multipart/form-data" sx={{mt:1}}><Hidden communitySlug={snapshot.community.slug} relationshipId={id}/><input name="returnTo" type="hidden" value="student"/><input name="targetType" type="hidden" value="message"/><input name="targetId" type="hidden" value={id}/><Stack direction="row" spacing={1}><Button component="label" variant="outlined">Select chart<input accept="image/png,image/jpeg,image/webp" hidden name="image" type="file"/></Button><Button disabled={isReview||paused} type="submit">Send image</Button></Stack></Box>:null}</DashboardPanel></Grid>
  <Grid size={{xs:12,lg:5}}><DashboardPanel title="Lessons, classes and assignments"><Stack spacing={1}>{teaching.map(item=>{const assignment=item.students.find(student=>student.relationshipId===id);return <Box key={item.teachingId} sx={{borderBottom:1,borderColor:"divider",pb:1}}><Stack direction="row" sx={{justifyContent:"space-between"}}><Typography fontWeight={800}>{item.title}</Typography><Chip color={item.teachingType==="class"?"secondary":item.teachingType==="assignment"?"warning":"info"} label={item.teachingType}/></Stack><Typography variant="body2">{item.body}</Typography>{item.dueAtUtc?<Typography variant="caption">Due {stamp(item.dueAtUtc)}</Typography>:null}{item.recordingUrl?<Button disabled={paused} href={item.recordingUrl} target="_blank" rel="noopener noreferrer">Watch recording</Button>:null}{item.deliveryUrl?<Button disabled={paused} href={item.deliveryUrl} target="_blank">Open</Button>:null}{assignment?<Stack direction="row" spacing={1} sx={{alignItems:"center",mt:1}}><Chip color={assignment.status==="completed"?"success":assignment.status==="attending"?"info":"default"} label={assignment.status}/>{assignment.status!=="completed"?<Box action={isReview?undefined:updateCommunityTeachingStudentAction} component="form"><Hidden communitySlug={snapshot.community.slug} relationshipId={id}/><input name="teachingId" type="hidden" value={item.teachingId}/><input name="status" type="hidden" value="completed"/><Button disabled={isReview||paused} size="small" type="submit">Mark complete</Button></Box>:null}</Stack>:null}</Box>})}</Stack></DashboardPanel></Grid></Grid>
  <DashboardPanel title="Reviews"><Grid container spacing={2}>{reviews.map(review=><Grid key={review.reviewId} size={{xs:12,lg:6}}><StudentCoachingReview isReview={isReview} messagingEnabled={relationship.studentMessagingEnabled} paused={paused} review={review} snapshot={snapshot}/></Grid>)}</Grid>{relationship.studentTradeReviewsEnabled?<StudentReviewRequest communitySlug={snapshot.community.slug} disabled={isReview||paused} relationshipId={id}/>:null}</DashboardPanel>
  <DashboardPanel title="Coaching history"><Stack spacing={1}>{snapshot.coachingRecords.filter(item=>item.relationshipId===id&&item.visibility==="shared").map(item=><Box key={item.recordId}><Typography fontWeight={800}>{item.title}</Typography><Typography color="text.secondary" variant="caption">{item.recordType} · {stamp(item.occurredAtUtc)}</Typography><Typography variant="body2">{item.body}</Typography></Box>)}{sessions.filter(item=>item.status==="completed").map(item=><Box key={item.sessionId}><Typography fontWeight={800}>{item.title}</Typography><Typography variant="body2">{item.notes}</Typography></Box>)}</Stack></DashboardPanel>
 </Stack>;
}
function Hidden({communitySlug,relationshipId}:{communitySlug:string;relationshipId:string}){return <><input name="communitySlug" type="hidden" value={communitySlug}/><input name="relationshipId" type="hidden" value={relationshipId}/></>}
