"use client";
import {Box,Button,Chip,Grid,Stack,TextField} from "@mui/material";
import {DashboardPanel,DashboardUnavailableState} from "@/app/dashboard-ui";
import type {TraderLinkCommunityDashboardSnapshot} from "@/src/modules/communities/contracts/traderlink-community-platform-contracts";
import {replyCommunityReviewAction,requestCommunityTradeReviewAction,sendCommunityCoachingMessageAction,updateCommunityTeachingStudentAction,uploadCommunityCoachingImageAction} from "./community-actions";
import {CommunityTypography as Typography} from "./community-typography";
const stamp=(value:string|null)=>value?new Intl.DateTimeFormat("en",{month:"short",day:"numeric",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"UTC"}).format(new Date(value))+" UTC":"";
export function StudentCoachingWorkspace({snapshot,isReview}:{snapshot:TraderLinkCommunityDashboardSnapshot;isReview:boolean}){
 const relationship=snapshot.relationships.find(item=>item.studentUserId===snapshot.viewer.userId&&item.status==="active");
 if(!relationship)return <DashboardUnavailableState compact description="" title="No active coaching"/>;
 const id=relationship.relationshipId,reviews=snapshot.tradeReviews.filter(item=>item.relationshipId===id),sessions=snapshot.coachingSessions.filter(item=>item.relationshipId===id),teaching=snapshot.teachingItems.filter(item=>item.students.some(student=>student.relationshipId===id)),tasks=snapshot.coachingTasks.filter(item=>item.relationshipId===id),messages=snapshot.coachingMessages.filter(item=>item.relationshipId===id),images=snapshot.coachingAttachments.filter(item=>item.relationshipId===id),paused=relationship.accessStatus==="access_paused";
 return <Stack spacing={2}>
  {paused?<DashboardPanel title="Coaching access paused"><Typography>TraderLink can no longer verify the Discord role required for this coaching service. If this is a mistake, contact your Discord server owner or administrator.</Typography></DashboardPanel>:null}
  <Grid container spacing={2}><Grid size={{xs:12,lg:7}}><DashboardPanel title="My coach"><Typography fontWeight={800}>{relationship.coachDisplayName}</Typography><Typography color="text.secondary" variant="body2">{relationship.planName}</Typography></DashboardPanel></Grid><Grid size={{xs:12,lg:5}}><DashboardPanel title="Upcoming"><Stack spacing={1}>{sessions.filter(item=>item.status==="scheduled").map(item=><Box key={item.sessionId}><Typography fontWeight={800}>{item.title}</Typography><Typography color="text.secondary" variant="body2">{stamp(item.scheduledAtUtc)}</Typography></Box>)}{tasks.filter(item=>item.status==="open").map(item=><Box key={item.taskId}><Typography fontWeight={800}>{item.title}</Typography><Typography color="text.secondary" variant="body2">{stamp(item.dueAtUtc)}</Typography></Box>)}</Stack></DashboardPanel></Grid></Grid>
  <Grid container spacing={2}><Grid size={{xs:12,lg:7}}><DashboardPanel title="Messages"><Stack spacing={1}>{messages.map(message=><Box key={message.messageId}><Typography fontWeight={800} variant="body2">{message.authorName}</Typography><Typography variant="body2">{message.body}</Typography></Box>)}{images.map(image=><Box key={image.attachmentId}><Typography color="text.secondary" variant="caption">{image.filename}</Typography><Box alt={image.filename} component="img" src={image.href} sx={{display:"block",maxHeight:280,maxWidth:"100%",mt:.5,borderRadius:2}}/></Box>)}</Stack>{relationship.studentMessagingEnabled?<Box action={isReview?undefined:sendCommunityCoachingMessageAction} component="form" sx={{mt:2}}><Hidden communitySlug={snapshot.community.slug} relationshipId={id}/><Stack direction={{xs:"column",sm:"row"}} spacing={1}><TextField fullWidth label="Message" name="body" required/><Button disabled={isReview} type="submit" variant="contained">Send</Button></Stack></Box>:null}{reviews[0]&&relationship.studentMessagingEnabled?<Box action={isReview?undefined:uploadCommunityCoachingImageAction} component="form" encType="multipart/form-data" sx={{mt:1}}><Hidden communitySlug={snapshot.community.slug} relationshipId={id}/><input name="targetType" type="hidden" value="submission"/><input name="targetId" type="hidden" value={reviews[0].reviewId}/><Stack direction="row" spacing={1}><Button component="label" variant="outlined">Select chart<input accept="image/png,image/jpeg,image/webp" hidden name="image" type="file"/></Button><Button disabled={isReview} type="submit">Send image</Button></Stack></Box>:null}</DashboardPanel></Grid>
  <Grid size={{xs:12,lg:5}}><DashboardPanel title="Lessons, classes and assignments"><Stack spacing={1}>{teaching.map(item=>{const assignment=item.students.find(student=>student.relationshipId===id);return <Box key={item.teachingId} sx={{borderBottom:1,borderColor:"divider",pb:1}}><Stack direction="row" sx={{justifyContent:"space-between"}}><Typography fontWeight={800}>{item.title}</Typography><Chip color={item.teachingType==="class"?"secondary":item.teachingType==="assignment"?"warning":"info"} label={item.teachingType}/></Stack><Typography variant="body2">{item.body}</Typography>{item.deliveryUrl?<Button href={item.deliveryUrl} target="_blank">Open</Button>:null}{assignment?<Stack direction="row" spacing={1} sx={{alignItems:"center",mt:1}}><Chip color={assignment.status==="completed"?"success":assignment.status==="attending"?"info":"default"} label={assignment.status}/>{assignment.status!=="completed"?<Box action={isReview?undefined:updateCommunityTeachingStudentAction} component="form"><Hidden communitySlug={snapshot.community.slug} relationshipId={id}/><input name="teachingId" type="hidden" value={item.teachingId}/><input name="status" type="hidden" value="completed"/><Button disabled={isReview} size="small" type="submit">Mark complete</Button></Box>:null}</Stack>:null}</Box>})}</Stack></DashboardPanel></Grid></Grid>
  <DashboardPanel title="Reviews"><Grid container spacing={2}>{reviews.map(review=><Grid key={review.reviewId} size={{xs:12,lg:6}}><Box sx={{border:1,borderColor:"divider",borderRadius:2,p:2}}><Stack direction="row" sx={{justifyContent:"space-between"}}><Box><Typography fontWeight={800}>{review.title}</Typography><Typography color="text.secondary" variant="caption">{review.reviewType.replaceAll("_"," ")}</Typography></Box><Chip color={review.status==="completed"?"success":"warning"} label={review.status.replaceAll("_"," ")}/></Stack>{review.status==="completed"&&review.coachFeedback?<ReviewSection title="Review" value={review.coachFeedback}/>:null}{review.status==="completed"&&review.wentWell?<ReviewSection title="What went well" value={review.wentWell}/>:null}{review.status==="completed"&&review.needsWork?<ReviewSection title="What needs work" value={review.needsWork}/>:null}{review.status==="completed"&&review.previousFocusAssessment?<ReviewSection title="Progress on previous focus" value={review.previousFocusAssessment}/>:null}{review.status==="completed"&&review.nextFocus?<ReviewSection title="Next focus" value={review.nextFocus}/>:null}{review.status!=="completed"&&review.studentContext?<Typography sx={{mt:1}} variant="body2">{review.studentContext}</Typography>:null}{snapshot.reviewReplies.filter(reply=>reply.reviewId===review.reviewId).map(reply=><Box key={reply.replyId} sx={{mt:1}}><Typography fontWeight={700} variant="body2">{reply.authorName}</Typography><Typography variant="body2">{reply.body}</Typography></Box>)}<Box action={isReview?undefined:replyCommunityReviewAction} component="form" sx={{mt:1}}><Hidden communitySlug={snapshot.community.slug} relationshipId={id}/><input name="reviewId" type="hidden" value={review.reviewId}/><Stack direction="row" spacing={1}><TextField fullWidth label="Reply" name="body"/><Button disabled={isReview} type="submit">Reply</Button></Stack></Box></Box></Grid>)}</Grid>{relationship.studentTradeReviewsEnabled?<Box action={isReview?undefined:requestCommunityTradeReviewAction} component="form" sx={{mt:2}}><Hidden communitySlug={snapshot.community.slug} relationshipId={id}/><Grid container spacing={1}><Grid size={{xs:12,md:4}}><TextField fullWidth label="Review title" name="title" required/></Grid><Grid size={{xs:12,md:5}}><TextField fullWidth label="What you want reviewed" name="studentContext"/></Grid><Grid size={{xs:12,md:3}}><Button disabled={isReview} fullWidth sx={{height:56}} type="submit" variant="outlined">Request review</Button></Grid></Grid></Box>:null}</DashboardPanel>
  <DashboardPanel title="Coaching history"><Stack spacing={1}>{snapshot.coachingRecords.filter(item=>item.relationshipId===id&&item.visibility==="shared").map(item=><Box key={item.recordId}><Typography fontWeight={800}>{item.title}</Typography><Typography color="text.secondary" variant="caption">{item.recordType} · {stamp(item.occurredAtUtc)}</Typography><Typography variant="body2">{item.body}</Typography></Box>)}{sessions.filter(item=>item.status==="completed").map(item=><Box key={item.sessionId}><Typography fontWeight={800}>{item.title}</Typography><Typography variant="body2">{item.notes}</Typography></Box>)}</Stack></DashboardPanel>
 </Stack>;
}
function Hidden({communitySlug,relationshipId}:{communitySlug:string;relationshipId:string}){return <><input name="communitySlug" type="hidden" value={communitySlug}/><input name="relationshipId" type="hidden" value={relationshipId}/></>}
function ReviewSection({title,value}:{title:string;value:string}){return <Box sx={{mt:1.5}}><Typography fontWeight={800} variant="body2">{title}</Typography><Typography variant="body2">{value}</Typography></Box>}
